### ISSUE TITLE
qri remove has many fsi bugs

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1000]
First off, running `qri remove` with no dataset deference (outside or inside of FSI) does nothing but also prints no output.

Running `qri remove` in FSI also ignores the dataset reference in .qri-ref. So even running `qri remove --revisions=2` inside FSI will do nothing.

In FSI, running `qri remove --revisions=2 me/test_ds` will remove 2 versions from the repo, but won't update the working directory. So `qri status` will show dirty files and the user has to use `qri restore` to get to a clean directory.

*However*, run the previously mentioned command *will* remove the link from the repo's fbs file, but *not* modify the `.qri-ref` in the working directory. Running future commands will return the error "dataset is not linked to the filesystem". We should be treating the .qri-ref file as authoritative and fixing up the fbs instead.

In addition, .qri-ref should be updated so that it contains the dataset ref path after a `remove` command.

**Comment by b5** [comment]
very fitting that issue #1000 is just like "hey, there's a bunch of bugs here".

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1012.
