### ISSUE TITLE
Add a more detailed automatic commit message when importing

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1054]
We currently say "Created Dataset" in the commit message title.  I thought it might be good to be more specific "Created Dataset from foobar.csv" to be more clear about the connection between the original file and the new Qri dataset.

**Comment by dustmop** [comment]
I'm a big fan of this. Recently added _some_ improvements to our automatic commit messages (https://github.com/qri-io/qri/commit/db938dd792f1c867bc90f7a29353e441b8c69cb2), but the feature is incomplete, and this is a great suggestion.

**Comment by dustmop** [comment]
I quickly looked into doing this by adding a "FileHint" variable in `Save` in `lib/datasets.go`, assigned either the `--file` flag or `--body` flag, whichever is non-empty. This has to get sent into `base/save.go`, and `base/dsfs/dataset.go`, which modifies lots of functions by adding another string parameter, which gets a bit messy.

Another approach would be adding a FileHint transient field on dataset.Dataset, which wouldn't require changing any function call arguments. @b5 you have any thoughts on this?

**Comment by b5** [comment]
Into the ideal, not super into the idea of modifying the dataset definition for this. dataset.Dataset should be driven by an independent spec free from the idiosyncrasies of qri software. If we really want it, we should clean up our function signatures, maybe considering passing an arguments struct.

**Comment by dustmop** [comment]
Implemented by https://github.com/qri-io/qri/pull/1286.
