### ISSUE TITLE
binary doesnt work on mosx catalina

### ISSUE THREAD

**Issue by zubairq** [qri-io/qri#1066]
Trying to run on latest MacOS gives following error:

/Users/fquraish/Downloads/qri_darwin_386/qri ; exit;
zsh: bad CPU type in executable: /Users/fquraish/Downloads/qri_darwin_386/qri

[Process completed]

**Comment by ramfox** [comment]
Hi! the `386` version is for 32 bit machines (`i386`)

The `amd64` version is for 64 bit machines (also known as `x86_64`)

Here is a link to help figure out what version you have:
https://apple.stackexchange.com/questions/12666/how-to-check-whether-my-intel-based-mac-is-32-bit-or-64-bit

Here is a link that talks a little bit about the different versions: http://www.callstack.in/tech/blog/difference-between-the-i386-download-and-the-amd64-94
