### ISSUE TITLE
Is there a way to fetch a list of all qri datasets and also a specific one without downloading anything?

### ISSUE THREAD

**Issue by breck7** [qri-io/qri#1068]
Sorry if this is a dumb question—I haven't used IPFS before—but is there a page where I can see all the datasets currently on QRI, and also access them, via traditional get requests?

I'd love to explore what's currently in the catalog.

**Comment by ramfox** [comment]
hi there!

Take a look at our website where we host datasets on the traditional web for exactly what you want to do: explore what's out there before downloading to your computer: [cloud.qri.io](http://cloud.qri.io)

**Comment by breck7** [comment]
Thanks @ramfox ... However, the link isn't working for me.

**Comment by ramfox** [comment]
my b, fixed

**Comment by breck7** [comment]
Thanks!!
