### ISSUE TITLE
Desktop wants DetailedDatasetRef to have a few extra fields

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1092]
I'm currently working on sewing the new `DetailedDatasetRef` API response into qri Desktop (qri-io/desktop#428) and there are some fields that desktop expects which aren't currently reported. 

The biggest two are:

* commit count
* `structure.format`

There are other expected fields that require a little more discussion:
* logbook identifier (we haven't formalized how these will be used yet)
* publication status (we need to talk about what _published_ actually means first) 

I'd love it if we could get the first two fields ASAP. We should hash out what exactly we mean for the other two first.

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/commit/e69c71d1e03b7a9a22f6c9312ab7ee7c12c66b51#diff-e2f34a24fb2c0c6aa9a5fe302a94eb53. Now named `VersionInfo`.
