### ISSUE TITLE
Ability to fully delete projects

### ISSUE THREAD

**Issue by sgammon** [qri-io/qri#1113]
I tried to setup a project with Qri using the command line, but then later discovered that my command line client, acquired from Brew, was out of date (filed as #1111). So I updated my command line.

Then, I deleted the project on-disk (it had not been published). I assumed this was enough to delete it. But upon later trying to re-setup the project, Qri tells me there is a project that already exists that poses a name conflict.

How can I fully delete this old project? I tried with `qri remove` as well and that didn't seem to find it, at the name `me/<dataset>` or `<username>/<dataset>` or just `<dataset>`.

**Comment by dustmop** [comment]
Hi @sgammon! Thanks for trying out qri, and for filing all of these issues.

For deleting a dataset, there are two aspects that are relevant. One is the "checked out" version or the "working directory", which is a directory on your filesystem containing "structure.json", etc. It sounds like you deleted that manually. Then, qri also has a database like system called the "repository", and it sounds like the dataset still exists there, which is what causes your name conflict.

When you run `qri list` do you see the dataset with the name `me/<dataset>` as expected? If so, running `qri remove me/<dataset>` should remove it from your repository. What's the error that that command gives you?

**Comment by sgammon** [comment]
sorry, i should have clarified. i do not see any entries for `qri list`, and running `qri remove me/<dataset>` returns that it cannot locate the dataset.

the only reason i know it still knows about it, is that it won't let me re-initialize a project of the same name.

**Comment by dustmop** [comment]
What's the error you're getting when trying to create a new project? A screenshot would be great.

**Comment by sgammon** [comment]
sure thing

output of `qri list` (shows the project after i created a second one, under a new name, by adding `-sample`):
<img width="648" alt="Screen Shot 2020-02-11 at 10 48 27 PM" src="https://user-images.githubusercontent.com/171897/74309860-9f973300-4d20-11ea-9baf-fcd75e227a55.png">

output of trying to create a new project with the name of the deleted project on-sidk (`eventstream`):
<img width="1276" alt="Screen Shot 2020-02-11 at 10 49 36 PM" src="https://user-images.githubusercontent.com/171897/74309925-c8b7c380-4d20-11ea-815b-bdcb21bfd9f3.png">

**Comment by dustmop** [comment]
Looks like you've found a bug we didn't know about, I'm able to reproduce. It seems that the "logbook", our system for coordinating changes, doesn't interact nicely with deleting folders directly from the file system if they've been created with the `init` command. Thank you for finding this, there's going to be a couple of fixes that come out of this.

**Comment by dustmop** [comment]
Forgot to follow-up, but this was fixed last week, via https://github.com/qri-io/qri/pull/1119. You can now delete a dataset, even one with errors, using `qri remove -f me/<dataset_name>`. The force flag will keep going despite errors and clean everything up.
