### ISSUE TITLE
Qri lets you create datasets with invalid names

### ISSUE THREAD

**Issue by sgammon** [qri-io/qri#1116]
If you create a dataset with a dash in it, `qri` doesn't complain for the `init` command. But then when you try to `qri save`, it yields the following error:

```
invalid name: error: illegal name 'name-with-dashes', names must start with a letter and consist of only a-z,0-9, and _. max length 144 characters
```

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1122. Will be included in the next release, or you can pull and rebuild if working off of HEAD.
