### ISSUE TITLE
Error in delete dataset

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#112]
Request URL: http://localhost:3000/datasets/ipfs/QmaYSCvUS7ow3WnXLEBscsdd5CvyibCnjCkvZnuYFHFKBs/dataset.json
Method: DELETE
payload:
{name: "epaToxicology", path: "/ipfs/QmaYSCvUS7ow3WnXLEBscsdd5CvyibCnjCkvZnuYFHFKBs/dataset.json"}

response:
{
  "meta": {
    "code": 500,
    "error": "QmZZRkZG5C4qatWSaGWFJgGZ24zxSn6m9GhRXfwbm6y4Er is pinned indirectly under QmaYSCvUS7ow3WnXLEBscsdd5CvyibCnjCkvZnuYFHFKBs"
  }
}

**Comment by b5** [comment]
closed by #155
