### ISSUE TITLE
refactor request: add additional details to the websockets response

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1124]
Working on implementing websockets on the desktop app.

Right now, I'm trying to understand the best way to know whether or not, while viewing a dataset on the workbench, we should fetch status because something has changed.

The `modify` response comes back as such:

```
{
  Type: "modify", 
  Source: "/Users/ramfox/Work/datasets/synths/body.csv", 
  Destination: "", 
  Time: "2020-02-14T16:39:34.487226-05:00"
}
```

Unfortunately, this doesn't give the app enough information about whether or not we should re-fetch anything we are currently working on. 

While we have the filename and folder, this does not mean that the dataset name is the same as the directory name. We also have no way of knowing the username, and we are allowed to check-out datasets that are not in our namespace, so we need to know.

Can the backend do some more translating and send the username and name of the dataset along with the rest of the given info?

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1125.
