### ISSUE TITLE
bug(websockets): when a dataset is checked out, inited, removed, renamed, update the watchlist

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1127]
as per this comment:
https://github.com/qri-io/qri/blob/4b58c7d8afc7214d1d97090f8780dca0120e05ee/api/websocket.go#L110

We need to be able to have the qri process running, then check out a dataset, and have that checked out folder be added to the watch list.

In the new frontend/websockets paradigm, the frontend is relying on the watch list to be accurate, as we rely on the websocket messages to inform the user and limit/unlock actions (such as 'commit', the user cannot 'commit' unless something has changed. We know something has changed because the backend has sent us a websocket message)

PR qri-io/desktop#452 relies on the assumption that as soon as a dataset is checked out, it will send over accurate modification/removal/creation/rename messages

**Comment by dustmop** [comment]
https://github.com/qri-io/qri/pull/1128 fixes this for the checkout case. I think we can hold off for now on the other; init is currently not used in Desktop, remove is okay not to handle (it's merely inefficient, not incorrect), and rename will require some planning.
