### ISSUE TITLE
bug(get): different responses for components w/ scriptPaths in linked vs non linked dataset

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1129]
Currently working on the feature to allow users to edit datasets directly in the Desktop app.

When requesting a Dataset from the backend (`/peername/datasetname`) of a linked dataset, the dataset comes back with the `Readme.ScriptBytes` field hydrated.

However, when requesting a non-linked dataset at the same endpoint, the `Readme.ScriptPath` field is hydrated, not the `ScriptBytes` field.

Requesting that Datasets return with the same expected fields hydrated for both fsi `true` & `false`.

I would prefer it if `Readme.ScriptBytes` were the chosen field, but would understand if we need to switch to using a `Selectors` param in the get request in order to get the `ScriptBytes`.

**Comment by b5** [comment]
closed by #1135
