### ISSUE TITLE
Error saving query and adding dataset from peer

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#113]
Request URL: http://localhost:3000/add/ipfs/QmWj1kzB152RAFoq2BAdCdGsoLeFVZwvFJKMKdinwxxAJb/dataset.json?name=comicAppearances
Request method: POST
Payload:
`{
  description: "select name, appearances from comics limit 10", message: ""
}`

response:
`
{
  "meta": {
  "code": 500,
  "error": "error fetching file: error resolving hash: invalid 'ipfs ref' path"
  }
}`
*********

also same error adding dataset from peer:

Request URL:http://localhost:3000/add/ipfs/QmcvCHEubYxE228qNEy4GBG6zCekRmy21Ae7RZF9tq4144/dataset.json?name=t_3mHPJkPMJZeVDa
Request Method:POST
Payload: 
`{description: "", message: ""}`

response:
`{
  "meta": {
    "code": 500,
    "error": "error fetching file: error resolving hash: invalid 'ipfs ref' path"
  }
}`

**Comment by b5** [comment]
closed by #142
