### ISSUE TITLE
executable bit not set on binary releases, date is wrong as well

### ISSUE THREAD

**Issue by feep** [qri-io/qri#1138]
https://github.com/qri-io/qri/releases/download/v0.9.4/qri_linux_amd64.zip

Executable bit is not set.
Modified date is 12/31/1979.

I did not check any other architectures.

**Comment by b5** [comment]
Os X version _is_ executable, but creation date is still set wrong:
```
.rwxr-xr-x@ 65M rusty 1979-11-30 qri
```

**Comment by feep** [comment]
1979, but different month? Why? 

Why do strange things happen?

**Comment by feep** [comment]
@b5 Executable and date look good.

I am no expert on permissions, but generally the rule is 'If you don't need it, don't set it'.

Need read in order to execute, but binaries are almost always writable only by root, `.rwxr-xr-x `.

I will check the mac zip when I get on that machine. Should be fine.

```bash
❯ curl -L -O 'https://github.com/qri-io/qri/releases/download/v0.9.5/qri_darwin_amd64.zip'

~/qri
❯ unzip qri_darwin_amd64.zip 
Archive:  qri_darwin_amd64.zip
 extracting: qri                     
 extracting: readme.md               

~/qri
❯ ls qri
.rwxrwxrwx 64M rusty 02-27 09:22 qri```

**Comment by feep** [comment]
Wow, gave myself a scare there.

```bash
❯ ./qri
Failed to execute process './qri'. Reason:
exec: Exec format error
The file './qri' is marked as an executable but could not be run by the operating system.
```

See my error? In the previous comment?

Downloaded the mac binary. Giggle.

Anyway, dates and executable are correct on the mac version, too. I'll test if it works later.
