### ISSUE TITLE
`qri init` does not mention the name length max of 144 chars

### ISSUE THREAD

**Issue by feep** [qri-io/qri#1153]
You fixed #1116 before I tried to file it. Thanks.

`qri init` does not mention the max length for names, but rejects them anyway.

```
❯ qri init
Name of new dataset [scratch]: a234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
Format of dataset, csv or json [csv]:   
dataset name must start with a letter, and only contain letters, numbers, and underscore

❯ qri version
0.9.6
```

That name `a234...` passes all the criteria mentioned in the error message, but it is 160 characters long.

Also, it uses a different error message than `qri save`.

```
❯ qri save
for linked dataset [feep/en.wikipedia.org,List_of_highest-grossing_films,Highest-grossing_films]invalid name: error: illegal name 'en.wikipedia.org,List_of_highest-grossing_films,Highest-grossing_films', names must start with a letter and consist of only a-z,0-9, and _. max length 144 characters
```

That’s probably 0.9.5. Can’t reproduce, because you fixed the init bug. =]

Yeah. I know, ridiculous name. I had reasons™.

They don’t call me the human fuzz tester for nothin’.

**Comment by dustmop** [comment]
Fixed the `qri init` issue by https://github.com/qri-io/qri/pull/1208.
