### ISSUE TITLE
Unable to "Export This Version" in Qri Desktop

### ISSUE THREAD

**Issue by VarsMolta** [qri-io/qri#1161]
When I try to export a qri cloud dataset in the Qri Desktop tool, it doesn't seem to work. The directory where I tried ti export is still blank. 
Using Qri Desktop v0.4.0

**Comment by b5** [comment]
Thanks so much for filing @VarsMolta, and apologies for the delay in responding sooner. We'll take a look & report back in the next day or two

**Comment by mydogspies** [comment]
I have exactly the same problem. Also using 0.4.0. I am on Windows 10, Enterprise with no AV's other than Defender, no special permission settings or anything out of the ordinary. Tried to save to various locations including other mounted physical drives. Does Qri produce a log file I can post maybe?
