### ISSUE TITLE
qri registry signup should not use a --password command-line flag

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1163]
It's bad practice to use a command-line flag for setting or sending a password. Onlookers can easily see the password typed into the screen. The password remains visible until scrolled off screen. By default, the password will get saved in bash's history in plain text. 

A better thing to do is to have a non-echoing prompt to get the user's password: https://stackoverflow.com/questions/2137357/getpasswd-functionality-in-go

**Comment by b5** [comment]
Big fan of this. I'd love to see this addressed ASAP

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1199.
