### ISSUE TITLE
Unlink deletes .qri-ref in the current directory, even if that’s not where the specified dataset was

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/qri#1169]
Calling `qri fsi unlink me/some_dataset` or `qri fsi unlink me/some_dataset path/to/some_other_dataset` (where `me/some_dataset` is linked to a different directory than `path/to/some_other_dataset`) from a different directory than the specified dataset does not remove the `.qri-ref` file from the dataset’s linked directory and instead attempts to delete it from the working directory (woe unto you if you happen to call this from a different dataset’s linked directory like I did).

Steps to reproduce:

1. Checkout one dataset somewhere.
2. Checkout a different dataset in another directory.
3. `cd` into the second dataset’s directory.
4. Run `qri fsi unlink <name of first dataset>`

Result:

The first dataset is unlinked, but the directory it was linked to still has a `.qri-ref` file. The current directory (for the second dataset, which should still be linked) does *not* have a `.qri-ref` file.

Expected:

The directory for the first dataset should no longer have a `.qri-ref` file and the directory for the second dataset should still have an unaltered `.qri-ref` file.

It looks like this happens because explicitly specifying a dataset ref results in a ref object with no directory path: https://github.com/qri-io/qri/blob/924157c253bf571ec9df92b0fd63e316e67bc6ad/cmd/ref_select.go#L113-L122

and: https://github.com/qri-io/qri/blob/924157c253bf571ec9df92b0fd63e316e67bc6ad/cmd/ref_select.go#L43-L45

Then the call to unlink sets the directory to whatever directory was attached to the ref without checking anything. Since it initializes to an empty string, that winds up implying the current working directory: https://github.com/qri-io/qri/blob/924157c253bf571ec9df92b0fd63e316e67bc6ad/cmd/fsi.go#L108-L113

And the actual unlink logic never sanity checks the directory path it’s given: https://github.com/qri-io/qri/blob/924157c253bf571ec9df92b0fd63e316e67bc6ad/fsi/fsi.go#L201-L210

I’m not sure exactly where in here the right place to do some checking is, but maybe `cmds.fsi.Unlink` should be calling `GetLinkedRefSelect()` of the ref before grabbing the refs directory?

**Comment by dustmop** [comment]
Should have replied earlier, apologies. `NewExplicitRefSelect` is behaving correctly and shouldn't change. The actual bug is a combination of `Unlink` in `cmd/fsi.go` always sending a blank Dir value, and then `fsi/fsi.go` doing the wrong thing with it. It should be calling `CanonicalizeDatasetRef` to get the ref's FSIPath, and then sending that to `removeLinkFile`.

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1213.
