### ISSUE TITLE
`.DS_Store` trips up `qri remove --all --force`

### ISSUE THREAD

**Issue by feep** [qri-io/qri#1190]
This isn’t qri’s fault. It is the Finder crapping all over the filesystem

All the same, you are going to have Mac users.

Do we want to special case a directory containing only `.DS_Store` as empty?

```
❯ qri remove --all --force 
for linked dataset [feep/ca_parks_starlark]

remove /Users/rusty/qri/caparks/qri/starlark: directory not empty

❯ ls
.rw-r--r--@ 6.1k rusty 03-16 00:55 -I .DS_Store
```

**Comment by dustmop** [comment]
I think the best bet here would be to get an explicit list of "low-information" files that `remove --force` should be okay with deleting. Definitely `.DS_Store`, but there's also things like `.thumbs.db` and some other Windows specific files such as `desktop.ini`. Would be nice to have a well-curated list that is generally agreed upon, and then we should document that as well.

**Comment by feep** [comment]
A commented blacklist here:

https://github.com/sindresorhus/junk/blob/a7c280daddca13fe5d2f731235b97bdfb5940fda/index.js#L3

More, but that one seems pretty good.

https://github.com/search?q=.ds_store+thumbs.db

**Comment by Arqu** [comment]
Just to bring our slack conversation back into this:
- I wanted to know the intention of --force; Is it just to completely wipe a dataset and anything associated with the directory or purely just qri related files hence the need for an ignore list of common low value files.
It's the latter.
