### ISSUE TITLE
`qri search` does not work while online/via RPC

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/qri#1193]
Normally, running `qri search <something>` works just fine. e.g:

```sh
$ qri search b5
⠒ showing 10 results for 'b5'
1   b5/texas_tceq_lynchburg_ferry_auto_gc
    https://qri.cloud/b5/texas_tceq_lynchburg_ferry_auto_gc
    /ipfs/QmPBYAg2fPwNhorAR42eUaj7ib7nRWhXTUr6p15R8Y6w3J
    Lynchburg Ferry [23] Daily Summary
    416 kB, 1556 entries, 9299 errors

2   b5/texas_tceq_deer_park_auto_gc
    https://qri.cloud/b5/texas_tceq_deer_park_auto_gc
    /ipfs/QmUVPxT4vm1KtZPnbSADbkn7162zHMe8xq3MGNxngYmifw
    Texas TCEQ: Hou.DeerPrk2 Daily Summary time series
    105 kB, 403 entries, 1935 errors

3   b5/awesome_csv
    https://qri.cloud/b5/awesome_csv
    /ipfs/Qmdikr7oqF69ZvKGwq1CuBYgmgfNi632T1wUG3Ng9qgrBk
    6.5 kB, 50 entries, 0 errors
...
```

However, if I am running a Qri node in the background, I instead get an error:

```sh
$ qri search b5 --log-all
12:24:30.826 DEBUG        lib: --log-all set: turning on logging for all activity lib.go:323
12:24:30.828 DEBUG        lib: using RPC address :2504 lib.go:337
12:24:30.828 DEBUG        cmd: running cmd ["qri" "search" "b5" "--log-all"] qri.go:131
reading body EOF
```

And the Qri node logs (since I have `--log-all` set):

```
DEBUG     qriapi: Websocket accept error: failed to accept websocket connection: websocket protocol violation: Connection header "" does not contain Upgrade websocket.go:58
```

This is happening both on v0.9.6 and 7c5d94a589f6f137f8508d43f56d1554c4a004d0 (tip of master for me right now).

**Comment by dustmop** [comment]
> reading body EOF
This error happens when go can't serialize data to sent over the rpc channel. It can happen when one of the parameters to our rpc-enabled functions (perhaps `search`) has a field which is a File or something that won't serialize. These can be painful to track down.

> DEBUG     qriapi: Websocket accept error: failed to accept websocket connection: websocket protocol violation: Connection header "" does not contain Upgrade websocket.go:58
I think this is spurious noise, though I'm not totally sure.

**Comment by Mr0grog** [comment]
>> DEBUG qriapi: Websocket accept error: failed to accept websocket connection: websocket protocol violation: Connection header "" does not contain Upgrade websocket.go:58
>
> I think this is spurious noise, though I'm not totally sure.

I was wondering if that was the case, since I feel like I’ve seen it fairly often in other scenarios and it didn’t appear to be causing problems. FWIW, though, it was reliably getting logged exactly once and exactly when I ran the `search` command. (Even when my qri node had settled out and was logging nothing else.)

**Comment by Arqu** [comment]
@Mr0grog thanks for catching this!
