### ISSUE TITLE
`print('string')` does not work in a transform.

### ISSUE THREAD

**Issue by feep** [qri-io/qri#1194]
`print()` does not work. `error()` does.

Minimal test case:
```
❯ qri version
0.9.6

❯ cat> error.star
def transform(ds, ctx):
    print("print hello")
    error("error hello")

❯ qri save --dry-run -f error.star me/humba
🏃🏽‍♀️ dry run
Traceback (most recent call last):
  transform.star:3:10: in transform
  <builtin>: in error
Error: transform error: "error hello"
```

**Comment by dustmop** [comment]
This definitely used to work. I have a suspicion that we changed how stdout and stderr are being handled, and since there was no unit test for `print`, we didn't realize that we changed the functionality.
