### ISSUE TITLE
bug(checkout): checking out a dataset that already has been checked out still creates a directory

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1195]
`qri checkout` isn't removing the new directory on error.

To recreate:

1) checkout a dataset or find a dataset that has already been checked out, let's say it's `test_dataset`
2) with an instance of qri running, curl:
`curl 'http://localhost:2503/checkout/ramfox/test_dataset?dir=/some/path/datasets/test_dataset_2'`
3) will return with an error:
```
{
  "meta": {
    "code": 500,
    "error": "'ramfox/test_dataset' is already linked to /some/path/datasets/test_dataset"
  }
}
```
4) but, if you list the directories inside the `/dataset` directory, you will find `test_dataset`

initially filed in qri-io/desktop#480

**Comment by dustmop** [comment]
Whoops, still open.
