### ISSUE TITLE
Qri Save with new version of transform results in `error saving: no changes`

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1215]
Using 0.9.6-dev on CLI.  Ran `qri save --file catalog-transform.star  me/catalog` and successfully ran the transform script, creating a new dataset.  

Added some comments to the transform script file and attempted to save again: `qri save --file catalog-transform.star  me/catalog` and got `error saving: no changes`

I expect to be able to create a new version of the dataset with the same body but with a new version of the transform script.

**Comment by dustmop** [comment]
This should be fixed by https://github.com/qri-io/qri/pull/1222, could you give it a shot when you get a chance, @chriswhong?

**Comment by b5** [comment]
we were tinkering with this today, is this closable?

**Comment by chriswhong** [comment]
Looks like I'm seeing `no changes` as expected.  Close it!
