### ISSUE TITLE
cli quickstart docs use old command flags

### ISSUE THREAD

**Issue by Arqu** [qri-io/qri#1219]
The command for [this](https://qri.io/docs/getting-started/qri-cli-quickstart#connect-your-keypair-to-your-qri-cloud-account) and [this](https://qri.io/docs/getting-started/qri-cli-quickstart#sign-up-for-a-qri-account) section says that we use `--pasword` to pass in the password, which is no longer true as of https://github.com/qri-io/qri/pull/1199. It's now prompted for on the terminal.

**Comment by b5** [comment]
QuickStart docs on the website? If so, mind moving this issue to https://github.com/qri-io/website?
