### ISSUE TITLE
Consolidating protocols, APIs and interfaces used within Qri

### ISSUE THREAD

**Issue by Arqu** [qri-io/qri#1224]
As the title states, we should consider what is currently being used within Qri and aim to consolidate and standardise as much as possible, and where having multiple interfaces aim to have a common source and contract in place.
One of the recent thoughts has been about introducing gRPC instead of our current implementation and basing things around protobufs. 

This issue is mostly to trigger a discussion and track the reasoning behind future decisions.

**Comment by VarsMolta** [comment]
What is the current implementation using? Is the current implementation hampering development efforts that standardization would help with?

**Comment by Arqu** [comment]
@VarsMolta to answer you directly, it's a blend between having issues with the current setup (RPC calls are currently not cancelable), hard to debug and present with user friendly messages, but also things like uniformity across interfaces. So it's a pallete of things we want to explore a bit further.

As for the wider discussion pasting some of @b5 comments here:

> My assumptions going into this have been:
> A JSON HTTP api is a required minimum
> Ditto for websockets, but mainly for “deep integration” projects like desktop & CLI. I don’t think websockets needs to be well documented
> We want to integrate with Apache Arrow one day, which means required literacy in flatbuffers
> I really like gRPC because it formalizes our Data Structures conversation. That said, I think we should be doing that anyway, and integrating that thinking into our JSON API
> The other technology I’d want to put on the table here is graphQL
> 
> Counting API serialization formats & their rough distrubtion of use, we have:
> JSON (90%)
> Flatbuffers (~9%)
> CBOR (1%, only dsync is using this at the moment) 
> 
> Counting communication protocols we have:
> HTTP
> LibP2P (TCP/IP, HTTP3 aka QUIC)
> Websockets
> 
> all this is to say, we use a lot of stuff.
>
> but gRPC might play really nicely. Reasons I’d be into it:
> better formality of data structures
> faster
> opens up an integration vector, particularly a cross-langauge one
