### ISSUE TITLE
cleanup: Rename lib methods containers away from "Requests"

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1235]
The objects that contain the interface of lib used to be "[something]Requests" like DatasetRequests. We renamed some, such as ProfileMethods (used to be ProfileRequests), but did not finish the job.

Take a look at the function `Receivers` in `lib/lib.go`. All of the objects constructed in there should be using a name that ends in "Methods". We should also rename the `CoreRequestsName` interface function to `CoreMethodsName`.

**Comment by b5** [comment]
Remaining Structs that need migration:

* [ ] `DatasetRequests`
* [ ] `PeerRequests`
* [ ] `LogRequests`

These are scheduled for deprecation, and shouldn't need migration:
* `ExportRequests`
* `RenderRequests`

**Comment by b5** [comment]
closed this a _little_ early. Still need to remove `ExportRequests` and `RenderRequests` by removing the commands themselves.
