### ISSUE TITLE
publish isn't advancing HEAD on qri cloud

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1251]
@chriswhong published a dataset, then published another update. I cloned the dataset, got an up-to-date logbook, but blocks from one version back

Reconstruction:

```
$ qri list
you have no datasets

b5 at b5-2 in ~/datasets/rm_me_5
$ qri add nyc-transit-data/turnstile_daily_counts_2020
🗼 fetched from registry
⠋
nyc-transit-data/turnstile_daily_counts_2020
/ipfs/QmaZJjtbSQVgeZSAamP4UpvVvDG7x7wHntAKSFbtxfssdU

Successfully added dataset nyc-transit-data/turnstile_daily_counts_2020

b5 at b5-2 in ~/datasets/rm_me_5
$ qri log nyc-transit-data/turnstile_daily_counts_2020 | cat
1   Commit:  /ipfs/QmZuSrGWPdrdt5KcZ4n7fSSmdpMm5C5pRq5QZEurdfYp59
    Date:    Fri Apr  3 11:20:41 EDT 2020
    Storage: remote
    Size:    3.4 MB

    update readme

2   Commit:  /ipfs/QmaZJjtbSQVgeZSAamP4UpvVvDG7x7wHntAKSFbtxfssdU
    Date:    Wed Apr  1 12:13:56 EDT 2020
    Storage: local
    Size:    3.4 MB

    fix typo in meta description
    meta:
    	updated description

3   Commit:  /ipfs/QmZiBjhne2H76oqJzHyUtTKF6TfeY9k6w7EYuYtqDbcCvu
    Date:    Tue Mar 31 16:50:19 EDT 2020
    Storage: remote
    Size:    3.4 MB

    add column descriptions

4   Commit:  /ipfs/QmeKsaSEdcP83R64PGZe47EYut4FHSoe3vBJht4zrq9En2
    Date:    Tue Mar 31 16:40:59 EDT 2020
    Storage: remote
    Size:    3.4 MB

    add meta and readme

5   Commit:  /ipfs/QmbjBD2i1kgKcufTKffGnzjU74wSRaEv3Vifqt8JENzr7L
    Date:    Tue Mar 31 16:38:08 EDT 2020
    Storage: remote
    Size:    3.4 MB

    created dataset
```

From the above output, the logbook that synced shows the first commit `Storage: remote`.

**Comment by Arqu** [comment]
I've tried to drill down on this one (and seems more like an issue in `qri-io/qri` how it handles `remote mode`. Drilling down got me to `refstore` and the `GetRef` function. While I don't have a complete grasp of the whole process so far, to mee it currently looks like the culprit might be how we "return a match" and how we "put refs"

Specifically, we go in order through the refList and return on the first match which should be ok as we always update the `Ref` if we have a match on the `PUT` request. However, what worries me is that we might not always have a good match and as such tend to `CREATE` a new `Ref` on a `PUT`. 

Think we might be able to "miss" a match if the `r.Name` and `b.Name` don't add up even if the `ProfileID` or `Peername` do match up.

Ie. We don't match on `Path`, we match on `ProfileID` or `Peername` but don't match on `Name` if it's empty or we "renamed" and it results in a `false Match()`, triggering the above flow.

Still need to figure out how to test this.

**Comment by Arqu** [comment]
Fixed on the cloud side.
