### ISSUE TITLE
qri stats --pretty does not format or change the output

### ISSUE THREAD

**Issue by Arqu** [qri-io/qri#1264]
`qri stats --pretty` generates the same output and format as `qri stats`.

**Comment by VarsMolta** [comment]
I'd like to work on this issue. What is the print format for `pretty` stats so I have a working test example?

**Comment by Arqu** [comment]
Absolutely!
Currently the format is like this sample:
`[{"count":4,"frequencies":{"29.86":3},"maxLength":21,"minLength":5,"type":"string","unique":1},{"count":2,"maxLength":17,"minLength":4,"type":"string","unique":2},{"count":1,"maxLength":21,"minLength":21,"type":"string","unique":1},{"count":1,"maxLength":24,"minLength":24,"type":"string","unique":1},{"count":199,"frequencies":{"":199},"maxLength":0,"minLength":0,"type":"string"},{"count":199,"frequencies":{"":199},"maxLength":0,"minLength":0,"type":"string"}]`

Ideally it should be something like:
```
[
 {
  "count": 4,
  "frequencies": {
   "29.86": 3
  },
  "maxLength": 21,
  "minLength": 5,
  "type": "string",
  "unique": 1
 },
 {
  "count": 2,
  "maxLength": 17,
  "minLength": 4,
  "type": "string",
  "unique": 2
 },
 {
  "count": 1,
  "maxLength": 21,
  "minLength": 21,
  "type": "string",
  "unique": 1
 },
 {
  "count": 1,
  "maxLength": 24,
  "minLength": 24,
  "type": "string",
  "unique": 1
 },
 {
  "count": 199,
  "frequencies": {
   "": 199
  },
  "maxLength": 0,
  "minLength": 0,
  "type": "string"
 },
 {
  "count": 199,
  "frequencies": {
   "": 199
  },
  "maxLength": 0,
  "minLength": 0,
  "type": "string"
 }
]
```

A good sample on how to do this can be seen here:
https://github.com/qri-io/qri/blob/master/cmd/dag.go#L129

**Comment by VarsMolta** [comment]
> Absolutely!
> Currently the format is like this sample:
> `[{"count":4,"frequencies":{"29.86":3},"maxLength":21,"minLength":5,"type":"string","unique":1},{"count":2,"maxLength":17,"minLength":4,"type":"string","unique":2},{"count":1,"maxLength":21,"minLength":21,"type":"string","unique":1},{"count":1,"maxLength":24,"minLength":24,"type":"string","unique":1},{"count":199,"frequencies":{"":199},"maxLength":0,"minLength":0,"type":"string"},{"count":199,"frequencies":{"":199},"maxLength":0,"minLength":0,"type":"string"}]`
> 
> Ideally it should be something like:
> 
> ```
> [
>  {
>   "count": 4,
>   "frequencies": {
>    "29.86": 3
>   },
>   "maxLength": 21,
>   "minLength": 5,
>   "type": "string",
>   "unique": 1
>  },
>  {
>   "count": 2,
>   "maxLength": 17,
>   "minLength": 4,
>   "type": "string",
>   "unique": 2
>  },
>  {
>   "count": 1,
>   "maxLength": 21,
>   "minLength": 21,
>   "type": "string",
>   "unique": 1
>  },
>  {
>   "count": 1,
>   "maxLength": 24,
>   "minLength": 24,
>   "type": "string",
>   "unique": 1
>  },
>  {
>   "count": 199,
>   "frequencies": {
>    "": 199
>   },
>   "maxLength": 0,
>   "minLength": 0,
>   "type": "string"
>  },
>  {
>   "count": 199,
>   "frequencies": {
>    "": 199
>   },
>   "maxLength": 0,
>   "minLength": 0,
>   "type": "string"
>  }
> ]
> ```
> 
> A good sample on how to do this can be seen here:
> https://github.com/qri-io/qri/blob/master/cmd/dag.go#L129

👍
