### ISSUE TITLE
qri remove hangs

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1271]
Recently upgraded to desktop 0.4.1 and CLI 0.9.7, I originally discovered this while trying to remove a dataset that was cloned the week prior, but then found that it's happening with all datasets.

To reproduce, run `qri add b5/world_bank_population`, it will be added successfully.  Then run `qri remove --all b5/world_bank_population`, it will hang.

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1272.
