### ISSUE TITLE
When saving, getting error "parsing ref, unexpected character at position 0: 'n'"

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1275]
Observed using CLI with command:
`qri save --log-all --file ~/Desktop/data-foo.csv nyc-transit-data/turnstile_daily_counts_2020 --title "update data for week ending 11 April 2020" `

Using `master` from a few moments before this issue was filed (`v0.9.8-dev`)

Also observed in Qri Desktop 0.4.1 (the same error is shown when trying to commit)

@dustmop suspects it is related to hyphens in the username

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1276.
