### ISSUE TITLE
desktop e2e-test backend won't launch 

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1285]
When trying to launch the backend in the e2e desktop tests, the backend errors and then closes. It seems the error is only when we try to pass in the env variables, as I'm able to launch just fine when opening the prod and dev versions of the app with the backend@master.

desktop code to launch backend:

https://github.com/qri-io/desktop/blob/dc285089dafa329979cd7c3c605cb491334f010b/test/utils/testQriBackend.ts#L47-L58

and `qriConfig` is declared in the same file.

We now get these messages in the logs:
stdout.log: `reading QRI_SETUP_CONFIG_DATA from env`
stderr.log: `config is nil, can't set IPFS path`

The error starts at commit e0202f4 that makes adjustments to `--setup`. I'm a little lost, let me know if there is a change that we need to make when trying to launch the e2e tests, or if this is a bug!

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1287.
