### ISSUE TITLE
Qri does not play nice with IPFS desktop

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1296]
Qri wants the repo lock. Which means anyone running Qri has to turn off any IPFS daemons (IPFS desktop is a UI wrapper around go-ipfs), and because we don't perfectly re-implement the IPFS API, things get weird for outside applications.

The short-term fix is to make qri behave as closely as possible to go-ipfs from an API perspective.

**Comment by momack2** [comment]
Ideally we clarify to IPFS Companion whether it can or can't use the qri IPFS deamon for loading IPFS websites (right now silently breaks instead of falling back to the gateway)
