### ISSUE TITLE
v0.10.0 tracking issue

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1309]
```
Usage:
  qri [command]

Dataset Commands:
  access      control visibility and permissions for datasets
  apply       execute scripts on datasets
  diff        compare differences between two data sources
  get         get components of qri datasets
  list        show a list of datasets
  log         show log of dataset commits
  delete      remove versions from dataset history
  rename      change the name of a dataset
  render      apply templates to datasets
  save        save changes to a dataset
  sql         experimental: apply an SQL query on local dataset(s)
  stats       calculate aggregated stats for a dataset
  storage     manage dataset storage on local and remote peers
  validate    show schema validation errors

Working Directory Commands:
  checkout    create a linked directory and write dataset files
  init        initialize a dataset directory
  restore     restore a checked out dataset's files to a previous state
  status      show what components of a dataset have been changed
  workdir     file system integration tools

Networking Commands:
  connect     connect to the distributed web by spinning up a Qri node
  drop        ask remotes to remove datasets
  peers       commands for working with peers
  push        set dataset publicity
  pull        fetch datasets from other peers
  registry    commands for working with a qri registry (qri.cloud)
  search      search the registry for datasets

Other Commands:
  completion  generate shell auto-completion scripts
  config      get and set local configuration information
  help        Help about any command
  setup       initialize qri and IPFS repositories, provision a new qri ID
  version     print the version number
```

### Highlights:
* **run any SQL**: paste in an SQL query. qri will find the datasets that I'm referencing, pull their latest versions, run the query, and return the result.
* **faster save**: save is now more than 2x faster than it was thanks to streaming validation & buzhash rolling hash calculation.
* **better feedback**: qri provides progress bars for save, push, pull, executed commands. Error messages are now descriptive.
* **push to remotes**: quickly set up a qri remote, allow friends to push, host data others are interested in
* **JSON API**:  qri's HTTP JSON API is well-documented. Qri CLI uses the JSON API instead of an RPC port.
* **introducing apply**: run all sorts of transformations on datasets.
* **robust configuration**: Qri can be configured to suit. Disable color, turn off p2p, turn off FSI integrations. Configurations can be copy-pasted because private keys are no longer stored in configuration.

-- --

### qri v0.11.0
* SQL transforms
* stale transform checking: `qri status` tells me I need to re-run a transform.
* remote hooks
* retention strategies

### v0.12.0+:
* access control
* encryption at rest

**Comment by dustmop** [comment]
Discussed today in the spring meeting, we're going to remove the following commands, which are mostly being combined into other commands or Desktop / cloud:

```
export
render
update
```

We also need to add:
```
storage
```

I would also suggest the following description change for `remove`:
```
remove - Remove dataset versions
```

Since:
1) We want to  have the option to remove from remotes as well as local repositories
2) We can remove only a certain number of versions instead of the entire dataset
3) Talking about versions differentiates it from `storage`

**Comment by b5** [comment]
superseded by  #1731
