### ISSUE TITLE
Merge `fetch` command into `log`

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1310]
currently fetch serves one purpose: getting logbook data without saving it. We can make the log command do that, and drop the need for the command entirely.

what used to be:
```
$ qri fetch b5/world_bank_population
```

now becomes:
```
$ qri log b5/world_bank_population
```
If I don't have the reference, it'll be fetched.

**Comment by ramfox** [comment]
Should this extend to the API? merging `/history` and `/fetch`?

**Comment by ramfox** [comment]
proposed example usage:
```
  # Show log for the local dataset b5/precip:
  $ qri log b5/precip

  #  Show log for a dataset on the Qri Cloud registry called ramfox/league_stats
  $ qri log ramfox/league_stats
	
  #  Show log for a dataset chriswhong/nyc_parking_tickets on a remote named "nycdatacollection"
  $ qri log chriswhong/nyc_parking_tickets --remote nycdatacollection
```

**Comment by b5** [comment]
Yep. All look good to me
