### ISSUE TITLE
Moving Qri's IPFS repo into the .qri folder

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1319]
Background for why we're doing this: https://github.com/qri-io/qri/issues/1225

### Migrating Qri's configuration
We should time these changes with our overhaul of qri's configuration, updating the config RFC to talk about removing support for `IPFS_PATH`. Instead the ipfs repo path should be part of the new filesystem configuration, specific to the local IPFS `qfs.Filestore`. Doing it this way both removes configuration ambiguity, and allows users to get the old behavior back by specifying `~/.ipfs` as the repo path.

To make this transition as clean as possible, I think we should use a completely new IPFS config, with a new keypair. This'll mean users running on the libp2p network won't appear as the same peer. Yet another reason I'm thankful we connected user data to a separate keypair held by Qri.

### Moving Qri data from one IPFS repo to another
We're going to need a tool for detangling the hashes in an IPFS repo that Qri relies on, both to _move_ those hashes to another repo, and to unpin those hashes from the original repo.

### Using non-default ports for IPFS configuration
The other part of privatizing our IPFS instance is to move off of the default port configurations for our IPFS node.

We can leverage this move to a private configuration to set ports to non-standard ones. One option is to use `0` for port numbers, which defaults to an open port.

### Steps to complete:
_note: need to finish this list_

* [x] ratify the latest config RFC:  https://github.com/qri-io/rfcs/pull/51.
* [ ] write an IPFS repo migration tool for moving data between repositories
* [ ] write an IPFS-repo-move function:
  * create a new IPFS repo at `.qri/ipfs`, new keypair and all
  * edit port configuration to use nonstandard ports
  * run the IPFS repo migration, moving over any Qri hashes to the new repo
* [ ] write a qri config migration that also triggers the move 
* [ ] remove support for `IPFS_PATH` env var
* [ ] add documentation that for users that want to customize IPFS behavior: they need to edit the config within `.qri/ipfs`.

**Comment by dustmop** [comment]
> We're going to need a tool for detangling the hashes in an IPFS repo that Qri relies on, both to move those hashes to another repo, and to unpin those hashes from the original repo.

My vote for this is to keep the implementation simple. Copy *everything* from the old `~/.ipfs` to `~/.qri/ipfs` and hope that we get `qri storage clean` implemented soon. The only case where this causes problems is a user who has stored a ton in IPFS already then starts using qri before the migration happens, and the only negative consequence is that they temporarily lose some disk space. I would bet implementing a smarter alternative would take more work than implementing `qri storage clean`.

**Comment by b5** [comment]
_very_ into that idea. Sounds far less error prone

**Comment by Arqu** [comment]
My only concern here is while we are going to heavily test the migration suite, issues can still occur. One thing I'd definitely want in this is a rollback mechanism and maybe dual compatibility for a while until we get over the hump with some sort of sunset period.

Currently a curse and a blessing that we don't have too many heavy users to make such a large change.

**Comment by ramfox** [comment]
curious why you believe creating a new repo is the best move, rather than copying/moving the original ipfs repo from the IPFS_PATH to the new standard location.
Does this have anything to do with having to upgrade/make changes to the repo anyway?

**Comment by feep** [comment]
I like keeping `.qri`’s stuff together.

I am not sure what is in `~/.ipfs` from reading filenames, it looks like configuration and one or both of cache & user data.

That’s a complicated case, but there are official places for those bits.

I put more about this in #1319.

It’s complicated, but now is probably the best time to consider it.
