### ISSUE TITLE
datasets saved in ipfs have inconsistent name and peername fields

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1330]
Found this hairy issue while digging into the save path.

We do a lot of assigning of the Name and Peername fields on Dataset while both reading and writing to/from IPFS. There's lots of hard-to-follow code paths and random workarounds all around the codebase, so and I wasn't sure what was actually ending up in IPFS.

I tried these steps:

```
> qri save --body something.csv me/make_one
dustmop/make_one@/ipfs/QmNpkL7ZNoqSEdRNPTKXUWntksaVSWThqALoYT7EUNzSow

> ipfs cat /ipfs/QmNpkL7ZNoqSEdRNPTKXUWntksaVSWThqALoYT7EUNzSow/dataset.json | jq '.peername'
"dustmop"

> cat ds.yaml
name: make_two
meta:
  qri: md:0
  title: example data
bodypath: something.csv

> qri save --file ds.yaml
dataset saved: dustmop/make_two@/ipfs/QmeZQLKs9L9kFzV4mMyqDpQduy1Hv784nqb5vVbLjbbMz6

> ipfs cat /ipfs/QmeZQLKs9L9kFzV4mMyqDpQduy1Hv784nqb5vVbLjbbMz6/dataset.json | jq '.peername'
"me"
```

So it looks like what is actually in the Peername field depends on how the dataset was saved. In both cases the Name field is blank.

What is the expected / correct behavior here?

In my assessment, we should require and enforce that both Peername and Name are *blank* in IPFS, since those strings aren't really immutable and are only suitable outside of a cafs. When we read the dataset we fill in those fields anyway using the user provided ref, so there's no difference in behavior from the outside. Basically Name and Peername would become transient fields that are treated specially by dsfs.

Does this approach make sense? It will remove some magic behavior from our code, and makes us more robust under renames. However, if we ever support something like looking up a dataset by initID without a ref, is it okay that those fields will be blank? Should they be the last value they were saved with? Because we currently aren't doing that either, as the Name field is blanked out.

The test `TestSaveThenOverrideMetaComponent` in cmd/cmd_test contains a test that verifies the Peername in IPFS is "me".

The function `SaveDataset` in base/save.go contains a work-around that sets a blank peername to "me" and is directly related to this issue.

**Comment by b5** [comment]
> In my assessment, we should require and enforce that both Peername and Name are blank in IPFS

this, absolutely. both peername and name fields should always be blank at the persistence layer. I'm dismayed to hear this is not the case, and haven't looked at that field in a while.

**Comment by dustmop** [comment]
Okay, great, glad to hear we're on the same page. I'll fix this, and at the very least, the tests at the cmd level will ensure the data in ipfs is correct.

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1331.
