### ISSUE TITLE
refactor(lib): `lib.NewInstance` should build an instance using `muxfs.New`

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1337]
Currently we build an instance by using the `repo/buildrepo` subpackage to add a `cafs.Store` and a `Mux` file system to the qri instance (to the `inst.store` & `inst.qfs` fields, respectfully).

We first build the `store`, using `buildrepo.NewCAFSStore` (which can either be a `ipfs`, `ipfs_http`, or `map` store), and then pass that `store` to the `buildrepo.NewFilesystem`. That store becomes the "cafs" filestore and the "ipfs" filestore.

We are refactoring `qfs` to instead build its own configurable multiplex filesystem, rather than using the `buildrepo` package. Issue details are here: https://github.com/qri-io/qfs/issues/26

So, rather than using `buildrepo.NewCAFSStore` and `buildrepo.NewFilesystem`, we should be using `muxfs.New` to create a `Mux` filesystem, based on passed in configuration. If there is no filesystem configuration, `lib.NewInstance` should use a `muxfs` option function that attempts to build a `Type="ipfs"` filesystem using `${QRI_PATH}/.ipfs`.

Then, `lib.NewInstance` should use the `muxfs.IPFSFilesystem()` function to get access to the created `qipfs.Filesystem`, cast it as a `cafs.Filestore`, and add it to the `inst.store` field.

Basically, we are reversing the course of action that currently occurs: now we build a store and use it to create a filesystem. Instead, we are going to create the filesystem and pull the store out of that.

One thing to note:
`muxfs` is changing the expectations of what we get by default in a mux filesystem. "cafs" used to be a field that housed a reference to a `qipfs.Filesystem`, and this same `ipfs` instance was also referred to in the `muxfs` by the field "ipfs". We are dropping the "cafs" field. This should be mitigated by the fact that we never explicitly call for a specific filesystem when we use a `qfs`, and instead rely on the given path to determine which filesystem we are trying to access.

However, this may affect when we set up instances for testing! A "cafs" fields on a muxfs should not longer exists.

**Comment by b5** [comment]
@ramfox, I've put some work into this with #1393, and while `lib.NewInstance` doesn't directly use `muxfs.New`, muxfs is only used in one place in production: `buildrepo.New`. buildrepo.New still exists b/c `lib.NewInstance` kinda needs a repo before it can do anything, which means the repo interface still ultimately owns the muxfs pointer. I'd argue this is the correct way to handle things while repo still exists.

The next step to move past this will require removing the `repo` interface entirely, which will take a while. What do you think of closing this when #1393 lands?

**Comment by ramfox** [comment]
Sounds good! 🙌

**Comment by b5** [comment]
ok great. Since #1393 is merged, I'm going to close this.
