### ISSUE TITLE
dscache needs to know about changes to fsi

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1344]
Dscache stores the FSIPath, which can be changed by `checkout` and `init` commands. FSI should notify dscache when this happens.

**Comment by b5** [comment]
We've talked about formalizing this into a _hooks_ pattern (as opposed to _events_). Fully supported

**Comment by dustmop** [comment]
We need to do some refactoring with the repo and instance. The logbook and dscache both exist on the repo, *and* the instance, while the FSI struct exists only on the instance.

Dscache needs to be told about changes from FSI, so the constructor needs both logbook and FSI, which means it can't live on the repo. All of these should be moved up to the Instance, and users will need to stop relying on the repo having them.

**Comment by dustmop** [comment]
Implemented by https://github.com/qri-io/qri/pull/1349.
