### ISSUE TITLE
Install from source fails on ARMv7 - constant overflows int 

### ISSUE THREAD

**Issue by rustprooflabs** [qri-io/qri#1350]
I am getting an error trying to install from source on a Raspberry Pi 4 (ARMv7 rev3), Go version 1.14.3.  I  get the error:

```
# github.com/cube2222/octosql/execution/functions
../../go/pkg/mod/github.com/cube2222/octosql@v0.2.1-0.20200319150444-e5a71fa20dbe/execution/functions/functions.go:368:8: constant 9223372036854775807 overflows int
../../go/pkg/mod/github.com/cube2222/octosql@v0.2.1-0.20200319150444-e5a71fa20dbe/execution/functions/functions.go:404:8: constant -9223372036854775808 overflows int
```

This seems related to https://github.com/qri-io/qri/issues/659 though this appears to be in an external dependency (octosql). If this is a bug there (and not within Qri itself) is it possible to install Qri without this dependency as a workaround?

**Comment by b5** [comment]
ouch, this has cropped up before: #659. Thanks for pointing this out!

Sadly this error looks like it's coming from an upstream package (octosql), we'll have to submit a PR there

**Comment by rustprooflabs** [comment]
I had a feeling that was the answer.  Let me know if I can help with the upstream PR or testing.  I'm new to both packages but will do what I can!

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1580. Now sql is disabled for arm builds, which hopefully isn't too inconvenient (better than not building at all).
