### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by feep** [qri-io/qri#1362]
It’s time.

[Angular’s](https://github.com/angular/angular/tree/master/.github/ISSUE_TEMPLATE) are very well done. But I’ll look around for something `go` so I won’t need to do so much rewriting.

I have some questions below. Vote with reactions.

**Comment by feep** [comment]
Emoji in name. As far as I can tell, this only shows up in (`choose`)[https://github.com/angular/angular/issues/new/choose].

**Comment by feep** [comment]
[Emoji in comments](https://github.com/angular/angular/issues/new?template=1-bug-report.md). Won’t show up in issue page.

**Comment by feep** [comment]
[Emoji in issue](https://github.com/angular/angular/issues/37214). Headers, perhaps.

**Comment by feep** [comment]
### Commands to show current os & version

```
# macOS
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020

# linux
❯ lsb_release -a
# untested

# windows
c:\> systeminfo
# untested
# only need the first 4 or so lines if anybody knows how to pipe that into the equivalent of `head`

```

**Comment by feep** [comment]
## Proposed Types

- Bug
- Feature
- Docs?
- Website?
- Cloud?
- Support/question
- Security

- Other repos that get misfiled 
Other repos could be combined in one template.

Templates show up in [`choose`](https://github.com/angular/angular/issues/new/choose), and as a header on [`issue/new`](https://github.com/angular/angular/issues/new?template=2-feature-request.md).

## Possible types

🐞Bug report
Report a bug in the Angular Framework

🚀Feature request
Suggest a feature for Angular Framework

📚 Docs or angular.io issue report
Report an issue in Angular's documentation or angular.io application

❓Support request
Questions and requests for support

### _Love_ the headfake on this one

```
      🛑      🛑      🛑 

Please do not file questions or support requests on our issue tracker.

TODO(feep) Blah blah, discord link.

Qri team thanks you.
And we look forward to chatting!

      🛑      🛑      🛑 
```

### Same headfake

⚠️ Security issue disclosure
Report a security issue in Angular Framework, Material, or CLI

### Don’t want to overwhelm, but heavily misfiled issues can have a pointer to their repo.

⭐ Starlark
Blah blah something.

🛠️Angular CLI
Issues and feature requests for Angular CLI

💎Angular Components
Issues and feature requests for Angular Components

**Comment by b5** [comment]
I'm a fan of starting simple, with three categories:
* bug report - have the template match almost exactly the way @hbruch files issues, with a template that includes sections for qri version & platform, expected behaviour, actual behaviour.
* feature request - happy to copy angular here
* support request - ask users to join discord & ask there, _not_ file an issue

We could add a fourth:
* security - link to security disclosures docs page (which doesn't exist yet, we'll need to make one)

I'm ok to wait until we have a security disclosures page up, then adding this section in a follow up.

**Comment by feep** [comment]
@b5, adding issue for security disclosure page.

Do you want the security disclosure page as a `.md` file in `/qri` repo, or as a page on the website?
