### ISSUE TITLE
Migrating IPFS and config

### ISSUE THREAD

**Issue by Arqu** [qri-io/qri#1376]
This is a tracker issue for the migration branch https://github.com/qri-io/qri/tree/migration-rev2.

The target is to merge the branch once all migration PRs are landed.

Config PRs:
- [x] https://github.com/qri-io/qri/pull/1364
- [x] https://github.com/qri-io/qri/pull/1370
- [x] https://github.com/qri-io/qri/pull/1373

IPFS/QFS PRs:
- [x] https://github.com/qri-io/qri/pull/1389
- [x] https://github.com/qri-io/qri/pull/1332
- [x] https://github.com/qri-io/qri/pull/1360
- [x] https://github.com/qri-io/qri/issues/1375
- [x] https://github.com/qri-io/qri/pull/1387

Related Issues:
- https://github.com/qri-io/qri/issues/1345
- https://github.com/qri-io/qri/issues/1346
- https://github.com/qri-io/qri/issues/1337
- https://github.com/qri-io/qri/issues/1319

Related RFCs:
- https://github.com/qri-io/rfcs/blob/master/text/0029-config_revision.md#remove-stale-configuration-fields

- [x] PR & Merge the `migration-rev2` branch into `master`

**Comment by b5** [comment]
We need two more things aside from extensive testing:
* upgrade to go-ipfs v0.6.0 https://github.com/qri-io/qri/issues/1400
* close https://github.com/qri-io/qri/issues/1399

Both of those are covered in other issues, so I'm going to close this one
