### ISSUE TITLE
fill.Struct should make it easier to ignore removed fields

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1378]
For the config migration, there's a number of fields being removed from the field struct. This causes a user's config pre-migration configuration to be unserializable using `fill.Struct`. The solution put in place was to use `SetArbitrary` to ignore these errors, see https://github.com/qri-io/qri/pull/1370#issuecomment-635513515 and follow-up comments.

This works but is a bit heavy handed, as it will error all unknown fields, including simple misspellings. A better option would be explicitly declare which fields were being removed, so that only those would be ignored by fill.Struct.

It's also a bit inconvenient for the config migration, as the struct has multiple sub-components, which means `SetArbitrary` needs to be defined for each sub-struct. It would be much more convenient to be able to list all of the full paths at the top-level.

Packages like `cmp.Diff` solve this by having optional parameters that specify which fields to ignore. However, `fill.Struct` prefers to work purely using the definition of the struct, so that the call sites remain free of the need to specify flags. For example, setting arbitrary field names in a map on the struct works by looking to see if the structure implements the `ArbitrarySetter` interface.

In that vein, we could define another interface, say `PathRemovals` that works like this:

```
type Config struct {
  ...
}

func (c *Config) RemovedPaths() string {
  return []string{"api.remotemode", "api.urlroot", ...}
}
```

This only needs to be declared for the top-level struct, the one that is passed into `fill.Struct`, and the paths will be passed down recursively to each sub-struct, ignoring errors for any matches.

Not committed to the interface or method name.

**Comment by dustmop** [comment]
Or maybe:

```
type PathIgnorer interface {
  IgnorePaths() []string
}
```

**Comment by Arqu** [comment]
This should now be addressed in the latest commit in https://github.com/qri-io/qri/pull/1373
