### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by feep** [qri-io/qri#1390]
We need a security policy for github.

It shows up in the black linkbar at the top, and in the “👋 looks like your first issue” box on issues.

Once we have one, I can link to it from issue templates and `config.yml`.

### Prior art

- [Angular](https://angular.io/guide/security#report-issues)
- go
  - [github](https://github.com/golang/go/security/policy)
  - [web](https://golang.org/security)

**Comment by feep** [comment]
@rgardaphe, can you set up a security [at] qri.io email address?

For now, it should probably just forward to hello [at] qri.io.

**Comment by feep** [comment]
@b5, this is really quick and dirty. Just a comment and an email address?

Probably easier to write it in the [web ui](https://github.com/qri-io/qri/new/master) than it is to comment.

Have a look at [go’s](https://github.com/golang/go/security/policy).

**Comment by b5** [comment]
Sure, can we use this?

```
# Security Policy

For security vulnerabilities, please send an email to security@qri.io, please **do not** file an issue for security related issues.

```

**Comment by feep** [comment]
Closed by qri-io/.github#3.
