### ISSUE TITLE
Simplify issue templates

### ISSUE THREAD

**Issue by feep** [qri-io/qri#1394]
Asmir filed an issue, the template was a little confusing.

Going to try switching from descriptive headers to questions.

That will eliminate most of the confusing and cluttery html comments.

More like this.

### What did you expect to happen?

I expected to file an issue without being confused.

### What actually happened?

All the html comments got in the way. I couldn’t figure out what to delete and what to fill out.

### Do you have a suggested fix?

Maybe it would help if the headers were questions?

**Comment by b5** [comment]
I'm into the question format
