### ISSUE TITLE
bug(ipfs config): creating a new qri repo creates an ipfs repo with incorrect ports in its `Addresses` config

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1412]
### What version of qri are you using (`qri version`)?
head/0.9.9-dev

### What is your OS and version?

mac 10.15.5

### What did you do?

create a new qri repo using `qri setup`

### What happened?

Qri created a new qri repo, and embedded ifps repo. This embedded ipfs repo had all the standard ports in its addresses. 

```
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
```

However, if you migrate from an older repo, we change those ports 0, so that the addresses will instead use any open port.

### What did you expect to happen?

I expected the ipfs repo's config to have addresses with port 0:

```
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/0",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/0",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/0",
      "/ip6/::/tcp/0",
      "/ip4/0.0.0.0/udp/0/quic",
      "/ip6/::/udp/0/quic"
    ]
  },
```

**Comment by b5** [comment]
closed by a `qfs` fix merged into qri in #1421
