### ISSUE TITLE
bug(fetch logs): "unrecognized push address string: registry" when trying to get logs from registry

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1419]
## What version of qri are you using (`qri version`)?

head / 0.9.9

### What is your OS and version?

mac 10.15.5

### What did you do?

1) running `temp_registry_server`, get the name of the dataset on the reg server, in my case : "pink_lace_xoloitzcuintli/synths"
2) In another terminal: `qri config set registry.location http://localhost:2500`, then run `qri connect`
3) In third terminal, curl qri to get the logs of that dataset:
```
$ curl -X GET "http://localhost:2503/history/pink_lace_xoloitzcuintli/synths?pull=true"
{
  "meta": {
    "code": 500,
    "error": "unrecognized push address string: registry"
  }
}
```

### What happened?

Got error: `unrecognized push address string: registry`

### What did you expect to happen?

Expected to get the logs of the dataset

### Do you have a suggested fix?
in `qri/registry/regclient/client.go`, line 61
Instead of `regClient.ResolveRef` returning the resolver address (aka the registry address), we are just returning "registry", believe we should be returning `cfg.Location` instead

**Comment by b5** [comment]
I'd also add that `"unrecognized push address string: registry"` is confusing given you aren't pushing anything. It'd be great to have that be "unrecognized _remote_ address string:"
