### ISSUE TITLE
feat(p2p): `ResolveRef` over p2p

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1456]
We know we want to add `ResolveRef` to p2p at some point. Wanted to create an issue to take notes & plan. To resolve refs over p2p we need both the `ResolveRef` and `resolveRefHandler` in place & we need to add a local-only resolver to the `QriNode`.

### local only resolver

`QriNode` - need to add a `resolver` field, with the comments specifying the structure expects a local-only resolver.

`p2p.NewQriNode` - should accept a `resolver` & add it to the `QriNode` it creates

The `lib` package is the arbiter of resolving. When we create a `QriNode` using `p2p.NewQriNode` in `lib.NewInstance`, we need to pass it a local-only resolver.

### `p2p.ResolveRef`

`ResolveRef` should send a batch of `ResolveRefRequest` messages, whose body is the unresolved dsref.Ref) to a set amount of peers & wait for replies. (another option would be for the request body to just include a ref string).

Questions arise when we want to determine who to send these peers to, how many we want to send to, and how long we are willing to wait. 

Who -> should we search our peerlist & prioritize a peer that has the matching dsref.Username? How do we determine the other peers we want to request resolution from, and how do we get it to _not_ be the same peers every time we make a request. Or, is there some determination to say "this peer is reliable, always ask this peer for info".
How many -> is this an arbitrary number we choose and then finetune? How many network requests are we okay with flooding the network? This is less important now when our network is sparse, but can be a problem later on.
How long -> libp2p has a default 60 sec timeout to `DialPeer`, https://godoc.org/github.com/libp2p/go-libp2p-core/network#pkg-constants in its docs. Multiple libp2p issues reference a 10s TCP handshake timeout. This can be configured by the user if they would like, but as a default, are we okay with a resolution that takes 60 seconds?

###
`handleResolveRef` - needs to accept a resolve ref request, attempt to resolve locally, and either return a message (containing either the resolved or unresolved dsRef) (or possibly nil for unresolved?)

The big question here is whether `handleResolveRef`, if it does not have the resolved dsref itself, should then attempt its own request to _its_ peers to resolve the ref. Or does it's responsibility end when it either succeeds or fails at resolving the ref itself.

### alternate implementations

Should ref resolution be its own protocol?
`/qri/0.0.1/resolveref/0.0.1`, with a dsref protobuffer message

Should we be refactoring the qri protocol first, and using a handler w/ a match func to pass the request to the correct sub-handler (in this case `handleResolveRef`)

**Comment by b5** [comment]
closed by #1493!
