### ISSUE TITLE
Adding metadata via the app breaks stuff

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#148]
Adding metadata via the app makes the 
`error unmarshaling names: json: cannot unmarshal array into Go value of type map[string]datastore.Key`
Error happen when you try to use any command line tools

Adding metadata when you do 
`qri add -f <file> -n <name> -m <metadata>`
works fine and doesn't break anything

**Comment by b5** [comment]
This issue is, like, mad old. Marking closed. Let's make a new one if stuff is still F'd
