### ISSUE TITLE
API /get should support component=body&format=csv

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1504]
right now getting a CSV from the API requires `/body/{username}/{dataset}`, we should make the same thing possible with `/get/{username}/{dataset}?component=body&format=csv`.

we should aim to deprecate & remove the `/body/` endpoint in favor of this approach. It's similar to the  "get vs. export" debate we had a while back. There should be ONE way to "get" stuff: the `/get` endpoint

cc @chriswhong

**Comment by dustmop** [comment]
Big fan of this idea.

**Comment by b5** [comment]
@hbruch brought up an important point on [discord](https://discordapp.com/channels/497052800778502152/497052802275737611/752631582241587270): there are external systems that rely on file extensions in URLS to determine it's a CSV file. His use case is with [kepler.gl](https://kepler.gl), where they state directly in their docs: [URL has to end in .csv](https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map.md#load-map-using-url)

If our API supported `/get/{user}/{dataset}/body.csv`, and that served CSV data, kepler.gl would be able to use Qri data. From an implementation standpoint, it's just a little extra parsing logic, so I think we should support it in the general form, allowing either `json` and `csv` file extensions: `/get/{user}/{dataset}/body.{format}`

**Comment by b5** [comment]
closed by #1510
