### ISSUE TITLE
bug(CLI): save doesn't register changes until after status is run

### ISSUE THREAD

**Issue by uhLeeshUh** [qri-io/qri#1525]
### What did you do?
Tried to save a change made to a dataset 

### What happened?
CLI didn't register any staged changes so wasn't able to save

Feedback from user Paul Crickard in Sprint R: “If I edited a file and tried to run save, it said everything up to date. But when I did status and then save, it caught the changes.”

**Comment by Arqu** [comment]
Another instance of https://github.com/qri-io/qri/issues/1383

**Comment by uhLeeshUh** [comment]
Great thanks for the catch @Arqu
