### ISSUE TITLE
Integration page URLs don't download all rows

### ISSUE THREAD

**Issue by hbruch** [qri-io/qri#1545]
### What did you do?
I tried to download `https://api.qri.cloud/get/mfdz/stuttgart_gelbekarten/body.csv?all` as noted on the integrations page.

### What happened?
First call resulted in 
```
"meta": {
    "code": 500,
    "error": "context canceled"
  }
}"
```

Following calls return the first 100 records of the dataset. 

### What did you expect to happen?
As there is an (though empty) url param "all" appended, I'd expect all rows to be returned. Instead, I needed to specify https://api.qri.cloud/get/mfdz/stuttgart_gelbekarten/body.csv?all=true (with appended =true).

### Do you have a suggested fix?
I'd append `=true` to all links on the integration page.

**Comment by dustmop** [comment]
This has been fixed on cloud.
