### ISSUE TITLE
discuss 'save' vs 'update' functionality in cli and client wrappers

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#159]
things to consider
 - git commit, branch, fork analogy vs load, save, update functionality in a traditional data workflow

in python it would be natural to 
- load a dataset
- make some changes
- have the option to update that existing dataset (same name, title, description but updated underlying structure)
- have the option to 'save as' with a new name and possibly same title, description, and updated underlying structure

example flow:
```python
import qri

ds = qri.load_ds("airports")
# make some change
ds.data.rename(columns={'old_col_name': 'new_col_name'}, inplace=True)

# update existing dataset
ds.update(msg="renamed `old_col_name` to `new_col_name`")

# make some other change
ds.data["new_col"] = ds.data.apply(lambda row: some_func(row), axis=1)

# save as new table
qri.save_ds(ds, name="new_name", meta)
```

**Comment by b5** [comment]
closing to to age, we'll pick this up when we update the python client
