### ISSUE TITLE
Move preview creation to new package in dataset repo

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1612]
The apply command is getting an “early-return & listen for events” execution. For this to work properly the startf package needs to be able to emit a `“transform:Dataset”` event that includes a dataset preview. That is: a size-bounded sample of the dataset. 

Dataset preview generation needs more specificity, and we're not finished defining what a "preview" is quite yet (for example: do we truncate fields in the `meta` component?). I'd like to move it down into dataset where we can work on the definition of a preview, and make the results of that work as easy to import as possible

We need  Move the core logic of generating a preview from an open dataset into a `preview` package in `github.com/qri-io/dataset`,  extracting preview creation from [where it currently lives in `base`](https://github.com/qri-io/qri/blob/346c47bc52d5ec4080d20ad48f481d46331e7e9b/base/preview.go#L31). 

We'll also need to copy the `ConvertBodyFile` function into this new package. Let's bring it over and leave it exported.

**Comment by ramfox** [comment]
@b5 

> We'll also need to copy the ConvertBodyFile function into this new package. Let's bring it over and leave it exported.

Is this saying: "make a copy of `ConvertBodyFile` in the new `preview` package, export it & adjust any imports in qri to pull from the new `preview` package"

Or, "make a copy of `ConvertBodyFile` in `preview`, but leave it as is in qri"?

**Comment by b5** [comment]
we worked this out over on qri-io/dataset#284
