### ISSUE TITLE
dispatch should be able to call http rpc using GET in addition to POST

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1658]
```
TODO from dispatch PR: https://github.com/qri-io/qri/pull/1653/files
// TODO(dustmop): This is always using the "POST" verb currently. We need some
// mechanism of tagging methods as being read-only and "GET"-able. Once that
// exists, use it here to lookup the verb that should be used to invoke the rpc.
```

The dispatch function always calls http endpoints using POST. We should add a function to MethodSets called `Mapping`, which includes information about whether methods can be called using GET instead of POST.

**Comment by ramfox** [comment]
Closing this issue, b/c we have since decided that the rpc will only operate via POST using json.
