### ISSUE TITLE
Questions around `/push` endpoints

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1744]
Right now, we have `/push` do 3 things depending on the http method

1) GET - returns a list of your datasets on the given remote as `[]VersionInfo`
2) POST - expected behavior, pushes a dataset to a remote
3) DELETE - removes a dataset from a remote
Seems like we need to add a few more endpoints to our spec to cover cases 1 & 3 or at least make sure they are covered under other endpoints.

Should we add `/remote/list` and `/remote/remove`, or should these be folded into `/list` and `/ds/remove`?

**Comment by dustmop** [comment]
Personally I like adding both `/remote/list` and `/remote/remove`.

**Comment by b5** [comment]
Yeah I agree with @dustmop, and think we should add `/remote/list` for listing your datasets on a remote, and `/remote/remove`.

Folding the remove functionality into `/ds/remove` is tempting, but I'm a fan of how the `/remote`-prefixed endpoints all talk to the remote subsystem.

**Comment by ramfox** [comment]
:chefs kiss:

**Comment by ramfox** [comment]
As per our in person (zoom) discussion:
Turns out the functionality of #1, getting a list of datasets from a remote is NOT what that method was doing. It instead was filtering our own datasets & returning the ones marked 'Public'. Since this is not was is expected of a `/remote/list` endpoint, we are tabling that endpoint for now until we can implement properly.
