### ISSUE TITLE
Question about `/render` endpoints

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1745]
We have two lib methods for rendering: `RenderReadme` and `RenderViz`

The api handler checks the params for a `Viz` field, if true it calls `RenderViz`, other wise it's assumed we are talking about `RenderReadme`

These are both off the same `/render` endpoint. 

One one hand, this doesn't necessarily violate our pattern of each endpoint returning one type of thing, because both return bytes of rendered html. But, we are technically returning something different depending on the input (a rendered `Readme` vs a rendered `Viz`), which does violate our 0.10.0 spec expectations.

Possible solutions, depending on if we feel this violates our principles:
- adding a `/render/viz` endpoint, and using `/render` for readme
- having both `/render/readme` & `/render/viz` & removing `render`
- use the `RenderParams` as they are now, but replace the `Viz` flag with the `Component` field of the `Ref`, if it says "viz", return a rendered viz, if it says "readme" or is empty, return a rendered readme

**Comment by b5** [comment]
I’m a fan of option 3 (add a param field). Field should be called `Selector` and should error if not one of viz, readme

**Comment by Arqu** [comment]
Agree with b5 here
