### ISSUE TITLE
Consider adding a default source resolver to the Attributes of lib methods

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1752]
Since I've been moving Source away from InputParams and over to scope, I've run into a lot of cases where certain commands only work if they're using a particular source.

For example:

* `pull` has to use `network` since by definition the ref is on another node
* `remove`, `rename`, `validate` all have to use `local`
* `push` has to use `local`, since it is something that starts on your own machine that goes to another

As of https://github.com/qri-io/qri/pull/1751 callers are required to always use `WithSource` to call these methods, and return an error if that isn't done. Instead, we can add a field to the Attributes map which will set a default source if the value is a non-empty string.

**Comment by ramfox** [comment]
would appreciate something like this .Even if it's just a dev life improvement, I found myself searching through the code while reviewing #1754 to make sure I correctly understood default behavior (was trying to figure out if we would run into any problems if a source wasn't set for a particular lib method)

**Comment by dustmop** [comment]
Totally, agreed that the current version is hard to read and keep straight in one's head. Thinking about it from the perspective of someone using `qri` as a library, they shouldn't be forced to set their own reasonable default values when we can do that instead.

**Comment by b5** [comment]
Yep I'm all for it. I think it'll also make changing default behavior easier to do and review

**Comment by Arqu** [comment]
+1 tests need sane defaults

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1764 and https://github.com/qri-io/qri/pull/1765
