### ISSUE TITLE
consider moving qri-io/didmod to this repo

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1779]
https://github.com/qri-io/didmod is only used by qri core, and its purpose is rather specific: to fulfill the needs of the stats package. It also needs to do Windows specific operations that match pretty closely to the hiddenfile and watchfs packages that already live in qri core. Move this package info `fsi/didmod` seems like it would be a good idea, both to consolidate this code, and to make releases and future maintenance easier.

**Comment by b5** [comment]
given we're moving away from FSI entirely we won't need this package. closing
