### ISSUE TITLE
feat(automation): expand orchestrator methods

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1794]
We need to add methods to the orchestrator so that other systems can use it to manipulate the `workflow.Store`. The `Orchestrator` understands what `trigger.Listeners` and `hook.Completors` we have access to. We can use this knowledge to convert []map[string]interface{} fields into specific triggers and hooks of the specified opt["type"]. If there is no "type" field, then the `CreateWorkflow` and `UpdateWorkflow` functions will error.

The other functions are more or less pass throughs of `o.workflows` functions.

```go
func (o *Orchestrator) UpdateWorkflow(wid workflow.ID, triggersOpts []map[string]interface{}, hookOpts []map[string]interface{}) (*workflow.State, error)
func (o *Orchestrator) GetWorkflow(wid workflow.ID) (*workflow.State, error)
func (o *Orchestrator) RemoveWorkflow(wid workflow.ID) error
func (o *Orchestrator) DeployWorkflow(wid workflow.ID) error
func (o *Orchestrator) UndeployWorkflow(wid workflow.ID) error
func (o *Orchestrator) ListWorkflows() ([]*workflow.State, error)
func (o *Orchestrator) ListDeployedWorkflow() ([]*workflow.State, error)
```

Tests
```go
// automation_test.go
func TestWorkflowIntegration(t *testing.T) error {
    // create orchestrator with a test listener and test completor
    // create trigger options
    // create hook options
    // CreateWorkflow
    // GetWorkflow
    // ensure correct trigger and hooks
    // CreateWorkflow
    // ListWorkflow
    // UpdateWorkflow
    // GetWorkflow
    // DeployWorkflow
    // ListDeployed // one
    // UndeployWorkflow
    // ListDeployed // zero
    // RemoveWorkflow
    // GetWorkflow // should fail
}
```

**Comment by ramfox** [comment]
@b5 before diving into getting all these functions settled, I am doing some clean up on parts I neglected. The main one is advancing triggers after they have launched.

I think I might be in favor of adding back trigger ids.

Here is my reasoning, though I would be happy to be wrong!
1) We need some piece of identifying information beyond the workflow id in order for the orchestrator to know which of that workflow's triggers it needs to `Advance`. That identifying information must be emitted by the Listener when the trigger fires, along with the workflow ID.
2) It follows that the Listener must store this identifying information in order to emit it. We discussed in the past that it could store the trigger's index in the list of triggers associated with that workflow. However, this is a bit impractical (doable, but impractical), since the `Listener` only ever has access to the list of `ActiveTriggers` of the workflow, so it will store the index of the `Trigger` with respect to the `ActiveTriggers` not all the `Triggers` of a workflow. This seems unnecessarily complicated, and anyone who is not me or you implementing a `Listener` in the future will need further explanation. However, it takes little to no explanation if we say that a Listener is expected to emit an event with payload of a workflow's ID and the trigger's ID.

I can't remember why we took them out. Was I just trying to be clever?

Alternative paths:
- we could limit the number of triggers of each type to be one, that way we can differentiate between the triggers in the workflow by using the trigger type... I think we want to allow multiple triggers of different types, though so this idea is dead in the water.
- `trigger.Listeners` can hold the entire workflow (not just the workflow id or trigger id) in their ephemeral store. When they get triggered, they advance the trigger that triggered them, and pass the advanced workflow as the payload of the `event.ETWorkflowTriggered` event. This can work because we expect to call `Listen` on any changed workflows, so it is possible that the `Listeners` would always have the most up to date workflows at all times. (and we need to do this anyway, but if a workflow is currently running, we should ensure that the user cannot make any changes, they would need to stop the workflow before making changes)

**Comment by b5** [comment]
yeah, advancing is a lot easier if IDs are there. Let's try to keep the length of IDs short, as trigger & hook IDs really only need to be unique to each workflow. Something like 5 random alphanumeric characters would work well.

We could continue to rely on index position, but I realized that would make it a lot harder to write UI that lets users affect that order.

For the record, getting rid of IDs was my idea 😄

**Comment by ramfox** [comment]
DeployWorkflow emits events so the frontend can know what's going on!

Proposed events:
`event.ETDeployStart`
`event.ETDeploySaveDatasetStart`
`event.ETDeploySaveDatasetEnd`
`event.ETDeploySaveWorkflowStart`
`event.ETDeploySaveWorkflowEnd`
`event.ETDeployRunWorkflowStart`
`event.ETDeployRunWorkflowEnd`
`event.ETDeployEnd`
`event.ETDeployError`

Thinking we have two payloads.
```
type DeployPayload struct {
   Ref: string // ref string of the dataset
   DatasetID: string // dataset init id
   WorkflowID: string // workflow id
   RunID: string // run id
}

type DeployErrorPayload struct {
   Error: string // string describing error
}
```

The `DeployPayload` would be the payload for all non-`DeployError` events. It would get progressively filled in as the deploy process proceeds and we have more information.

Would like some feedback on the placement of `event.ETDeployEnd`:
The `event.ETDeployEnd` event would end all Deploys, regardless of whether they were successful. Wondering if there is any "rollback" that needs to happen, should the `event.ETDeployEnd` event would come after the rollback has finished? Or is that not something the frontend needs to wait for. Should we have a separate event for this?

Note: this implies that if there is a part of the Deploy that has been left out, eg there is no dataset update or we do not "run" the workflow, those associated events will not be fired.

**Comment by b5** [comment]
* into the set of proposed events.
* Let's match the current `Event` naming suffix on payload structs: `DeployPayload` -> `DeployEvent`

> Should DeployPayload and DeployErrorPayload just be combined, since there is only one field difference (Error)

I'd suggest embedding `DeployEvent` in a `DeployErrorEvent`: 

```go
type DeployErrorEvent struct {
  DeployEvent
  Error error
}
```

**Comment by ramfox** [comment]
in zoom to zoom convo we settled on this:
```
event.ETDeployStart
event.ETDeploySaveDatasetStart
event.ETDeploySaveDatasetEnd
event.ETDeploySaveWorkflowStart
event.ETDeploySaveWorkflowEnd
event.ETDeployRun
event.ETDeployEnd

type DeployPayload struct {
   Ref: string // ref string of the dataset
   DatasetID: string // dataset init id
   WorkflowID: string // workflow id
   RunID: string // run id
   Error: string // only populated on event.ETDeployEnd events that indicate the deploy ended in error
 }
```
