### ISSUE TITLE
Qri 0.1.0 Planning

### ISSUE THREAD

**Issue by b5** [qri-io/qri#185]
oooookay, time to trim back & cut a release. Now that we know we're a GDVCS (global dataset version control system), let's carve a feature set from our existing code base & write tests & get a release candidate out the door. The goal here is to get something stable to ship qri-io/frontend 0.1.0 against. I'm cutting away anything that's remotely unfinished in favor of a solid base we can build future versions against.

### Dataset Definition
We've spent a lot of time honing & refining our dataset definition. Let's finish one last touch before shipping: Replace dataset.Schema with jsonschema.Schema.

### CLI Commands:
Qri 0.1.0 should ship with the following CLI commands:
* `init` - initialize a qri repository
* `list` - list local datasets
* `add` - add a dataset to your local repository
* `remove` - remove a dataset
* `update` - write a change to a dataset's history
* `rename` - change a dataset name
* `log` - show change logs for a dataset
* `validate` - validate data against a given dataset or schema
* `profile` - get and set profile information
* `config` - get and set config information
* `daemon` - spin up a qri "server" with JSON API

All of these options should also be available in the API. Let's modify our integration tests to have a happy-path version of all mentioned CLI commands.

You'll notice all talk of transformations, SQL, Search, Peers, etc. Is gone. Gotta crawl before you can walk. I'd like to ship a 0.1.0 that is _stable_ and _extensible_. getting the frontend installer script to work on places other than my machine is going to be tough enough as is 😄. Based on this, I'm hoping we can get this done by **next Thursday, January 26th**.

Onward!

**Comment by b5** [comment]
Ok, just finished an api design session with the team, we've made some terminology changes & added some much needed extra functionality. Here's the complete, updated list of commands that'll ship with 0.1.0:

Qri 0.1.0 should ship with the following CLI commands:
* App Commands:
  * `setup` - set up a qri repository (formerly init)
  * `config` - get and set config information
  * `profile` - get and set profile information
* Dataset Commands
  * `list` - list local datasets
  * `add` - add a dataset to your local repository
  * `remove` - remove a dataset
  * `save` - save changes to a dataset (formerly update)
  * ~`update` - fetch remote changes to a dataset~ (pushed to 0.2)
  * `rename` - change a dataset name
  * `log` - show change logs for a dataset
  * `validate` - validate data against a given dataset or schema
  * `export` - write datasets from qri to the local file system
* Network commands
  * `connect` - connect to the distributed web and spin up a local API (formerly daemon / server)

Most of this is renaming, except for the export command, for which I'll file an issue. I'm planning on documenting the short & long descriptions for these commands over on #193. 

I'm interested to hear if others find `add` & `save` to be a little weird. Meh, let's ship it and find out.

**Comment by ramfox** [comment]
Qri 0.1.0 should ship with the following CLI commands:

* App Commands:
  * `setup` - set up a qri repository (formerly init)
  * `config` - get and set config information
  * `profile` - get and set profile information
* Dataset Commands
  * `list` - list local datasets
  * `add` - add a dataset to your local repository
  * `remove` - remove a dataset
  * `save` - save changes to a dataset (formerly update)
  * `rename` - change a dataset name
  * `log` - show change logs for a dataset
  * `validate` - validate data against a given dataset or schema
  * `export` - write datasets from qri to the local file system
* Network commands
  * `connect` - connect to the distributed web and spin up a local API (formerly daemon / server)
  * `connections` - list of peers you are connected to
  * `peer` - establish connection with a specific peer via peername or peerID
  * `peer info` - get basic info from specific peer
  * `peer datasets` - get list of peer's datasets

Potential Qri 0.2 commands:
  * `keep` - fetch peer's dataset and add it to your repository
  * `update` - fetch remote changes to a dataset

**Comment by b5** [comment]
nice. What do y'all think about replacing `qri peer datasets` with `qri list [username]`?

Second proposal, what about renaming `list` to `datasets`?

**Comment by ramfox** [comment]
If we rename `qri peer datasets` with `qri list [username]`  we should also rename `qri peer info` to `qri info username`

Which I like actually. 

I'm pretty all for changing `list` to `datasets` (and or `ds`) and `log` to `history` and aliasing `list` and `log` for those more comfy with it.

Which means the above would be
`qri peer datasets` -> `qri datasets [username]`

Thoughts?

**Comment by b5** [comment]
yeah I'm into it. Basically we're enforcing the convention that no parameters means _you_, one param without a slash means peer,  and username/datasets means dataset.

```shell
$ qri info
Peername: b5
Name: Brendan O'Brien
Info: Someone who could love dogs
Stats: 2 datasets, ...

$ qri info rico
Peername: rico
Name: Rico Gardaphe
Info: Lover of all doggos.
Stats: 1 dataset, ...

$ qri info rico/comics
Name: List of Comic characters
Stats: 47 entries, 2.3Mb, 27 changes
Description: Comics is a blah blah..

$ qri datasets
b5/yearly_rainfal
b5/num_pigeons_on_my_lawn

$qri datasets rico
rico/comics

$qri datasets rico/comics
error: cannot get datasets of a dataset
```
Feels right to me.

**Comment by ramfox** [comment]
What if we blend the two?

```shell
$ qri info
your profile:
Peername: b5
Name: Brendan O'Brien
Info: Someone who could love dogs
Stats: 2 datasets, ...

$ qri info rico
Peername: rico
Name: Rico Gardaphe
Info: Lover of all doggos.
Stats: 1 dataset, ...

$ qri info rico/comics
Name: List of Comic characters
Stats: 47 entries, 2.3Mb, 27 changes
Description: Comics is a blah blah..

$ qri list
b5/yearly_rainfal
b5/num_pigeons_on_my_lawn

$ qri list rico
rico/comics

$ qri list rico/comics
error: cannot get datasets of a dataset
```

**Comment by ramfox** [comment]
Qri 0.1.0 should ship with the following CLI commands:

* App Commands:
  * `setup` - set up a qri repository (formerly init)
  * `config` - get and set config information
  * `profile` - get and set profile information
  * `info`
    * `qri info` - get your profile information
    * `qri info <peername>` - get peer's information
    * `qri info <peername>/<datasetname>` - get dataset information
  * `list`
    * `qri list` - get list of my datasets
    * `qri list <peername>` - get list of peer's datasets
* Dataset Commands
  * `add` - add a dataset to your local repository
  * `remove` - remove a dataset
  * `save` - save changes to a dataset (formerly update)
  * `rename` - change a dataset name
  * `log` - show change logs for a dataset
  * `validate` - validate data against a given dataset or schema
  * `export` - write datasets from qri to the local file system
* Network commands
  * `connect` - connect to the distributed web and spin up a local API (formerly daemon / server)
  * `connections` - list of peers you are connected to
  * `peer` - establish connection with specific peer via peername or peerID
Potential Qri 0.2 commands:
  * `keep` - fetch peer's dataset and add it to your repository
  * `update` - fetch remote changes to a dataset

**One thing I sort of snuck in here is the `peer` command as a mirror to the API endpoint `/connect/peername` or `/connect/peerID`** Not sure if this is the best use of the `peer` command and actually whether or not we even need it. Thoughts?

**Comment by b5** [comment]
THE PLANNING HAS HAPPENED.
