### ISSUE TITLE
Rename `qri server` command

### ISSUE THREAD

**Issue by b5** [qri-io/qri#188]
_moved from qri-io/dataset#51_

I'll admit to not being a big fan of the word "daemon", I'm starting to see where the IPFS team got it from, which seems to be a process of elimination:

* `server` doesn't really make sense, and at worst is misleading. Who is the client? what's being served?
* `node` might make sense, but these days when I hear "node" I think "javascript", and it invites lots of cognitive overhead, especially when trying to distinguish which bit is the "node", which bit is the "process that runs the node", ugh.
* `online` might work, switching to a verb.
* `connect` jumps out as a possibility. It's a little confusing that `connect` would spin up an API locally..., and whatever this command is, it should be configurable to just serve up data you have locally, without connecting to the p2p/qri d.web
* `deamon`, while a very shitty word, is at least accurate. 

Thoughts? I think we need to drop server, but the question is what do we replace it with?

**Comment by ramfox** [comment]
I think this would depend on who would be using the command and for what purpose.

If part of our goal is to be stepping away from 'weird-computer-techie' language, then calling something a 'daemon' is not going to achieve that goal. But if the kind of folks who would normally use the command would be more put off by not having it accurately named, then daemon makes sense.

I don't know that I have a problem with `qri online` being the command, unless using a verb is usually a big no no that we are violating.

**Comment by b5** [comment]
Totally, my concern with `online` is the ambiguity of what the command is "onlining". `qri server` currently does three things:
* make our local API available (API "online")
* connect to IPFS (IPFS "online")
* connect to qri p2p network (qri "online")

The more I think about it, that might actually make _more_ sense, where the default `qri online` command connects up all three by default, and we could configure flags / arguments for changing the things that `online` activates.
