### ISSUE TITLE
ds.get_body() returns None when there is an existing body

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1894]
Observed when using rosebud-api with qrimatic frontend.

I deployed a new workflow and added some logic to append a row to the existing body only if the body is not `None`.  When it runs, `get_body()` is always `None` for some reason, so instead of appending, I always end up with a single row in my dataset (it overwrites the old body)

<img width="809" alt="Home___Qri_Cloud" src="https://user-images.githubusercontent.com/1833820/130520384-93ae0348-edfe-4dc4-bd81-dee909a886df.png">

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qrimatic/commit/bc3b0c416fc862c44bd66128c1aa78a3e30352ea.
