### ISSUE TITLE
document all qri 0.1.0 commands in CLI

### ISSUE THREAD

**Issue by b5** [qri-io/qri#193]
Currently lots of our commands are poorly documented if at all. We should take some time to write, full, proper descriptions of all 0.1.0 commands, as users will need them to be able to find their way around.

**Comment by b5** [comment]
copying draft of commands here, feel free to weigh in with any suggestions 😄 

# **App Commands:**

*app commands affect the behavior of the entire qri application.*


## setup 

*Initialize qri and IPFS repositories, provision a new qri ID*

qri setup [--no-ipfs]

Setup is the first command you run to get a fresh install of qri. If you’ve never run qri before, you’ll need to run setup before you can do anything. Setup does a few things:

- create a qri repository to keep all of your data
- provisions a new qri ID
- create an IPFS repository if one doesn’t exist

This command is automatically run if you invoke any qri command without first running setup.
If setup has already been run, by default qri won’t let you overwrite this info.


## profile

*get and set user profile information*

profile is a bit of a cheat right now. We’re going to break profile out into proper commands later on, but for now we’re hoping you can edit a JSON file of profile information. For now running qri profile get will write a file called profile.json containing current profile info. Edit that file and run qri profile set <file> to write configuration details back.

Expect the profile command to change in future releases.


## config

*get and set local configuration information*

config is a bit of a cheat right now. we’re going to break profile out into proper parameter-based commands later on, but for now we’re hoping you can edit a YAML file of configuration information. For now running qri config get will write a file called config.yaml containing current configuration info. Edit that file and run config set <file> to write configuration details back.

Expect the config command to change in future releases.


# **Dataset Commands:**

*commands for viewing, manipulating, storing and removing datasets* 


## list

*show a list of local datasets*

qri list

list shows lists of datasets. The default list is all datasets you have on your local qri repository.

aliases: `ls`,


## info

*show a summary of a given dataset name*

qri info <dataset ref…>

Info summarizes dataset details for display.

## add

*add a dataset to your local repository*

qri add [--meta <file>] [--structure <file>] <data file>

Add creates a new dataset from data you supply. You can supply data from a file or a URL. When adding data, you can supply metadata and dataset structure, but it’s not required. qri does what it can to infer the details you don’t provide. Adding currently supports two data formats:

- CSV (Comma Separated Values)
- JSON (Javascript Object Notation)

Once you’ve added data, you can use export and save to change a dataset’s data, metadata, and structure.

## remove

*remove a dataset from your local repository*

qri remove <dataset ref…>

remove gets rid of datasets. After running remove, qri will no longer list your dataset as being available locally. By default remove frees up the space taken up by the dataset, but not right away. This is because the IPFS repo that’s storing the data will need to garbage-collect that data when it’s good & ready, which could be anytime. If you’re running low on space, garbage collection will be sooner. Keep in mind that by default your IPFS repo is capped at 10GB in size, if you adjust this cap using IPFS, qri will respect it.

In the future we’ll add a flag that’ll force immediate removal of a dataset from both qri & IPFS. Promise.

## save

*save changes to a dataset*

qri save  [--meta <file>] [--structure <file>] [--data <data file>] [--message <msg>] <dataset ref>

Save is how you change a dataset, updating one or more of data, metadata, and structure. Every time you save an entry is added to your dataset’s log (which you can see by running “qri log [ref]”). Every time you save, you can provide a message about what you changed and why. If you don’t provide a message we’ll automatically generate one for you.

Currently you can only save changes to datasets that you control. Tools for collaboration are in the works. Sit tight sportsfans.

aliases: `commit` 


## rename

*change the name of a dataset*

qri rename <old name> <new name>

Rename changes the name of a dataset. So, uh, it’s worth noting that this can break lots of stuff for other people, especially in these early days of qri. So take our advice and feel free to rename stuff lots at first, but try to settle on a name and stick with it, especially if you want other people to like your datasets.

aliases: `mv` 


## log

*show the history of changes to a dataset*

qri log <dataset ref>

log prints a list of changes to a dataset over time. Each entry in the log is a snapshot of a dataset taken at the moment it was saved that keeps exact details about how that dataset looked at at that point in time. We call these snapshots versions. Each version has an author (the peer that created the version) and a message explaining what changed. Log prints these details in order of occurrence, starting with the most recent known version, working backwards in time.

## validate

*show schema validation errors*

qri validate [--structure <file>] [--data <file>] [<dataset ref>]

validate checks data for errors using a structure, printing a list of issues. By default validate checks dataset data against it’s own structure. validate is a flexible command that works with data and structures either inside our outside of qri by providing one or both of --data and --structure arguments. Providing --structure and --data is an “external validation that uses nothing stored in qri. When only one of structure or data args are provided, the other comes from a dataset reference. For example, to check how a file “data.csv” validates against a dataset "foo”, we would run:
qri validate —data data.csv foo
In this case, qri will will print any validation as if data.csv was foo’s data.

To see how changes to a structure “structure.json” will validate against a dataset in qri, we would run:
qri validate —structure structure.json foo
In this case, qri will print and validation errors as if stucture.json was the structure for dataset foo

Using validate this way is a great way to see how changes to data or structure will affect a dataset before saving changes to a dataset.

## export

*copy datasets to your local filesystem*

qri export [--dataset] [--meta] [--structure] [--data] <dataset ref…>

Export gets datasets out of qri. By default it exports only a dataset’s data to the path [current directory]/[peername]/[dataset name]/[data file]. To export everything about a dataset, use the —dataset flag.

# **Network Commands:**
_commands that primarily deal with the internet(s)_

## connect

*connect to the distributed web and start a local API server*

While it’s not totally accurate, connect is like starting a server. running connect will start a process and stay there until you exit the process (ctrl+c from the terminal, or killing the process using tools like activity monitor on the mac, or the aptly-named “kill” command). Connect does three main things:

- Connect to the qri distributed network
- Connect to IPFS
- Start a local API server

When you run connect you are connecting to the distributed web, interacting with peers & swapping data.

The default port for the local server is 2503. We call port 2503 “the qri port”. It’s a good port, lots of cool numbers in there. Some might even call it a “prime” port number.

**Comment by ramfox** [comment]
Yay! This is great!

Some thoughts I have:

We should probably be more explicit when showing the commands and flags, eg:

qri add FILENAME.json (—meta METADATAFILENAME.json)(—structure STRUCTUREFILENAME.json)

‘Once you’ve added data, you can use export to pull the data out of qri, change the data outside of qri, and use save to update a dataset’s data, metadata, and structure on qri’

I have thoughts about the order of commands in validate, will edit this comment and expand when not on my phone 

On one hand, if every command always ends with the datasetref (which I’m assuming is the new name for name, lol), then the convention is fine I guess, but it feels weird to me as someone reading that the ref would be so far from the command.

Lol @ “internet(s)”

**Comment by b5** [comment]
> Should we be more explicit when showing the commands and flags?

the `help` section for each command will come with longer descriptions of what each flag does. I'm hoping to keep the usage diagrams simple so you can sorta spot the patterns across commands. In this case `--meta`, `--structure`, and `--data` flags should always be "a file that corresponds to that part of a dataset".

> ‘Once you’ve added data, you can use the export command to pull the data out of qri, change the data outside of qri, and use the save command to record those changes to qri’

Much better.

> Rename, we should be explicit for folks who aren't familiar with mv: qri rename <old dataset ref> <new dataset ref>

Agreed! Changing.

> Unless this violates some sort of norm that I'm not realizing that will bother folks who are command line literate.

Yeah I think this is one convention we should keep. Most CLI's put _flags_ before _arguments_ for a number of reasons, the biggest one that comes to mind for me is when arguments are chained it's very easy to accidentally add flags to the wrong thing, especially when using short valueless flags. Consider chaining mkdir's `-p` with qri's "passive":

```bash
$ mkdir ~/my/datasets/ -p & qri add file.csv -s structure_file.json -p 
```

Having them on the end adds to confusion IMHO.  Our CLI should happily accept the latter form, but I don't think we should encourage it.

> Also not sure I'm sold to calling it dataset ref rather than name, even though it's accurate.

I think your hunch is right, It's a lot of cognitive overhead, especially for a string. Let's call them names when they're strings and refs when they're parsed to go structs. changing.

**Comment by osterbit** [comment]
is `qri view {datasetname}` supposed to be on this list?

**Comment by b5** [comment]
I don't think `qri view` is going to make this release. I think it'd be nice to ship `view` & `search` together in the next release?
