### ISSUE TITLE
API endpoints slated for removal for qri 0.1.0

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#197]
Now that we have redesigned and focused our CLI, we should take this update and modify the API to match.

These are my proposed modifications and removals:

### Removal:
``` go
OPTIONS /search
GET /search remove
POST /search

OPTIONS /add/ 
POST /add/ // adds dataset from hash

// These three have been commented out, should remove them:
OPTIONS /queries
GET /queries // list of all queries
GET /queries/ // get list of queries referencing a specific dataset
OPTIONS /run
POST /run // execute a query

OPTIONS /data/ipfs/ // returns valid http methods for endpoint
GET /data/ipfs/ // returns data portion of dataset

POST /datasets // add a dataset from a file // should be removed, now longs in /add/
PUT /datasets // saves (commits) a dataset (redundant)
OPTIONS /datasets
OPTIONS /datasets/
OPTIONS /peers/
```

Refactor:
``` go
// init -> add
OPTIONS /init/ -> OPTION /add/ : return valid http methods for endpoint
POST /init/ -> POST /add/ : adds a dataset from a file
// download -> export
OPTIONS /export/
GET /download/ -> GET /export/
// datasets -> list
OPTIONS /list
GET /datasets -> GET /list
// /datasets/ -> save
OPTIONS /save/
PUT /datasets/ -> PUT, POST /save/
// /datasets/ -> remove
OPTIONS /remove/
DELETE /datasets/ -> POST, DELETE /remove/
// /datasets/ -> info
OPTIONS /info
GET /datasets/ -> GET /info/ 
// / (root) now means something different
(root) // renders the home page, but if there is a [peer_name]:
// /peers/ -> [peer_name]
GET /peers/ -> GET /[peer_name] // returns info about peer
GET /[peer_name]/[dataset_name] // returns info about dataset
GET /[peer_name]/[dataset_name]/at/[dataset_hash] // returns info about dataset at that specific save point

// /peernamespace/ -> /[peer_name]/list
GET /peernamespace/ -> GET /[peer_name]/list // returns list of peer's datasets
// /connect/peerID -> /connect/[peer_name] and /connect/peerID
GET /connect/ // contect to specific peer
// need to add option for /rename
OPTIONS /rename
```

Stays the same:
``` go
GET /status //  Health Check 
OPTIONS /profile
GET /profile // get current user profile
POST /profile // update current user profile
POST /rename // renames dataset
PUT /rename // renames dataset
OPTIONS /peers
GET /peers // returns list of peers
OPTIONS /profile/photo // returns valid http methods for endpoint
PUT /profile/photo // set profile photo
POST /profile/photo // set profile photo
OPTIONS /profile/poster // returns valid http methods for endpoint
PUT /profile/poster // set profile poster
POST /profile/poster // set profile poster
OPTIONS /connections
GET /connections // list of connections
OPTIONS /connect/
/ipfs // responds to IPFS Hash requests with raw data
OPTIONS /history/ 
GET /history/ // returns history of changes for a given dataset
```

CLI commands with no representation in the API as of right now:
* `config`
* `setup`
* `validate`

**Question: will profile photos/posters still work?**
Edit: *Paraphrasing b5: YES*
*Added profile/photos and profile/posters to endpoints that will remain the same*

**thoughts about /history/ vs. /log/**
So, I think history is a much for 'friendly' term. Any thougths about having `qri log` be `qri history` and alias `log`?
If not, what are your thoughts about changing /history/ to /log/ and use the term log on the frontend?
Edit: *No, not changing to log, leaving as history*
  
**Question about /ipfs/:**
Straight up, does this just serve files from ipfs through qri? Does this belong in 0.1.0? Thinking no because there is no equivalent CLI? But honestly, not sure if it does other things we need, would love input 
Edit: *Paraphrasing b5: we need this keep it*

**also noted**
I pulled apart /datasets and /datasets/ and made their http methods associated with specific endpoints. This does not have to be the way we do it. In which case, I think removing /info/, /add/, /save/, /delete/ and associate them with get, post, put, delete /datasets/ makes the most sense
Edit: *looks like this is the way we are going to go!*

**Comment by b5** [comment]
> will profile photos/posters still work?

Yes profile/poster photos stay. I'm incredibly vein. How else will people see the edges of my bowtie? 

Also, @osterbit this is  another good spot for creating a `mime/multipart` file upload request when we get around to writing tests for these endpoints. At this point we should think about writing a general `testUploadFile` function.

> Any thougths about having qri log be qri history and alias log?

Interesting. I could be in. what do you think @rgardaphe & @osterbit, should we change `qri log` to `qri history`?

> Straight up, does this just serve files from ipfs through qri?

lol yuuuuup. It belongs, mainly b/c it's dope, and we need it to do things like load profile photos (which are stored on IPFS).

**Comment by osterbit** [comment]
disussed `log` vs `history`
- `log` shorter and same as git
- `history` longer and more accessible
- preference: tossup
- decision: tossups should default to git?

**Comment by ramfox** [comment]
- Thoughts on using "log" as a front end term, I'm for it if that's what we use on the CLI?
- How do we feel about the refactoring section?

**Comment by ramfox** [comment]
Okay so after our discussion of vanity names as part of the API I have 3 main questions:

let's say my repo is has the name `ramfox` and it contains a dataset called `comics`
my peer's repo is called `rico` and it has a dataset called `doggos`
```shell
GET https://localhost.com:2503/rico // returns info about peer rico
GET https://localhost.com:2503/rico/doggos // returns info about dataset rico/doggos
GET https://localhost.com:2503/rico/doggos/at/ipfs/Qmfs.... // returns info about dataset rico/doggos 
// at a specific save point
```
1) I think we spoke about this and the answer was yes but to clarify does this also return info about a dataset at a specific save point?:
```
GET https://localhost.com:2503/ipfs/Qmfs... 
```
now to access my own informations and datasets I do:
```shell
GET https://localhost.com:2503/info // returns my info
GET https://localhost.com:2503/ramfox/comics // ????? returns info about dataset ramfox/comics
GET https://localhost.com:2503/ramfox // ??? returns my info
GET https://localhost.com:2403/profile // returns my info
```

2) Should we nix `/info` and just follow the pattern that using `/[peername]` will return my info too, especially since `/profile` does the same thing?
3)  Is `/[peername]/[datasetname]` the way a user accesses their own dataset info using the API (I do like that it mirrors the CLI: `qri info ramfox/comics` )

**Comment by b5** [comment]
> 1. I think we spoke about this and the answer was yes but to clarify does this also return info about a dataset at a specific save point?:

If you feed the hash of a dataset to `/ipfs/` endpoint it will return data stored on IPFS, which might be a dataset, but `/ipfs/` is a "dumb" endpoint, it just returns data from the network. So if you wanted to say, have some dataset-specific API query param, you'd need to go through `/ramfox/comics?showvizconfig=true` (made up query param as an example).

2. We should have a fixed endpoint that indicates the currently authenticated peer. github's [`/user`](https://developer.github.com/v3/users/#get-the-authenticated-user) is a great example. I agree that `/info` is a little misleading. I often like `/me` for the currently auth'd user. We need this fixed endpoint because the _server_ holds the source of truth on who the current user is, and without it we'd have no way of disambiguating this info.

3. Yep. I think users should have to use `/[peername]/[datasetname]` to see their own data.

**Comment by ramfox** [comment]
Okay cool!

> I often like /me for the currently auth'd user. We need this fixed endpoint because the server holds the source of truth on who the current user is, and without it we'd have no way of disambiguating this info.

Cool. How would GET /me differ from GET /profile?

**Comment by b5** [comment]
oops, yes let's nix `/profile`. I totally forgot to mention this bit, but `/me` should operate as a _stand-in for my username_, so I I should be able to:
```
GET http://localhost:2503/me/comics
GET http://localhost:2503/me/comics/at/ipfs/QmFoo...
...
``` 
Me here is operating like a magic word for "current user". It'll also help a bunch for long usernames on the CLI, and replacing it with your full peername should give the same info. These two should return the same thing if I'm user `b5`
```
GET http://localhost:2503/me
GET http://localhost:2503/b5
```

**Comment by ramfox** [comment]
Awesome! Thanks, I'll update the api and cli issues to match `:)`

**Comment by b5** [comment]
ugh, wait my bad. I'd totally forgotten about `/profile/photo` and `/profile/poster`. In that case let's keep `/profile`, because it's mainly there to serve as an API proxy for the `profile` CLI command. Knowing that we now have _three_ ways to refer to a user's profile, we'll refactor this in the future, but for now I think it makes the most sense.

So yeah, let's keep _both_ `/profile` _and_ `/me`.

**Comment by ramfox** [comment]
Dope!

**Comment by ramfox** [comment]
0.1.0 was released!!! Closing issue :)
