### ISSUE TITLE
Refactor DatasetDiffer to include jsondiffer and write core method for cli

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#198]
#### dataset differ
- [x] open WIP pull request
- [ ] update unexporeted sub-component differs (structure, data, meta, etc)
  - [x] to be exported
  - [ ] to take arguments consistent with their scope (structure differ should take structures etc, instead of datasets)
- [ ] update Diff and DiffList structs to align with jsondiff
- [ ] update DiffDataset to output a map of its subcomponents rather than a flat slice of diffs
#### add diff function to core
  - [ ] should be a method on DatasetRequest struct
  - [x] should take a diffParams struct that includes a left and right dataset ref
  - [ ] should also take an empty result struct  and return an error
  - [ ] should allow flexibility to just diff structure or just diff data etc.
  - [ ] should allow for multiple output formats (or this may belong in the cli or api fucntions that call the core function

**Comment by osterbit** [comment]
@b5 this sound about right?

**Comment by osterbit** [comment]
possible interface from the qri side: 

```go
// DiffParams defines parameters for diffing two datasets with Diff
type DiffParams struct {
	// The pointers to the datasets to diff
	DsLeft, DsRight *dataset.Dataset
	// The output format specified as a string. Currently support "struct", "ascii_full", and "ascii_delta"
	Format string
	// whether output should include color text modifiers if applicable
	Color bool
	// override flag to diff full dataset without having to specify each component
	DiffAll bool
	// if DiffAll is false, DiffComponents specifies which components of a dataset to diff
	// currently supported components include "structure", "data", "meta", "transform", and "visConfig"
	DiffComponents map[string]bool
}

// Diff computes teh diff of two datasets
func (r *DatasetRequests) Diff(p *DiffParams, diffs *datasetDiffer.DiffList) (err error) {
	// TODO
	return fmt.Errorf("Not yet implemented")
}
```

**Comment by b5** [comment]
Looks great! At first I was a little concerned about the `DiffComponents` field being a little too loosie-goosie, but I think it's a good initial implementation.
