### ISSUE TITLE
Refactoring API endpoint to reflect CLI more closely

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#200]
We've recently redesigned the qri CLI interface with new naming conventions. We should take this updated terminology and modify the API to match!

Here's what our api currently looks like:

``` go
// / WebappHandler
(root) // renders the home page
// /status  HealthCheckHandler

// /ipfs  HandleIPFSPath
/ipfs // responds to IPFS Hash requests with raw data

// /profile   ProfileHandler
OPTIONS /profile
GET /profile // get profile 
POST /profile // save profile

// /profile/photo   SetProfilePhotoHandler
OPTIONS /profile/photo
PUT /profile/photo // set profile photo
POST /profile/photo // set profile photo

// /profile/poster  SetPosterHandler
OPTIONS /profile/poster
PUT /profile/poster // set profile poster
POST /profile/poster // set profile poster

// /search  SearchHandler
OPTIONS /search
GET /search // search datasets
POST /search // search datasets

// /peers   PeersHandler
OPTIONS /peers
GET /peers // list peers

// /peers/  PeerHandler
OPTIONS /peers/
GET /peers/ // get peer profile

// /connect/  ConnectToPeerHandler
OPTION /connect/
GET /connect/ // connect with specific peer

// /connections   ConnectionsHandler
OPTIONS /connections 
GET /connections // lists all connections

// /peernamespace/  PeerNamespaceHandler
OPTIONS /peernamespace/
GET /peernamespace/ // lists peer's datasets

// /datasets  DatasetsHandler
OPTIONS /datasets
GET /datasets // list user's datasets
PUT /datasets // 'save'/'update'/'commit' dataset
POST /datasets // adds dataset to repo

// /datasets/   DatasetHandler
OPTIONS /datasets/
GET /datasets/ // list specific datasets
PUT /datasets/ // 'save'/'update'/'commit' dataset
DELETE /datasets/ // remove dataset from repo

// /add/  AddDatasetHandler
OPTIONS /add/
POST /add/ // add an existing dataset to user's repo

// /init/   InitDatasetHandler
OPTIONS /init/
POST /init/ // add a new dataset to user's repo from file or url

// /rename  RenameDatasetHandler
POST /rename // change dataset's name
PUT /rename // change dataset's name

// /data/ipfs/  StructuredDataHandler
OPTIONS /data/ipfs/
GET /data/ipfs/ // returns data from dataset

// /download/   ZipDatasetHandler
/download/ // download dataset as a zip

// /history/  LogHandler
OPTIONS /history/
GET /history/ // return history/log of dataset changes
```

The new commands we're shipping with 0.1.0 are:

* App Commands:
  * `setup` - set up a qri repository (formerly init)
  * `config` - get and set config information
  * `profile` - get and set profile information
  * `info` - get your info (no params), peer info (peername as param), dataset info (peername/datasetname as param)
* Dataset Commands
  * `list` - get list of your datasets (no params) or peer datasets (peername as param)
  * `add` - add a dataset to your local repository
  * `remove` - remove a dataset
  * `save` - save changes to a dataset (formerly update)
  * `rename` - change a dataset name
  * `log` - show change logs for a dataset
  * `validate` - validate data against a given dataset or schema
  * `export` - write datasets from qri to the local file system
* Network commands
  * `connect` - connect to the distributed web and spin up a local API (formerly daemon / server)
  * `connections` - list of peers you are connected to

So based on that and the discussion in #197, let's change the API to look like this:

``` go
// / PeerHandler
OPTIONS /
GET / // renders homepage
GET /[peername] // returns info about peer
GET /[peername]/[datasetname] // returns info about that dataset
GET /[peername]/[datasetname]/at/[hash] // returns info about that dataset at that specific save point
GET /[peername]/list // returns list of peer's datasets

OPTIONS /me/
GET /me/[datasetname] // get info about that dataset (alias for /[peername]/[datasetname]
GET /me/[datasetname]/at/[hash] // get info about that datset at that specific save point (alias for /me/[peername]/[datasetname]/at/[hash]

// HealthCheckHandler
GET /status //  Health Check 

// ProfileHandler
OPTIONS /profile
GET /profile // get current user profile
POST /profile // update current user profile

// ProfileHandler
OPTIONS /me
GET /me // get current user profile
POST /me // update current user profile

// SetProfilePhotoHandler
OPTIONS /profile/photo // returns valid http methods for endpoint
PUT /profile/photo // set profile photo
POST /profile/photo // set profile photo

// SetPosterHandler
OPTIONS /profile/poster // returns valid http methods for endpoint
PUT /profile/poster // set profile poster
POST /profile/poster // set profile poster

// ConnectToPeerHandler
OPTIONS /connect/
GET /connect/ // contect to specific peer

// ConnectionsHandler
OPTIONS /connections
GET /connections // list of connections

// InitDatasetHandler -> AddDatasetHandler
OPTION /add/ : return valid http methods for endpoint
POST /add/ : adds a dataset from a file

// ZipDatasetHandler
OPTIONS /export/
GET /export/

// ListDatasetsHandler
OPTIONS /list
GET /list

// DatasetHandler -> SaveDatasetHandler
OPTIONS /save/
PUT /save/
POST /save/

// DatasetHandler -> RemoveDatasetHandler
OPTIONS /remove/
POST /remove/
DELETE /remove/

// RenameDatasetHandler
OPTIONS /rename
POST /rename // renames dataset
PUT /rename // renames dataset

// PeersHandler
OPTIONS /peers
GET /peers // returns list of peers

// HandleIPFSPath
/ipfs // responds to IPFS Hash requests with raw data

// LogHandler
OPTIONS /history/ 
GET /history/ // returns history of changes for a given dataset
```

So to be explicit, these are the specific things to be removed and refactor (and what needs to stay the same :)):

### Removal:
``` go
OPTIONS /search
GET /search remove
POST /search

OPTIONS /add/ 
POST /add/ // adds dataset from hash

OPTIONS /data/ipfs/ // returns valid http methods for endpoint
GET /data/ipfs/ // returns data portion of dataset

POST /datasets // add a dataset from a file // should be removed, now longs in /add/
PUT /datasets // saves (commits) a dataset (redundant)
OPTIONS /datasets
OPTIONS /datasets/
GET /datasets/ -> GET /info/ 
OPTIONS /peers/
OPTIONS /peernamespace/
```

Refactor:
``` go
// init -> add
OPTIONS /init/ -> OPTION /add/ : return valid http methods for endpoint
POST /init/ -> POST /add/ : adds a dataset from a file

// download -> export
OPTIONS /export/
GET /download/ -> GET /export/

// datasets -> list
OPTIONS /list
GET /datasets -> GET /list

// /datasets/ -> save
OPTIONS /save/
PUT /datasets/ -> PUT, POST /save/

// /datasets/ -> remove
OPTIONS /remove/
DELETE /datasets/ -> POST, DELETE /remove/

// / (root) now means something different
(root) // renders the home page, but if there is a peername:
// /peers/ -> [peer_name]
GET /peers/ -> GET /[peer_name] // returns info about peer
GET /datasets/ -> GET /[peer_name]/[dataset_name]/at/ipfs/[dataset_hash] // returns info about dataset
GET /datasets/ -> GET /ipfs/[dataset_hash] // returns info about dataset

// /peernamespace/ -> /list/[peernamespace]
GET /peernamespace/ -> GET /list/[peernamespace] // returns list of peer's datasets

// /connect/peerID -> /connect/[peer_name] and /connect/[peerID]
GET /connect/ // contect to specific peer

// need to add option for /rename
OPTIONS /rename

// need to alias /me for /profile
OPTIONS /me
GET /me
POST /me

// need to alias /me/[dataset] for /[peername]/[datasetname]
OPTIONS /me/
GET /me/[datasetname]
```

Stays the same:
``` go
GET /status //  Health Check 
OPTIONS /profile
GET /profile // get current user profile
POST /profile // update current user profile
POST /rename // renames dataset
PUT /rename // renames dataset
OPTIONS /peers
GET /peers // returns list of peers
OPTIONS /profile/photo // returns valid http methods for endpoint
PUT /profile/photo // set profile photo
POST /profile/photo // set profile photo
OPTIONS /profile/poster // returns valid http methods for endpoint
PUT /profile/poster // set profile poster
POST /profile/poster // set profile poster
OPTIONS /connections
GET /connections // list of connections
OPTIONS /connect/
/ipfs // responds to IPFS Hash requests with raw data
OPTIONS /history/ 
GET /history/ // returns history of changes for a given dataset
```

### Steps to complete:
* [x] Close issue #196 (rename core issues to more closely align with the CLI documentations)
* [x] Read our developer guidelines to follow our commit conventions, etc.
* [x] Open a WIP Pull request so we can follow along!
* Each in a separate commit (please :)), adjusting/adding tests each time:
  * [x] remove /search endpoint and associated handler files and functions
  * [x] remove /add endpoint and associated handler files and functions
  * [x] remove /data/ipfs endpoint and associated handler files and functions
  * [x] refactor /init/ to /add/ & remove POST
  * [x] add OPTIONS /me, GET /me, and POST /me to have the same effect as OPTIONS /profile, GET /profile, and POST /me
  * [x] refactor /download/ to /export/
  * [x] refactor OPTIONS, GET /datasets to OPTIONS, GET /list, remove POST, PUT /datasets
  * [x] refactor PUT /datasets/ to POST, PUT /save/, add OPTIONS /save/, delete PUT /datasets
  * [x] refactor DELETE /datasets/ to DELETE, POST /remove/, add OPTIONS /remove/
  * [x] add OPTIONS /rename
  * [ ] refactor GET /connect/ also take peername as an input
  * [ ] remove OPTIONS /peers/, refactor GET /peers/ to GET /[peername] (need to add logic to root handler that renders the homepage when there are no params, returns the peer's info if there is one param with no slash, returns the most recent dataset info if there is one param with a slash, and returns the info on a specific commit if if there is a param with a dataset hash)
  * [ ] refactor GET /peernamespace, to GET/[peername]/list, remove DELETE /peernamespace
* [ ] code coverage is currently at 46.5%, try to beat that :)

**Comment by ramfox** [comment]
In light of my never ending questions on #197, I'm going to start this issue with the stuff I know we are chucking and avoiding the stickier bits until I have a more firm idea of what's up.
 :)

**Comment by ramfox** [comment]
Also, I have a question about the OPTIONS http method. 

I don't really understand what's happening in the util package (util.EmptyOkHandler) that we import from datatogether/api

I understand that a response with server ok is being written, but is there anything else happening under the hood that I'm not seeing? I thought OPTIONS returned the valid http methods you can use on that endpoint

**Comment by b5** [comment]
You're right to wonder about the whole lot of nothing `apiutil.EmptyOKHandler` returns. OPTIONS is only in place to provide headers for CORS [preflight requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests). OPTIONS doesn't actually say what methods are are available, only that this server supports CORS.

Generally I don't think we even need to specify that our servers support OPTIONS requests, and instead provide a note somewhere that the qri api can be configured to support CORS.

**Comment by ramfox** [comment]
Okay cool!

Great. Does this mean that each endpoint (including /status and the root) need to support OPTIONS?
Also, should we be testing to be sure it is supported?

**Comment by ramfox** [comment]
So I’m a bit stuck on figuring out how to deal with peer names (rather than hashes), specifically for the `/connect/` API endpoint. 
1). Would you mind taking some time tomorrow to briefly talk through with me how some stuff should work. Thinking specifically about the `/connect/` endpoint
