### ISSUE TITLE
docs(cmd): representation of names could be made more consistent across commands

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#210]
when I add a dataset via
```bash
qri add --data cities.csv --meta cities.json me/cities
```
I use the namespace prefix `me/` or `osterbit/`
but when call `qri list`
I get the names without any indication of a namespace:
```bash
cities			: /ipfs/QmWeoPjHFfm9rk4F9irbpB3BobzkK9DNh3YNmBCnCVAqg1/dataset.json
new_cities			: /ipfs/QmamrmvG2hvihVQavGR3zi2yS1QK5vSqTZ1kG8FvS7qp2k/dataset.json
```
which might be misleading to a new user thinking they would only need to use the un-namespaced name when referring to it.

possible path of confusion (that I went down a second ago):
- user unaware of the `me/` namespace to provide a name calls `qri add --data cities.csv --meta cities.json cities` (lacking the prefix)
- calls `qri list` and sees the name wasn't accepted and instead auto-named it `citiescsv`
- attempts to rename it by calling `qri rename citiescsv cities` but gets the error response "current name is required to rename a dataset"

It might suffice to just add an additional explicit statement in the help docs that the name must be formatted as {namespace}/{name}

**Comment by ramfox** [comment]
Not sure if we've talked about this yet in another thread, but I agree it's confusing.

I think for now, at least, that list should show:

```bash
me/cities			: /ipfs/QmWeoPjHFfm9rk4F9irbpB3BobzkK9DNh3YNmBCnCVAqg1/dataset.json
me/new_cities			: /ipfs/QmamrmvG2hvihVQavGR3zi2yS1QK5vSqTZ1kG8FvS7qp2k/dataset.json
```

And maybe during the add process there should be a warning/error if you don't have a `/` in the name argument? Thoughts?

**Comment by b5** [comment]
yea totally. now that #250's landed `qri ls` now shows this:
```
alan/movies@/ipfs/QmZ29tNFNjCe9FEouuw6vjfwwaWoxGEbiShTrYP4wjSeoR
alan/movies2@/ipfs/QmcJBrGjfB4iwEUnFkkgL6wM9uP3UYPHn71KUqUwQdWbRc
```

any `me` references are displayed with the peername instead. Thoughts?

**Comment by osterbit** [comment]
I guess it's early to assume that the datasets I'll be working with are generally *my* datasets, but it would be nice to just be able to optionally leave out the namespace prefix and have qri assume a default namespace that it looks for first based on some configuration setting (like 'default namespace')

**Comment by b5** [comment]
I'm going to close this now that we're reporting all names (relatively) consistently. We still have a ways to go in terms of making things pretty & peer-friendly, but I think we've solved the main point of this issue with our transition to using `DatasetRef` everywhere
