### ISSUE TITLE
feat(cmd): tab completion for names of datasets in repo 🙏

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#211]
like with git branch names, would be so useful!

**Comment by b5** [comment]
SO MUCH THIS

**Comment by osterbit** [comment]
cool library that might be useful/worth looking into : https://github.com/chzyer/readline
- has a `type TabCompleter` ([godoc](https://godoc.org/github.com/chzyer/readline#TabCompleter))

**Comment by Arqu** [comment]
@osterbit you can follow progress on this on https://github.com/qri-io/qri/issues/1236
A nice part has been merged already.
