### ISSUE TITLE
using the add command with the --url flag, ignores the given datasetname

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#243]
`qri add --url http://placetogetdatasets.com/my_new_dataset.csv datasetname`

gives you a datasetRef of:
`me/my_new_datasetcsv@/ipfs/Qm.../dataset.json`

not

`me/datasetname@/ipfs/Qm.../dataset.json`

**Comment by ramfox** [comment]
not actually a bug, this is me missing the memo of having to type me/[datasetname]

closing issue

**Comment by b5** [comment]
hrm, we should think about a way to guard against this. It's a pretty common mistake we've already seen at least once or twice, and commands like add are assumed to be dealing with a dataset... I'll open another issue.
