### ISSUE TITLE
Move validation/input handling to the core (from the cmd and api packages)

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#258]
The core methods should be responsible for handling bad input and returning errors.

The cmd and api packages should be wrappers that shoehorn user input into the proper format to send to the core methods.

Right now, handling bad/missing input is sometimes happening at the cmd and api level, and sometime at the core. This should all happen at the core.

**Comment by ramfox** [comment]
Need to examine each function in core to see if we should move the validation

core/dataset.go:
* [ ] List
* [ ] Get
* [ ] Init
* [ ] Save
* [ ] Rename
* [ ] Remove
* [ ] Add

core/history.go:
* [ ] Log

core/Peers.go:
* [ ] List
* [ ] Info

core/Profile.go:
* [ ] SavePeername
* [ ] SaveProfile
* [ ] SetProfilePhoto
* [ ] SetProfilePoster

core/Search.go:
* [ ] Search
* [ ] Reindex

**Comment by b5** [comment]
I would say this is now done!
