### ISSUE TITLE
Inconsistency with how we handle/load files over the api endpoints

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#263]
Some endpoints assume the file was sent over the wire. Others load a file from an absolute path.

Not exactly sure what the right way to go with this.

With a typical API, you are pinging a remote server that has no access to your directories. In order to send a file, you would need to send the actual file in the request. 

With our API, we assume the server is local and has access to your directories. The paths must be absolute, because your working directory may be different from the directory the qri node uses as its working directory.

But does it makes sense for the server to be able to load files via the API? Seems like it shouldn't. I had been modeling everything on the API after the CLI, which we can safely assume is local. What if we somehow are requesting a qri node that is ours, but is remote? We need to be able to send the file over the wire.

Okay, it seems like what we should really do, is accept both. If the data fields are filled, don't load files. If they aren't, load files. If those files/directories don't exist, error.

**Comment by b5** [comment]
we can't/shouldn't assume that the API will be operating locally. I'd vote to transition _all_ api endpoints that deal with files to accept files sent over the wire, or via arguments that specify urls for where the file lives.

**Comment by ramfox** [comment]
Dope!

need to ensure that we are grabbing files from mime/multipart on:

* [ ] /add (when not pulling from url)
* [ ] /save
* [ ] /profile/photo
* [ ] /profile/poster
