### ISSUE TITLE
Refactor ParseDatasetRef

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#273]
Let's refactor the way we parse a datasetRefs from a string.

This is our nice, clean datasetRef format:
`/peername/datasetname@network/hash`

These are the valid inputs to ParseDatasetRef that will output a clean datasetRef:
```
/peername/
/peername
/peername/datasetname/
/peername/datasetname
/peername/datasetname/@
/peername/datasetname@
/peername/datasetname/@/network/hash
/peername/datasetname/@network/hash
/peername/datasetname/@/hash
/peername/datasetname/@hash
/peername/datasetname@/network/hash
/peername/datasetname@network/hash
/peername/datasetname@/hash
/peername/datasetname@hash
@/network/hash
@network/hash
@/hash
@hash
/peername/datasetname/@/network/hash/junk/junk/...
/peername/datasetname/@network/hash/junk/junk/...
/peername/datasetname/@/hash/junk/junk/...
/peername/datasetname/@hash/junk/junk/...
/peername/datasetname@/network/hash/junk/junk/...
/peername/datasetname@network/hash/junk/junk/...
/peername/datasetname@/hash/junk/junk/...
/peername/datasetname@hash/junk/junk/...
@/network/hash/junk/junk/...
@network/hash/junk/junk/...
@/hash/junk/junk/...
@hash/junk/junk/...
```

So, an @ symbol designates that we are looking for a dataset at a particular time/update.

A peername and a hash can both be a sha base58 encoded hash, although a peername can also just be a string

**Comment by b5** [comment]
nice! I'm hoping `peername/datasetname@network/hash` (no leading slash) is also legal? Tests from your PR seem to indicate that's the case
