### ISSUE TITLE
Weird behavior when you `Get` a datasetRef

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#278]
So if we use the core `Get` function to request a datasetRef using peername & name, we get the correct datasetRef back.

If we use peername, the wrong dataset name, but have a valid path, we will get a dataset back from that path, but the dataset name of that ref is the same wrong dataset name.

So, my proposal is that in repo/refs.go CanonicalizeDatasetRef https://github.com/qri-io/qri/blob/aab40af85719456f8fe11cde1465e3e74af93926/repo/ref.go#L222-L248

We ensure that the peername/datasetname and path are all related to the same ref, returning an error if they are not.

**Comment by b5** [comment]
first:
💥  YOU CAN PUT CODE IN ISSUES!? 💥 

anyway, yes, given that `CanonicalizeDatasetRef` is the first chance you get to actually check for the existence of a ref, this is the sensible thing to do.

**Comment by b5** [comment]
We've made progress on this. Closing due to age.
