### ISSUE TITLE
bug caused by partial dataset creation

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#283]
- when I attempt to add a dataset and something weird happens (like naming issue in #282) and the dataset fails to initialize all the way, the parts that did initialize (like putting the data piece on ipfs) end up causing errors on subsequent attempts (specifically returning a "data already exists" error)
- may be worth trying to put things in some sort of transaction container, adding a cleanup step, or just changing the control-flow around data already existing in core.datasets [around here](https://github.com/qri-io/qri/blob/master/core/datasets.go#L278)

**Comment by b5** [comment]
We've made a _bunch_ of progress on the codepath that generates datasets, based on that I'm going to close this.
