### ISSUE TITLE
docs: building a new version after building a prev version

### ISSUE THREAD

**Issue by machawk1** [qri-io/qri#313]
I sought to try out v0.2.0 and re-followed the instructions from the README. My history of stale sources (see #217) plagued me again -- I received build errors in step 5/5 in the process of building from source and the process failed to build. `go get` did not perform the equivalent of git pull. When performing the latter (`git pull`) manually and repeating the README instructions, qri built as expected.

This caveat may need to be documented in the build instructions -- if I have pulled from source and built before then do so at a later date, the most recent source is not (apparently) subsequently used.

**Comment by b5** [comment]
nice catch, we should consider adding a `git pull` check / call to the makefile.
