### ISSUE TITLE
Better integration between qri graph & IPFS DAG

### ISSUE THREAD

**Issue by b5** [qri-io/qri#314]
we've been kinda half-assing our DAG integration, which now officially needs some work as we start to cache data in places other than IPFS. I'd like to set a clear roadmap on how to make changes that bring better interop, and save a little space while we're at it.

Here's an example of our current state of a qri dataset for consideration:
https://ipfs.io/ipfs/QmNk4KaHETZC28AGMPXLYJLRgpmnDLAP3xEya7oCZuLUZr

we've been [exposing (abusing?) the adder interface](https://github.com/qri-io/cafs/blob/master/castore.go#L94) to read file hashes while the dataset directory is being created to store raw paths. We need these paths for dataset comparison purposes, it's important that these references are IPFS hashes referenced without any directory structure.

The main point of entry for a dataset is `dataset.json`, which, after a number of refactorings has come out looking like this:

### QmNk4KaHETZC28AGMPXLYJLRgpmnDLAP3xEya7oCZuLUZr/dataset.json:
```json
{
  "abstract": "/ipfs/QmYBf5Nqv2kehMVMJJNQVV2vyKxfg2AyNjAS6c7bQvsB8P",
  "commit": "/ipfs/QmNbvLbXk6p1kyXVv9gtcEJUmp2znyHnEkB3GeJWpbA4Se",
  "dataPath": "/ipfs/QmbzYXBhS8b6ph7iyhSxnkS4JPZuJju9SvwJ8Rwdozciwk",
  "meta": "/ipfs/QmNc2RXhzsPFUezLqEC3q8ZuEh2BNMJMnkhaW96A5viXM5",
  "qri": "ds:0",
  "structure": "/ipfs/QmS17GWdSWGGSwweeQLpWr4hcNeH5T4BQpF5Uub9ntUVdg"
}
```

It's starting to look a _lot_ like `ipfs dag get QmNk4KaHETZC28AGMPXLYJLRgpmnDLAP3xEya7oCZuLUZr`:
```json
{
  "data": "CAE=",
  "links": [
    {
      "Cid": {
        "/": "QmYBf5Nqv2kehMVMJJNQVV2vyKxfg2AyNjAS6c7bQvsB8P"
      },
      "Name": "abstract.json",
      "Size": 78
    },
    {
      "Cid": {
        "/": "QmNbvLbXk6p1kyXVv9gtcEJUmp2znyHnEkB3GeJWpbA4Se"
      },
      "Name": "commit.json",
      "Size": 462
    },
    {
      "Cid": {
        "/": "QmbzYXBhS8b6ph7iyhSxnkS4JPZuJju9SvwJ8Rwdozciwk"
      },
      "Name": "data.json",
      "Size": 512808
    },
    {
      "Cid": {
        "/": "QmUVDUJDPs8HFdFk6rzjptUVHbRVg8HTdKJeKjwAZwzDnW"
      },
      "Name": "dataset.json",
      "Size": 350
    },
    {
      "Cid": {
        "/": "QmNc2RXhzsPFUezLqEC3q8ZuEh2BNMJMnkhaW96A5viXM5"
      },
      "Name": "meta.json",
      "Size": 22
    },
    {
      "Cid": {
        "/": "QmS17GWdSWGGSwweeQLpWr4hcNeH5T4BQpF5Uub9ntUVdg"
      },
      "Name": "structure.json",
      "Size": 790950
    }
  ]
}
```

I'd like to check some assumptions with the IPFS team before moving forward with tightening this integration:

### Is it possible / a good idea ATM to inject extra stuff into the IPFS dag API & maintain compatibility with the "vanilla" unixfs api?
(this is specific to the go-ipfs implementation)
At a bare minimum, we'd want to add `"qri": "ds:0"` field to the raw dag. (this is supposed to be the canonical indicator that differentiates a qri dataset from other things). But it's important that this hash still present as a directory & path properly in regular IPFS land.

### ... Or would it make more sense skip DAG manipulations & focus on an IPLD adapter for qri?
We still have to write an adapter for our nascent naming system that ties qri peernames/peerID's to datasets. This'll need an IPLD adapter to teach IPFS how to resolve qri names. We can punt for now on the DAG stuff & circle back to this issue later.

**Comment by whyrusleeping** [comment]
So, it looks like you could replace all your json files with cbor ipld. Basically, if you put json with `ipfs dag put` you can create a cbor IPLD object. And anything in your json that looks like `{"/": "QmFooBar"}` will turn into a link. With that, you could do things like `ipfs dag get QmRootHash/dataset/abstract` and get the abstract, instead of having to read the json file, parse out the hash, and the fetch it from there.

I wouldnt try to be compatible with unixfs if you don't need to. Is there a particular reason you would be considering that?

**Comment by b5** [comment]
fantastic.

main reason for "unixfs compatibility" was our aiming for easier introspection into the raw data. being able to tell people to hit `ipfs.io/ipfs/QmRootHash` and see a directory of data makes the whole process easier to understand. If I'm understanding correctly, a cbor IPLD implementation would still be able to represent the dag as it does in the current implementation (rendering to HTML)?

That being said, we're starting the process of converting all data to CBOR at ingest with the hopes of driving IPLD all the way through the stored data itself (eventually hoping to ship a CBOR chunker if someone doesn't beat us to it). This'll mangle lots of the "pretty" output we get from storing JSON ATM, so if the answer is "no" it won't be much of a loss.

**Comment by whyrusleeping** [comment]
I'm not sure if the gateways still render the cbor objects nicely. We should add support for that somehow if they don't. In any case, it would be great to have a nice ipld browser page to inspect graphs.

**Comment by b5** [comment]
looks like locally I get plaintext:
```
ipfs cat /ipfs/zdpuAuqaSYLv1K9wnMuhPr5wctbaYQTwSDRvENxWQ4dZBdoNv: unrecognized node type
```
ditto for the gateways.

Well this has been wildly helpful. we'll start the transition to ipld cbor mainly because I've spent the last 20 minutes playing with the CLI and it's amazing. If no one has shipped a nice cbor browser in a month I'd be happy throw some time into a PR to make inspecting graphs prettier
