### ISSUE TITLE
bug(connect): --read-only and --disablep2p flags don't do anything

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#332]
In the config refactor, we lost the ability to be in --read-only or --disablep2p mode when we use `qri connect` command

To fix this, we just need to make changes to the connect.go file to alter the config.API.ReadOnly and config.P2P.Enabled if the read-only and disablep2p flags are present, respectively.

**Comment by b5** [comment]
@ramfox can you confirm this was addressed by #338?

**Comment by ramfox** [comment]
yep! added it to the pr
