### ISSUE TITLE
qri profile is now redundant with the config profile

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#336]
We now store profile information in two place, the config.yaml and the profile.json files.

This is a sure fire way to get some buggy behavior. The question now is how to pare down.

- we definitely don't need the `qri profile` commands, we should stick to just the `qri config` commands to edit our profile information.
- however, any changes to profile all go through a validation step, which the config.yaml file does not go through. Should I be bringing that profile validation over to when we set the config? 

Counter argument: Config should only be about technical settings. No profiles. It can have keep the private key, but that's it. Profile stays how it is. We go back to a world where you can't change your peername after setup. Or, if you can, it's through `qri profile set peername new_peername`. `qri info` goes back to showing the profileID and peername

Counter counter argument: Config should only be about technical settings and high level important info. It contains private key, peername, and profileID. Profile only contains bio information + fields that if changed, won't break the app. Peername, profileID, and privkey all live in config only. The core.Get() function reads from the config and reads from the profile, adds them together in one struct and returns that. I like this because it separates the more 'technical requirements' from the fun peer details stuff. We want people to add their twitter/biography/photos, but we don't want to encourage people to change their peername after initially setting it, and they should never change their profileID or privkey. By separating the two, we can encourage one and discourage the other.

@b5 halp

**Comment by b5** [comment]
My view:
_all_ qri configuration details should be stored in `config.yaml`. There are a few reasons for this:
* make auditing problems that arise from configurations happen in one place
* load only one file (yaml seems like it's a little expensive to parse, I'd prefer to do it once)

When peers run into problems we'll always need to confirm their configuration details.

As for the configuration details that should remain immutable (PrivateKey, peerID), my hope in the long run is to remove the private key altogether, instead providing an interface to a GPG / PGP key stored somewhere else on the local system. we'll use caching tricks to store the profile ID. But for now, we should at least do two things:
* remove the profile commands as you'd mentioned
* adjust the config command to disallow & warn when trying to mutate the profile.ID & profile.PrivateKey fields.
* add validation for _all_ config structs in the config package, using the profile.validate you'd previously written as a template
* `config.Config.Validate()` should call validate on all it's struct fields
* call `cfg.Validate` inside `cmd/config.go loadConfig()`, returning an error if the configuration is invalid

If you can tackle those bullets, I'll adjust fsrepo to no longer store it's own `profile.json` among a few other things this affects. Sound good?

**Comment by ramfox** [comment]
Yes! Sounds good.

Will calls to the `core.Info` function stay the same?

**Comment by b5** [comment]
yes... except I think the raw `qri info` delivering profile info didn't make much sense in the first place. instead I think we should direct users to run `qri config get profile`.

closed by #348
