### ISSUE TITLE
Make changes to cmd_test to catch more possible errors

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#337]
In the future, we should be relying on very robust unit tests to make sure our edge cases are behaving the way we want them too.

For now, to get a little more security, let's add cases in our command line integration test.

- with the new config changes, remove some `qri profile` calls in favor of using `qri config`
- rather than refering to a dataset as 'me/<datasetname>', use 'alan/<datasetname>'

**Comment by b5** [comment]
totally agreed. Let's make these changes after we close #336 & #335, the PR that closes #337 should remove the profile command altogether
