### ISSUE TITLE
Keep getting odd log messages

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#357]
I keep getting log messages when I `qri connect` or when I `qri config set` a field:

```
10:49:21.977 ERROR     fsrepo: invalid character '3' after top-level value profile_store.go:31
10:51:54.375 ERROR     fsrepo: invalid character 'M' after top-level value profile_store.go:31
```

But not sure what they are referring to.

**Comment by b5** [comment]
Ok turns out this was a race condition with file writing, which has been addressed by #368. There's still a chance this'll happen but it should be _far_ less common.
