### ISSUE TITLE
Add /config API endpoint that works like the cli config command

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#375]
add an api endpoint:
`/config`
that takes json request and updates the config:
```
{ 
  profile.peername: 'new_peername'
}
```

more details to figure out:
how do we send the profile.photo and profile.poster over the wire? Do I just copy the way it's done on other spaces? should those get special endpoints because they are file based? Probs yes. Will double check with brendan and also do an audit of how this is handled in other places, because I know I've run into it before. Updates to follow.

===============

EDIT: 5/3:
After some discussion with @b5, we are limiting the scope of this for now. We keeping the `/profile` endpoint, and ensuring that this edits the underlying config properly, and tabling the `/config` endpoint.

**Comment by b5** [comment]
Ok, big fan of this feat. What do you think of it working like this?:
* `GET /config` should return the full configuration as a json object
* `POST /config` should accept a full configuration object back, and overwrite the current configuration.

There are some caveats:
* `GET`'s response should have private key(s) removed. 
* `POST` should validate for legal changes (for example, profile.ID can't be changed, we need to make sure it isn't), and re-add private keys so they aren't written to empty on save.

The PR that adds this should abstract the functions in `cmd/confg.go` into new core methods `GetConfig` and `SetConfig`. 
* `GetConfig` should have a new params struct, the meaning of each of these should come from the current command line options:
```golang 
  type GetConfigParams struct {
    WithPrivateKey bool
    Format string
    Concise bool
}`
```
* `SetConfig` should take a full config object, which we can get via the API by unmarshaling into a fresh `&config.Config{}`. SetConfig's params should both be `*config.Config`, structs.

Neither of these functions need the normal pattern of being methods on a "Requests" struct, they can just be public functions in the core package. In both command line and the API, setting profile photo & posters should be "special", with the CLI using the current code to deal with files, and the API rejecting sets to those fields for now.

You'll know it's done when these two methods have mad dope tests, and the cli commands `Run` funcs get really, really simple.

**Comment by ramfox** [comment]
Okay cool.

Basically push the config get and set lower into the stack, and leave the more 'special', ie, requests with files, at the cli/api level. 

Think I get it for now, will reach out if I have more questions!!

**Comment by ramfox** [comment]
So is the signature of GetConfig:
`func GetConfig(*GetConfigParams) []byte, error`
?
Is there a benefit to using loadConfig as a prerun function if we are moving a bunch of stuff into core?
We could add cfgPath to the GetConfigParams, so we can load from the correct filepath when we LoadConfig from the GetConfig function.

It also seems like the specific field (like profile.name) should be added to the GetConfigParams, and if there is no specific field, then the full config is returned.
```
type GetConfigParams struct {
    WithPrivateKey bool
    Format string
    Concise bool
    CfgPath string
    Field string
}
```

GetConfig would then return a slice of bytes, either in json, formatted json, or yaml

Thoughts?

**Comment by b5** [comment]
For func signatures, I think we should have `GetConfig` & `Setconfig` follow the [net/rpc function signature](https://godoc.org/net/rpc), so it would be:
```golang
// GetConfig returns current configuration details
func GetConfig(p *GetConfigParams, res *[]byte) error

// SetConfig updates configuration settings
func SetConfig(p, res *config.Config) error
```

As for loadConfig, which I assuming you mean is the `cmd` package loadConfig(), it's called at very specific times, and not others because it errors if loadConfig fails (which is a problem for commands like `setup` which _shouldn't_ have a configuration to start with). So for now I think we should leave it where it is, but I'd appreciate a separate issue on the topic so we can suss out a better story around loading configuration!

Helpful?

**Comment by ramfox** [comment]
Cool on the function signatures

Re loadConfig:
Yes, I'm just trying to figure out when we could call something similar to loadConfig in the api

I guess I don't understand why we wouldn't just call the core.LoadConfig function in the GetConfig or SetConfig core functions

**Comment by ramfox** [comment]
Okay per our conversation IRL, we should add to the config package:

```
func (cfg *Config) WithoutPrivateValues() *Config

func (cfg *Config) WithPrivateValues(*Config) *Config
```

To make sure when we are setting and getting config, we aren't returning or overriding the fields we want to keep private, or shouldn't override.

This feels like we should have a `WithoutPrivateValues` and `WithPrivateValues` for each of the structs within config. That way we can just call each of them to copy over what they should at the top, (the same structure of how we used Assign, except this time we aren't overriding anything, just copying)

**Comment by b5** [comment]
perf. It'll be pretty "basic" for many of those sub-structs. to be safe let's have each function return a fresh copy of the receiver so others can mutate the returned `*Config` safely

**Comment by ramfox** [comment]
Okay, after another convo, this is the route we are going:

Each struct inside the config.Config will have a Copy() function that returns a deep copy of that struct.

Only *Config will have a WithPrivateValues and WithoutPrivateValues that returns a new *Config that either has or does not have the private values.

hollerrrrr
