### ISSUE TITLE
Taxonomy / Hierarchy for Dataset Properties

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/qri#396]
A valuable asset would be a layer of tables that help track taxonomic relationships held within the dataset. This should facilitate dataset comparisons / linking. 

**Examples:**
  - Duchess, Orange, and Suffolk are all contained in a list of counties in the state of New York. Knowing this dataset is contained and organized as such within a dataset would allow someone else doing county-based analysis to collaborate
  - Green, Red and Yellow are all contained in a list of colors
  - Others: which cities are contained in which states?, which zip codes are contained in which cities (or vice versa)?,

**Comment by b5** [comment]
This should be further developed with a forthcoming rfc over at qri-io/rfcs. closing
