### ISSUE TITLE
(feature proposal) dataset add using multiple documents in single yaml file

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#411]
this might be unnecessary or redundant, but if we are adding files from yaml, would be nice to support multiple 'documents' per file.  I believe this is an official part of the yaml 2.0 spec, though unclear if available out of the box with the standard golang yaml package.  Looks like kubernetes achieves this functionality via their [`splitYAMLDocument ` function](https://github.com/kubernetes/kubernetes/blob/f3942e7dedc0781aaee0a8dec1e134748b705ae2/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go#L138-L169)

**Comment by b5** [comment]
I'm going to close this due to age. Maybe we'll revisit at a later date
