### ISSUE TITLE
Repos without meta.json do not display stats from structure.json

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#419]
I somehow ended up creating some datasets that do not contain meta.json files, either by running commands with incomplete names ("test_repo" instead of "me/test_repo"), or while developing transformation code.

While these datasets have structure.json files in them, the command "qri list" does not properly display the contents of the structure (size in bytes, number of entries, number of errors):

![screen shot 2018-05-30 at 10 40 35 am](https://user-images.githubusercontent.com/2515490/40728046-3ece6fc0-63f7-11e8-888b-79d8f147db8f.png)

**Comment by b5** [comment]
Not creating meta when none is provide is def the behaviour we want. Making sure none of our code assumes meta exists is the tough bit 😃. 

This was closed by #423.
