### ISSUE TITLE
`qri export` should give the option to export as yaml or json

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#425]
Our new `qri add --file=dataset.yaml` and `qri export --blank` both use .yaml files
However, when we export structure or meta from qri (`qri export --structure`) it exports as json. This makes it harder for the user to use a structure from different but similarly formatted dataset on a new dataset.

Let's add a `--format` flag that allows you to export as either yaml or json

**Comment by ramfox** [comment]
Hmmmm, so i assume also that in the future we want to have the option of exporting the body as cvs or json or whatever. this format flag will also need a name.

Feels to me the dataset/structure/meta format flag should be `--format`
and the data/body format flag should be `--body-format` and/or `--data-format`

**Comment by b5** [comment]
agreed. I vote for `--body-format`, the other thing we'll need to think about is when to export the body as a separate file, and when to just inline the body. I think the default should be to export the body as a separate file. `--inline-body` might make a nice flag to override.

**Comment by ramfox** [comment]
Hmm, so the `--zip` flag calls to `dsutil.WriteZipArchive`, which takes the structure, dataset, and data and zips that. The data is in whatever format it was put into qri. The structure and dataset are both json files. Notice that there is no separate meta file.

I feel like you should be able choose what goes into the zip file and what format they are in

Food for thought, not attempting this rn
