### ISSUE TITLE
Bug: Non human readable output when we connect to the registry.

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#448]
https://github.com/qri-io/qri/blob/5e54b5a344314470ee632d86271bb0353b1989ab/cmd/repo.go#L276-L280

Line 279 `printInfo("%v, rc)` is giving us not human readable output:
```
&{0xc4207ef820 0xc420270ba0}
```

@b5 Are we supposed to have output here, and if so, what should it say?

**Comment by b5** [comment]
this should be fixed!
