### ISSUE TITLE
Add tests for `Complete` and `Run` functions for all qri cmd

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#466]
First, create a TestFactory struct that satisfies the Factory interface

This TestFactory should have an in memory test repo, aaaand what else?

TestFactory should have all the functionality necessary for running all cmd tests

Listing all commands right now, but might not get to all of them:
* [ ] add
* [ ] body
* [ ] config
* [ ] connect
* [ ] diff
* [ ] export
* [ ] factory
* [ ] get
* [ ] info 
* [ ] list 
* [ ] log 
* [ ] peers 
* [ ] print 
* [ ] registry 
* [x] remove 
* [x] rename `complete` `validate`
* [x] rename `run`
* [x] render `complete` `validate`
* [x] render `run` (need to have noPrompt set)
* [x] save `complete` `validate`
* [x] save `run`
* [x] search `complete` `validate`
* [x] search `run` (Need to add a registry client to the TestFactory before we can test properly.)
* [x] setup 
* [x] use 
* [x] validate

**Comment by b5** [comment]
Yes! Apologies for taking a while to get to this, but after reviewing #468, it's clear that a nice version of that would be to do exactly what you're saying & validate arguments in the `Complete` method, and write a nice message to the user in `ValidateOptions.IOStreams.Err` when validation fails, just before returning an error that's more execution-focused:

```golang

// ErrBadArgs is the generic error for bad user input
var ErrBadArgs = errors.New("bad arguments provided")

// ...

func (o *ValidationOptions) Complete(f Factory, args []string) error {
  // ...
  if len(args) == 0 {
    printErr(o.Err, "hey, you need to provide a dataset name or a supply the --data and --schema flags with file paths")
    return ErrBadArgs
  } 
}
```

**Comment by ramfox** [comment]
@b5 question:
So for `qri search`, the minimum args is set to 1, so we are assured that our `Complete` function can reach slice args[0] without cause any errors.

It feels... wrong not to guard against that in the function itself.

But if we guard against it, it means that we won't get an error if someone changes minimum args to 0 for some reason. Nothing will error, but all of a sudden our output to users will change, but all our tests will pass as if nothing changed.

Also, we don't use the convention of `qri command` with no arguments shows the help message on any other commands. But maybe we should? 

Anyway, not sure what the best thing to do is, could use some guidance. Thanks!!!

**Comment by b5** [comment]
Agreed. I think we need would to pick a lane between doing all argument
handling in complete vs using built-in cobra “minArgs” and stuff. We could
go all-in on cobra and supply custom validation functions to the Args
field, but since we’ve already set up a nice area for ourselves with
“Complete”, it means we can change out our commander later if needed. So
let’s start to move away from the cobra Args field. Sound good?
