### ISSUE TITLE
Bring API functionality closer to the command line

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#474]
We want the frontend to have the same functionality as the command line, or at least, as close as possible. 
To do that, we first need to update the API!

Here are the commands that don't have API endpoint counterparts:
* config (although we have the `/profile` endpoint that changes the profile config)
* registry
* search
* validate
* version

I propose we start with:
### Registry
We need this so we can publish and unpublish.
`/registry/publish`
`/registry/unpublish`
`/registry/check`
or should it be
`/registry/` and then the payload says whether to publish, unpublish, or check status. This fits closer to our usual api patterns, so going to start with that
### Search
we had search up once, should check commits and see how it operated before
### Version
This is for a little UI detail that rico suggested, when qri loads, it should show what version you are using. Perhaps this should also exist somewhere else on the app, as a reference

**Comment by b5** [comment]
A few Quick Notes:
* glad you're chasing registry :)
* search is definitely a higher priority.
* Config is one place where we'll probably end up deviating a bunch. I'd hold off on that for now until we have time to have a proper conversation about how altering configuration will work.
* `version` might be nice to have, but isn't really a high priority right now, and I'd rather see version info baked into a 200 response from the `/status` endpoint.
* I don't know about you, but I don't see an immideate need for `validate` over the API right this second

**Comment by ramfox** [comment]
Okay, done with `search`, and `registry` publish and unpublish

Since I know that we will need a 'check to see if this is published' option on the frontend, still want to spend time working out the registry dataset status bug

then will add these to the api integration test
