### ISSUE TITLE
meta issue to write an issue about frame.py

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#49]
https://github.com/pandas-dev/pandas/blob/64c8a8d6fecacb796da8265ace870a4fcab98092/pandas/core/frame.py

make an issue outlining a side project for kasey/an engineer learning the qri codebase to get an understanding of the Pandas DataFrame implementation (represents 2D tabular data/functionally similar to SQL but with 'pythonic' and numpy-inspired syntax/data structures/conventions) and assess the interoperability of low level functions and data structures of the qri engine/ the difficulty or feasibility of making a python-to-golang wrapper or adapter.

**Comment by b5** [comment]
why replicate frame.py when you can just integrate directly with jupyter notebooks :)
