### ISSUE TITLE
Differences in CLI `add` and and `save`

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#498]
Issue to document the differences between using the `add` and `save` commands, the make the processes unintuitive:

* you can `add` a dataset when `qri connect` is running, but you can't `save` a dataset when `qri connect` is running
* you can `add` a dataset without specifying a dataset name in the command (if there exists a dataset name in the dataset file), but the same does not go for `save`

**Comment by dustmop** [comment]
I added a (large) issue at https://github.com/qri-io/notes/issues/3 which does into more depth of the similarities and differences between `add` and `save`.

**Comment by ramfox** [comment]
The qri RFC also addresses these differences in [0012-CLI-commands.md](https://github.com/qri-io/rfcs/blob/master/text/0012-CLI-commands.md)
