### ISSUE TITLE
qri peers vs qri list inconsistency

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#503]
`qri list` shows all datasets in my own repo, does not require a connection

`qri peers` shows peers that I can see when connected, requires connection

`qri list <peername>` shows the datasets owned by a peer, requires connection

Proposal: `qri peers list <peername>` should be the command to see the datasets owned by a peer, to make it obvious that it is an operation that requires a connection, since it involves other peers. `qri list <text>` should be an error or do something else.

**Comment by ramfox** [comment]
I'm into this change!!!

**Comment by b5** [comment]
ok let's make it so

**Comment by b5** [comment]
we ended up going with `qri list --peer [peername]`
