### ISSUE TITLE
should `qri new` publish by default?

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#513]
There may have been a discussion about this that came to the opposite conclusion, but `qri new` should publish by default, and the `publish` flag should be renamed `no-publish`

This is in favor of search being more robust, I can see people forgetting to `publish` and then being confused about why their dataset isn't coming back when they search for it, or having a bunch of datasets on the network that people can't find because the folks adding them didn't realize they had to `publish` in order for them to be searchable.

Thoughts?

**Comment by b5** [comment]
After playing with this, I *don't* think qri new should publish by default. I know initially we'd agreed on the opposite, but after spending time using qri I've come to two major reasons for this:
1. A lot of the datasets I make / work on are "practice" or unfinished work I don't want to announce to the world (yet).
2. I often work without an internet connection, which creates inconsistent behaviour in regard to publishing

In the offline example, `qri publish` running secretly in the background will fail in this context, which undermines the one upside of "always publish", which is being able to say "I ran new, it should be online". For these reasons, I think we should avoid publishing by default, and instead focus on building up a whole set of tutorials & flows around publication that's similar to `git push`.

**Comment by b5** [comment]
Just a quick note for the record, we've gone with _not_ publish-by-default. Through the RFC process we elected to [add a publish flag](https://github.com/qri-io/rfcs/blob/master/text/0012-CLI-commands.md#qri_new) that will allow users to run `qri new --publish ...` that will achieve publish-on-create behaviour.
