### ISSUE TITLE
Expand `qri use` to work on all commands that examine a dataset

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#515]
Right now `qri use` works only with the `qri get` command.

I propose that we expand that usage to work for:
* [x] log
* [x] body
* [x] diff
* [x] export
* [x] info
* [x] render
* [x] validate

I don't think this should extend to the `save` command.

At first glance, it seems that this would take two changes from each command:
1) allow 0 arguments and allow empty Refs to pass to the lib function that underlies each command
2) add the lib.DefaultSelectedRefs() function to each underlying lib command, if it doesn't already exist

**Comment by b5** [comment]
yep. I think we should have a gander with _all_ dem commands. Thinks like `diff` might create some weird situations. I like the approach you're taking. lib should check for a current selection & use that if one isn't provided. Be on the lookout for aligning input param structs to all work & look the same way while you're at it.

The thing I'd like to keep in mind with `qri use` is at any given point it should be possible to be "using" _many_ datasets. In a context where more than one dataset is in in use for a command that kinda seems like it should be with only one dataset, I'd love to come up with a return convention that replies with _multiple_ datasets. Changing the return values of lib functions should be a separate PR, let's land support for using selected datasets with lib functions & just, for example, taking the first selected ref when only one ref is supported.

pumped.

**Comment by ramfox** [comment]
Great. I'm going to add the `qri use` feature to the above commands, but for now only apply the command to the first ref in the `use` list, if there is more than one ref, for now.

And I'll begin thinking of a story around returning info on multiple refs, as well as the problems/challenges that occur with certain commands. (eg off the top of my head, for `qri render`, if there are multiple refs how do we deal with filename for output, should an --output flag be present)

**Comment by ramfox** [comment]
Okay, so diff is a weird case.

Diff requires two dataset refs.

if there are at least 2 datasets in the `use` list, the first dataset in the list will be the `left` and the second will be the `right`

if there are datasets in the `use` list,  and there is one dataset ref passed to the command, the one passed to the command will be the `right` dataset, the first ref on the `use` list will be the `left`

if there are two dataset refs passed in, we proceed as normal.

If there are not enough dataset refs, we return an error: "please provide two dataset references to compare"
