### ISSUE TITLE
Need to add `/transform` and `/viz` endpoints that return the content of a dataset's tranform and viz.

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#537]
We currently don't have a way to take a look at the transform or viz scripts. Let's open up an API endpoint that can do that.

First, there is an issue open: qri-io/dataset#144 that really should be addressed first.

We then need to create functions in the lib and api packages:

In lib:

If we don't want to lay the groundwork and write Dataset functions, we can always pull the files directly from the store in the lib package, like we do in the lib.Render function.

lib.LookupTransform => takes a LookupParams (contains a Path to the dataset) and returns a LookupResponse (returns scriptPath and slice of bytes of data)
lib.LookupViz => takes a LookupParams (contains a Path to the dataset) and returns a LookupResponse (returns scriptPath and slice of bytes of data)

In API:

`/transform/datasetRef`
`/viz/datasetRef`

returns a response with the Path and the Data. The Data is a json string. Need to make sure it is all escaped correctly before sending it off to the frontend.

Thoughts: 
do we need some kind of pagination? if so, what would that look like? Every 2000 characters? How would it get stored in a paginated way?

**Comment by b5** [comment]
@ramfox & I have talked this over a bunch decided to go in a different direction for the frontend. Given that the underlying API for these endpoints may change a bunch and we don't need this for the frontend, I'm going to close this for now. We can re-open in the future if a reason to revisit this comes up.
