### ISSUE TITLE
qri init interprets this incorrect flag as a valid name rather than throwing an error

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#55]
forgot the second dash on name and ran 
<code>qri init -f survey_cleaned.csv -m meta_survey_cleaned.json -name researchTools</code>
which named the dataset 'ame' from 'name' rather than telling me '-name' was an invalid flag

**Comment by b5** [comment]
yeah this is actually not a bug, but is consistent with [GNU posix](http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html). Our flag package is inherited from cobra, which is importing https://github.com/spf13/pflag
