### ISSUE TITLE
fix(read-only): edits to api read-only

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#577]
Changes to qri to get frontend read-only functionality to work:

* [ ] get requests on profile picture and profile poster should be allowed through
* [x] `lib.Info` function should add the `online` field to the profilePod before returning. (The `/peers` list endpoint calls to the `lib.Peers`, which calls `action.ListPeers`. `action.ListPeers` adds the `online` fields, which is why we get the correct online-ness when we are not in read-only mode: the frontend usually gets all its profile info from this `/peers` endpoint)
* [ ] perhaps allow GET requests  to the `/peers` endpoint, this depends on what our `read-only` frontend landing page is going to be

**Comment by b5** [comment]
I think this is closable. can you confirm @ramfox?
