### ISSUE TITLE
creating a new dataset using `qri save --file=file.yaml` is broken

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#587]
My merging of `new` and `save` broke the ability to create a new dataset using a --file=file.yaml or --file=file.json flag. The error is:
```
either dataBytes, bodyPath, or a transform is required to create a dataset
```

Which comes from actions/dataset.go. This file wasn't modified by the recent changes, and was working when `new` was calling it, so I'm not sure yet what `new` was doing differently to make this work.

**Comment by dustmop** [comment]
I'm dumb, this was totally working, but I was trying to use a dataset.yaml file that didn't have bodypath set. Glad this isn't broken, but maybe the error message could be better.

**Comment by b5** [comment]
you're not dumb. Let's make the error message better, ideally as part of an errors overhaul
