### ISSUE TITLE
recent p2p refactorings have broken p2p tests on my machine

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#588]
My machine is known to be finicky, it's true. But the recent refactoring of p2p have caused the unit tests to both fail in weird ways and also take a long time to finish. Here are some error messages:

```
--- FAIL: TestSharePeers (7.89s)
    qri_peers_test.go:47: peers took too long to connect
FAIL
FAIL	github.com/qri-io/qri/p2p	60.569s
```
```
[0 212> go test ./p2p/.
--- FAIL: TestNewNode (10.23s)
    node_test.go:31: could not determine host IP addresses for Dustins-MacBook-10.local.
FAIL
FAIL	github.com/qri-io/qri/p2p	32.701s
```

I'm going to try and bisect to see what change lead to this new behavior. I have a suspicion that something that used to be mocked is now using real networking code, which behaves unreliably in certain circumstances.

**Comment by b5** [comment]
Hmmm... this is odd. On my machine tests are still taking 1-2 seconds. Might be worth combing through for old dependencies, re-run `gx install` (which shouldn't make a difference but, you know, computers).

After that I think the place to start digging would be `QriNode.makeBasicHost`, we've made some small-but-critical changes there

**Comment by dustmop** [comment]
Hmmm, I can't reproduce now. Maybe something was running on my machine that was effecting my tests. Which is not as bad, though still not ideal. Could be totally unrelated to any recent code changes, though. Closing this for now, but I'll keep an eye on it.
