### ISSUE TITLE
`go get  github.com/qri-io/qri` fails

### ISSUE THREAD

**Issue by titaniumbones** [qri-io/qri#591]
on arch linux, relatively current everything. 

```
$ go version       
go version go1.11.1 linux/amd64
$  ipfs version
ipfs version 0.4.17
$  go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/matt/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/matt/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build993156681=/tmp/go-build -gno-record-gcc-switches"

```

installation of qri packages fails with: 
```
$ go get github.com/qri-io/qri
# github.com/qri-io/qri
gx/ipfs/QmaPHkZLbQQbvcyavn8q1GFHg6o6yeceyHFSJ3Pjf3p3TQ/go-crypto/blake2b.supportAVX2: relocation target runtime.support_avx2 not defined
```
Looks like there were some issues at one time with go-crypto earlier in the year, fixed by an upgrade elsewhere, e.g. [in this issue](https://github.com/golang/go/issues/25098#issuecomment-385484235)

Is this an upstream bug, and/or is it caused by some misconfiguration on my paanyway not urgent just messing around. rt?

**Comment by b5** [comment]
lots of things can go wrong with the raw `go get` thanks to gx. 

mind running the following to see if it helps?
```shell
cd $GOPATH/github.com/qri-io/qri
make update-qri-deps
make build
```

**Comment by titaniumbones** [comment]
Yes, this works! I guess this is the same as #512, so maybe I will close as a duplicate.

**Comment by b5** [comment]
go glad to hear that helps! I'll make a note that we should highlight these bits in our readme & docs

**Comment by titaniumbones** [comment]
qhile yr at it  document hte change form `qri new` to `qri save` !

**Comment by b5** [comment]
lol that's what you get for running tip! New release with documentation should happen this week 😄

**Comment by titaniumbones** [comment]
ha, thought I'd already closed this :-/
