### ISSUE TITLE
docs(README): Contributing links broken

### ISSUE THREAD

**Issue by machawk1** [qri-io/qri#614]
In the repo README.md, the `Contribute` and `Read the Contributing guides` links both point to the broken URI https://github.com/qri-io/qri/CONTRIBUTOR.md.

I believe that the intention is for them to link to the CONTRUBUTING.md file at https://github.com/qri-io/qri/blob/master/.github/CONTRIBUTING.md (and that it was moved from its previous location in the repo root) but was unsure if you wanted a hard-coded master branch link, hence no PR (yet!).

I will gladly submit a PR with the above revised link if it is correct but wanted to make you were aware of them being broken.

**Comment by b5** [comment]
thanks for spotting this @machawk1, PR would be very much welcomed. We're totally fine with a hard coded link 😄

**Comment by machawk1** [comment]
PR #615 submitted, @b5.

**Comment by b5** [comment]
Thanks so much @machawk1!
