### ISSUE TITLE
This repo's .github CONTRIBUTING should ref to contributing guide

### ISSUE THREAD

**Issue by Frijol** [qri-io/qri#619]
https://github.com/qri-io/qri/blob/master/.github/CONTRIBUTING.md (linked from Readme) currently doesn't link to the very specific contribution instructions that reside at https://github.com/qri-io/qri/blob/master/DEVELOPERS.md#commits, but should!

**Comment by ramfox** [comment]
Hi! 

This is such a good point :) Do you have any interest in creating a pull request to fix?

If not, I can take care of it.
