### ISSUE TITLE
`qri export` docs out of date in CLI quickstart

### ISSUE THREAD

**Issue by Frijol** [qri-io/qri#621]
http://qri.io/docs/tutorials/cli_quickstart/#1.6 at 1.6:

![screen shot 2018-11-20 at 4 19 50 pm](https://user-images.githubusercontent.com/454690/48810910-2e64fd80-ece0-11e8-9267-706791bab00e.png)

It refs to two docs, but there are three– needs to document `ref.txt`. Also mine came out `dataset.json` rather than documented `dataset.yaml`

![screen shot 2018-11-20 at 4 21 09 pm](https://user-images.githubusercontent.com/454690/48810941-56ecf780-ece0-11e8-9340-9beb65313b97.png)

**Comment by ramfox** [comment]
Great! Noted!
