### ISSUE TITLE
CLI quickstart `save --file` won't work after `remove` in current tutorial

### ISSUE THREAD

**Issue by Frijol** [qri-io/qri#622]
Following the CLI quickstart tutorial straight through, you'd do [2.1](http://qri.io/docs/tutorials/cli_quickstart/#2.1) and remove the sample `nalcs_standings` qri record.

If you follow this instruction, the 2.2 section won't work exactly as written. It looks like you need a body in order to save a dataset. Here's the output if I follow the instructions exactly (after removing the record in 2.1):

```sh
➜  try-qri qri save --file dataset.yaml me/nalcs_standings
datafile or dataset PreviousPath needed
```

but if I add a ref to the body/re-link body, it works fine:

```sh
➜  nalcs_standings qri save --file dataset.yaml me/nalcs_standings --body body.csv
dataset saved: frijol/nalcs_standings@QmXMbo6XWE7C46sgFq1TjTf5KTq74ufYnmhW5Y9VPbFCrx/ipfs/QmSgNLRJhSQJkBqwNAQ29VjAFKgQVgxJmsKUdQhUEuvE2Y
```

Could be a stumbling block for new users.

**Comment by ramfox** [comment]
Yep! Docs and tutorial are out of date. Thanks for the note.
