### ISSUE TITLE
deleting a dataset removes entire history, no way to delete a single commit

### ISSUE THREAD

**Issue by b5** [qri-io/qri#642]
Early users find this surprising in a bad way. I think we should fix this ASAP with the following changes to the way `delete` works:

* alter the default behavior of `qri delete me/dataset` to removing a single commit
* add a new flag `--all-versions` that deletes the entire dataset, so `qri delete --all-versions me/dataset` does what `qri delete` currently does.
* this is also true for the API, users would set an `all_versions=true` query param
* attempting to delete a dataset owned by a peer (`qri delete peer/dataset`) should `error: cannot edit history of datasets you don't own. to remove the dataset entirely, run qri delete --all-versions`

In subsequent PR's we should work out some param for deleting multiple commits at once (the Qri equivalent of `git reset --hard HEAD~n`), but let's tackle that in a separate PR.

PR that closes this needs to:
* have tests for both types of delete
* update the API
* update the CLI

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/662.
