### ISSUE TITLE
The previous schema always gets squashed by a generated schema, unless you include a schema

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#648]
I was adding tests to cmd/save, when I noticed that if you don't include the dataset.json file each time you `qri save`, the schema gets written over.

Sunk a bit of time looking for the root of the issue, but could't find the exact place. Going to just leave this issue as is for now and keep trucking on my other work.

**Comment by b5** [comment]
we _must_ have addressed this by now. closing due to age
