### ISSUE TITLE
Search should also return results from local datasets as well as from peers

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#65]

**Comment by nathantchan** [comment]
Does this mean that search currently doesn't search your local datasets? I just tried searching for a dataset I added and couldn't find anything...

**Comment by rgardaphe** [comment]
- Need ability to search WITHIN one's OWN datasets, a specific Peer's datasets and/or the whole qri network. 
 - Need ability to return search results that designate the following:
       - whether I created it
       - whether i currently have pinned it
       - eventually how new / trusted it is

Why? If i'm super into seaturtles, and I'm looking for a seaturtle dataset, if the top results are always mine, i'll be annoyed. If I found a seaturtle researcher's profile, I may want to search within her library of datasets only. I'd then want the ability to filter by creation date (age), and how many upvotes it has received.
