### ISSUE TITLE
bug when using `set_body` and csv

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#654]
Doing some testing on dumb data.

here is my body before, in csv format:

```
one	1
two	2
three	3
four	4
five	5
```

Here is my transform:

```
def transform(ds, ctx):
  bd = ds.get_body()
  ds.set_body(bd)
```

Just getting the body and setting the body back. And this is what the error message I'm getting:

`error reading values: error reading row 0: parse error on line 1, column 1: bare " in non-quoted-field`

It works fine if I the body is in json format. This could be a startf problem.

**Comment by b5** [comment]
This should now be fixed thanks to a number of improvements to both startf & csv handling
