### ISSUE TITLE
bug(base.localUpdate): transform that we just 'recalled' gets written over

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#657]
localUpdate is called by UpdateDataset. UpdateDataset, is called by lib.Update, which "recalls"
the last transform run, and adds that transform to the ref
However, once we get down here, that ref actually get's written over when we
call base.ReadDataset. Which means if our last dataset did not have a transform, when we called
Update, we will error.

probs simple solution: save the transform before `ReadDataset`, and then add the transform back, but want to make sure this is what we want/the best solution

**Comment by b5** [comment]
I think this was closed by our big refactor in #681!
