### ISSUE TITLE
How to configure IPFS command-line options?

### ISSUE THREAD

**Issue by camhunt** [qri-io/qri#658]
I'm setting up a public qri proxy, and I'd like it's IPFS node to support additional duty (pub-sub, circuit relay, etc). Some of these options require command-line options when starting the IPFS daemon (ex: "--enable-pubsub-experiment"). Is there/can there be a way to configure this for qri (perhaps in config.yml)?

**Comment by b5** [comment]
Hi @camhunt. Currently the best way to alter the iPads config Qri uses is to use `ipfs config` subcommand from go-ipfs. You can also edit the config file in `$IPFS_PATH` directly (its a JSON file, just no Extension) if you don’t have the ipfs binary around

**Comment by camhunt** [comment]
I'm good with editing the ipfs config command, but I still think there is a requirement to pass a flag to the ipfs daemon on start for some experimental features.

**Comment by b5** [comment]
So I took a look at this, and you're absolutely correct on the pubsub thing (in the sense that it didn't "work" with qri). I ended up making a few changes geared at your use-case that have shipped in our latest patch release. You can find instructions for doing pubsub with qri running here: https://github.com/qri-io/qri/pull/672#issue-246606054

Hope that helps!
