### ISSUE TITLE
print.go needs typed vars

### ISSUE THREAD

**Issue by camhunt** [qri-io/qri#659]
Attempting to build on armv7l device (Android phone via Termux). Getting these types of errors:

`cmd/print.go:82:9: constant 1152921504606846976 overflows int`

Quick search brings back the (apparent) need to type the vars, as referenced in [this](http://golangcookbook.blogspot.com/2012/12/error-constant-overflows-int.html) article.

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/666.
