### ISSUE TITLE
JSON Validation

### ISSUE THREAD

**Issue by WaughB** [qri-io/qri#660]
Given an invalid JSON file (data.json):
```bash
{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : X, "pressure_kPa" : 252.340, "temperature_C" : 16.000, "maybe_battery" : 1, "mic" : "CHECKSUM"}
{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : 2, "pressure_kPa" : 252.340, "temperature_C" : 16.000, "maybe_battery" : 1, "mic" : "CHECKSUM"}
{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : 3, "pressure_kPa" : 252.340, "temperature_C" : 16.000, "maybe_battery" : 1, "mic" : "CHECKSUM"}
{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : 0, "pressure_kPa" : 252.340, "temperature_C" : 16.000, "maybe_battery" : 1, "mic" : "CHECKSUM"}
{"time" : "2019-01-14 06:43:46", "model" : "XXXXXX", "type" : "XXXXXX", "flags" : "XX", "id" : "XXXXXX", "pressure_bar" : 1.750, "temperature_C" : 17.000, "mic" : "CRC"}
{"time" : "2019-01-14 06:43:47", "model" : "XXXXXX", "type" : "XXXXXX", "flags" : "XX", "id" : "XXXXXX", "pressure_bar" : 1.750, "temperature_C" : 17.000, "mic" : "CRC"}
{"time" : "2019-01-14 07:31:16", "model" : "XXXXXX", "type" : "XXXXXX", "flags" : "XX", "id" : "XXXXXX", "pressure_bar" : 2.225, "temperature_F" : 77.000, "mic" : "CHECKSUM"}
```
I ran `qri validate --body data.json` and it returned `✔ All good!`
After validating, I ran `qri save --body data.json me/test_json` and it never moved past the progress box. I tried this on two machines running Qri. The first one I stopped after ten minutes, and the second one I stopped at twenty minutes. 

Correcting the file to:
```bash
[{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : X, "pressure_kPa" : 252.340, "temperature_C" : 16.000,"maybe_battery" : 1, "mic" : "CHECKSUM"},
{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : 2, "pressure_kPa" : 252.340, "temperature_C" : 16.000, "maybe_battery" : 1, "mic" : "CHECKSUM"},
{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : 3, "pressure_kPa" : 252.340, "temperature_C" : 16.000, "maybe_battery" : 1, "mic" : "CHECKSUM"},
{"time" : "2019-01-14 02:11:23", "model" : "XXXXXX", "type" : "XXXXXX", "state" : "XX", "id" : "XXXXXX", "flags" : 8, "repeat" : 0, "pressure_kPa" : 252.340, "temperature_C" : 16.000, "maybe_battery" : 1, "mic" : "CHECKSUM"},
{"time" : "2019-01-14 06:43:46", "model" : "XXXXXX", "type" : "XXXXXX", "flags" : "XX", "id" : "XXXXXX", "pressure_bar" : 1.750, "temperature_C" : 17.000, "mic" : "CRC"},
{"time" : "2019-01-14 06:43:47", "model" : "XXXXXX", "type" : "XXXXXX", "flags" : "XX", "id" : "XXXXXX", "pressure_bar" : 1.750, "temperature_C" : 17.000, "mic" : "CRC"},
{"time" : "2019-01-14 07:31:16", "model" : "XXXXXX", "type" : "XXXXXX", "flags" : "XX", "id" : "XXXXXX", "pressure_bar" : 2.225, "temperature_F" : 77.000, "mic" : "CHECKSUM"}]
```
Resolved the issue and the `qri save` worked almost immediately.

**Comment by dustmop** [comment]
I can't reproduce with the first data.json file you posted. I get `error reading values: error reading row 7: Expected: separator ','`.

I noticed the first line has no comma between `temperature_C` and `maybe_battery`:
`"temperature_C" : 16.000 "maybe_battery" : 1,`

Was this also missing in the file you were using, or was it a redaction error?

**Comment by WaughB** [comment]
I forgot the comma when posting. I'll add that back in now.

**Comment by dustmop** [comment]
Ah, also the first line has `"repeat" : X`, which doesn't parse. But after fixing that, `qri save --body=data.json me/test_json` works immediately for me (sort of, it only processes the first row, but it doesn't hang). Could you double check that you have a minimal example that still exhibits this problematic behavior? It's possible that during redaction, something is changed that routes about the bug that causes the hang.

**Comment by dustmop** [comment]
Was sent a reproduction case by @WaughB out of band. From digging into it, so far I've found that the problem is in `prepareDataset` in dataset/dsfs/dataset.go. The goroutines `setErrCount` and `setDepthAndEntryCount` both complete quickly, but the `setChecksumAndStats` seems to block completely at the start during its call to io.Copy. I don't completely understand what this code is doing, so I'm going to come back later and try again.

**Comment by dustmop** [comment]
One more thing I should mention: the reproduction case does exhibit the issue implied above: it's not a single json object, but rather a text file containing a json object per row. The file is only 188 lines and 38672 bytes, not huge by any means. Fixing it to be a single json object, by adding "[]" outside and "," at the end of each line fixes the issue.

My initial guess is that `setErrCount` and `setDepthAndEntryCount` are both using entry readers, and so only read the first row then complete quickly, while `setChecksumAndStats` is using a buffer reader, so it's processing the whole file. Maybe there's a hidden race condition or deadlock being triggered by this difference in runtime characteristics?
