### ISSUE TITLE
qri publish vs qri registry publish

### ISSUE THREAD

**Issue by camhunt** [qri-io/qri#668]
Curious about the difference. On arm64 platform (RockPro64 w/ 2GB RAM), the `qri publish` command just seemed to hang. `qri registry publish` worked like a charm.

**Comment by ramfox** [comment]
Qri publish does three things:

1) sets your dataset as `listed` to peers that are connected to you
2) publishes your dataset to the registry
3) backs up (pins) your data to an always-on ipfs node

`qri registry publish` just does the 2nd thing.

This implies that either it's hanging when changing your dataset to listed, which is very unlikely, or more likely, it is taking a bit of time backing up/pinning your dataset to an always-on ipfs node. This time fluctuates depending on the health of the ipfs network at the time of running the `publish` command.

**Comment by b5** [comment]
I think we found the source of your bug @camhunt. a bug in our registry polling was causing `qri publish` to hang. now fixed if you're pulling from master, it'll land formally in qri 0.7.1. https://github.com/qri-io/registry/pull/26

the reason `qri registry publish` may have worked but `qri publish` didn't might come from running the commands in succession, the first one may have actually worked (pinning the data), but your local client would have been deadlocked and unable to say as much. With that version now pinned, the second attempt wouldn't have required polling at all, so you wouldn't hit the deadlock on the second `qri registry publish`.

I'm going to close this, but let us know if you run into any other issues with `qri publish`. Thanks!
