### ISSUE TITLE
add flags to `qri save` for setting individual components of a save

### ISSUE THREAD

**Issue by b5** [qri-io/qri#690]
I'm having a semi-frustrating time always having to create a `dataset.yaml` or `dataset.json` just to update a transform script. What I'd like to be able to do from the CLI is one of two things. The first would be providing json/yaml snippits for each component. In each of these cases the `_file` argument would be a file that _only defines that component_, not an entire dataset:
```
$ qri save --meta meta_file.json me/dataset
$ qri save --structure structure_file.json me/dataset

$ qri save --viz viz_file.yaml me/dataset
$ qri save --transform transform_file.json me/dataset

# we already support this:
$ qri save --body file.csv me/dataset
```

The second would be providing a raw script as a file as a shortcut for "default settings, but with this file":
`qri save --transform tf_file.star me/dataset`
ditto for viz scripts:
`qri save --viz template_file.html me/dataset`
This would just do the right thing, populating a component with defaults (like setting `syntax` to `html` or `starlark`) and setting the `scriptPath` to the supplied path argument

In a later PR it'd be great to leverage the `qri` values we embed into datasets to intelligently accept a dataset.json definition, but if passed to a specific component argument, we would traverse to and only use that component of the supplied dataset. For example this:
```
qri save --meta other_dataset.json me/dataset
```
would be the same as saying "I've exported some other dataset as `other_dataset.json`, please copy it's `meta` component onto `me/dataset`. This is future work. For now it'd be great if we errored if you passed a file that had `"qri": "ds"` in the top level to any component argument

**Comment by dustmop** [comment]
I'm not a huge of having a flag for each component, leads to too many flags that are similar things but are also mutually exclusive. I would prefer `--component <component_name>`. Both --file and --body are somewhat special in how they work, for example, either can be used to create a new dataset, while --component couldn't be.

**Comment by b5** [comment]
In the alternative you're outlining I would do `qri save --component structure --file st_file.json`? Just making sure.

Agreed on the many/too many flags issue. I want to make sure I understand the alternative, but for I can see this adding up to overloading the `--file` flag a whole bunch instead of flags for each component:
```
# do what I was mentioning above, inferring this is a default transform
$ qri save --file transform.star me/dataset

# skip the whole --component thing, instead let users specify components with "qri" : "st" top level values
$ qri save --file component_file.json me/dataset
```

This would have a few implications:
* data, script, and viz file extensions would need to be mutually exclusive
* can't compose multiple components from different source files in a single `save` invocation (b/c no moar flag slots)

What about dropping the `--component` business altogether, and just loading up `--file` with new tricks? After working with Qri a bunch I really just want this flow of applying stuff from one dataset to another, which overloading the `--file` flag would satisfy:
```
$ qri get transform.script me/dataset_a > transform.star
$ qri save --file transform.star me/dataset_b
```

I like this approach more b/c all I have to think about is the `--file` flag, no more bending the mental model around which flag to use when.

Toughts? cc @camhunt

**Comment by dustmop** [comment]
> In the alternative you're outlining I would do `qri save --component structure --file st_file.json`?

Yes, this was the possibility I was thinking of.

> What about dropping the `--component` business altogether, and just loading up `--file` with new tricks?

I think this is an even better idea. Also, we can allow changing multiple components by passing multiple `--flag` values:

`qri save --file change_meta.json --file change_structure.json me/my_dataset`

To do this we would change `--file` to use a StringSliceVar: https://godoc.org/github.com/spf13/pflag#StringSliceVar

**Comment by b5** [comment]
so looks like we only have to get the multiple `--file` flags working to close this out. We've also added `.star` -> transform with a scriptPath and `.html` -> viz with a scriptPath.

**Comment by dustmop** [comment]
This is working now, closing this issue.
