### ISSUE TITLE
Problem with starlib/xlsx and dataset/dsio - Manjaro with Go 1.12

### ISSUE THREAD

**Issue by wblondel** [qri-io/qri#716]
Hi,

I can't build qri on Manjaro with Go 1.12 (go version go1.12 linux/amd64).

First, when I do `go get github.com/qri-io/qri`, I have these errors:
```
# github.com/qri-io/starlib/xlsx
qri-io/starlib/xlsx/xlsx.go:96:8: assignment mismatch: 1 variable but f.xlsx.GetRows returns 2 values
# github.com/qri-io/dataset/dsio
qri-io/dataset/dsio/xslx.go:70:23: too many arguments in call to r.decode
	have ([]string, error)
	want ([]string)
```

Then, when I `make build`, I have these errors:
```
\n4/5 install gx dep-packages:\n
go get github.com/qri-io/registry/regclient github.com/qri-io/dag github.com/qri-io/qfs github.com/qri-io/startf
# github.com/qri-io/dataset/dsio
../dataset/dsio/xslx.go:70:23: too many arguments in call to r.decode
	have ([]string, error)
	want ([]string)
# github.com/qri-io/starlib/xlsx
../starlib/xlsx/xlsx.go:96:8: assignment mismatch: 1 variable but f.xlsx.GetRows returns 2 values
make: *** [Makefile:48: build] Error 2
```

How can I solve this? I don't know what to do.

Thanks!

**Comment by b5** [comment]
Hi @wblondel, thanks so much for filing! 
`make build` is definitely the way to go (regular `go install` isn't expected to work).

It looks like one of our downstream dependencies changed their API. I'm working on a fix, and will update here.

**Comment by b5** [comment]
ooook, just merged two commits that should address the issue. Would you mind running two commands for me? `make update-qri-deps` followed by `make build`

**Comment by wblondel** [comment]
Success! It works :+1: Great job :)

**Comment by b5** [comment]
Great! Thanks for the heads up, I'll close this
