### ISSUE TITLE
Starlark repo link broken in docs

### ISSUE THREAD

**Issue by viksit** [qri-io/qri#717]
- Go to https://qri.io/docs/tutorials/starlark_transformations/
- "Qri (“query”) is about datasets. A transformation is a repeatable script for generating a dataset. Starlark." -> Links to https://github.com/google/starlark/blob/master/doc/spec.md
- should be https://github.com/bazelbuild/starlark/blob/master/spec.md

**Comment by b5** [comment]
Thanks so much for the heads up! We'll get to a patch in the next day or two!

**Comment by dustmop** [comment]
Since this issue was filled, https://qri.io/docs/tutorials/starlark_transformations/ moved to https://qri.io/docs/reference/starlark_syntax/. Out of date link fixed by https://github.com/qri-io/website/pull/115.
