### ISSUE TITLE
extraneous quotes error

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#72]
Not sure if this is necessarily a 'bug' but possibly something that will cause issues for some users if they use the same libraries I do:
- across a couple different python csv writer tools, the csv writers have various quoting options. Two of them are:
  - 'QUOTE_MINIMAL' - instructs writer objects to only quote those fields which contain special characters such as delimiter, quotechar or any of the characters in lineterminator.
  - 'QUOTE_NONNUMERIC' - Instructs writer objects to quote all non-numeric fields

while the second one seems like the more sensible default (and is the one qri expects), QUOTE_MINIMAL is the default setting and if a csv is encoded this way, will throw an error when trying to run qri init

**Comment by b5** [comment]
closing due to age
