### ISSUE TITLE
Error message when trying to diff from CLI

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/qri#738]
Using v. 0.7.3 on a mac, I tried to diff 2 versions of a local dataset and received this error message: 

`gob: type mismatch: no fields matched compiling decoder for DiffParams`

Here was the command I tried.
```
$ qri diff me/MLB_AllTime_HR_Leaders@/ipfs/Qmdorvwh7mejCuguCDfgAvEd2YBMBwF2kxF2MadbgQ7u31 me/MLB_AllTime_HR_Leaders
```

I also tried running the command without any inputs. 
```
$ qri diff
```
I got the same error message.

**Comment by b5** [comment]
ooooooh interesting. Are you running Qri elsewhere? Mind quitting any Qri electron app or terminals running `qri connect` and trying again?

**Comment by ramfox** [comment]
> ooooooh interesting. Are you running Qri elsewhere? Mind quitting any Qri electron app or terminals running `qri connect` and trying again?

Yep, this did it, thank you!!!
