### ISSUE TITLE
(possible bug?) unable to get this join query to work

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#75]
```sql
SELECT
    a.india as injured_by_tsunami,
    b.india as killed_by_tsunami 
FROM
    Environment_10 as a   
LEFT JOIN
    Environment_11 as b   
        ON     a.index = b.index
```
Environment_10:
<pre>/ipfs/QmPgUfwuSkbNcczqe84M9xmgq51k5gyFC8yCFJb4sQnE35/dataset.json</pre>
Environment_11:
<pre>/ipfs/QmbyLstHcqh6k4dMpQDMAVUsoZi2pmDX7jzWUqzmthkzJe/dataset.json</pre>

it gives the error message: 'unrecognized reference: a.india'

**Comment by b5** [comment]
ok so we're no longer about SQL, closing.
