### ISSUE TITLE
Clarity for windows build docs

### ISSUE THREAD

**Issue by AdroitProgrammer** [qri-io/qri#775]
Can you add a line instructing you to run PATH=$PATH:/c/Go/bin after the download of Msys2 "add go to path" part of your docs. It sets the path through the msys2

**Comment by dustmop** [comment]
Note to self: also add a link to the go "workspace" documentation, and add screenshots to make setup on Windows easier. In addition, using "go get" to retrieve the main `qri` repo instead of "git clone" leads to a sub-optimal experience, it takes a lot longer and spews lots of gx related errors.

**Comment by dustmop** [comment]
Windows documentation has been much improved, to include lots more detail about how to build from source.
