### ISSUE TITLE
round of feedback & fixes from recent dogfooding session

### ISSUE THREAD

**Issue by b5** [qri-io/qri#806]
I recently went through a dogfooding session creating an annotated bibliography with Qri, and ran into a number of small-ish fixes that would make using Qri much better.

My Checklist:
* [x] `qri save` with `structure.strict: true` needs to present validation errors when saving
   currently the error just says "invalid body" or something. it should show the errors right then & there for fixing.
* [x] need a flag to pretty-print a JSON body for editing
* [x] `qri save` with transform secrets confirmation request is writing to `stdout`, should write to `stderr`.  This is a _big_ problem when you run `qri save --dry-run > outpu.json`, because output goes to the file, so it looks like the process is just hanging forever, when it's really just waiting for you to feed `enter` to stdin
* [ ] should generally audit everything in the save path for writes to out & error, separating them properly.
* [x] qri publish --unpublish is missing return character after "unpinning dataset", so the next thing just clobbers onto the same line

**Comment by dustmop** [comment]
Merged #807 to handle "need a flag to pretty-print a JSON body for editing".

**Comment by b5** [comment]
#810 took care of "qri publish --unpublish is missing return character..."

**Comment by dustmop** [comment]
First item ("qri save with structure.strict: true") fixed by https://github.com/qri-io/dataset/pull/199.

**Comment by dustmop** [comment]
Marking this as closed, as we've improved the situation a lot, though monitoring stdout and stderr usage will probably never go completely away.
