### ISSUE TITLE
dry-run save transform while connected produces error

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#813]
Discovered by myself and @ramfox late last week, together we tracked down the problem to being connected and then running:
`qri save --file=code.star me/my_dataset --dry-run`

Gives the error:
`reading body EOF`

Running the same while not connected works okay.

**Comment by Arqu** [comment]
This still hangs, issue was introduced here: https://github.com/qri-io/dataset/pull/169
In `dataset.go` the struct `Dataset` has  a field `bodyFile qfs.File` which isn't serializable. Quite possibly `Body interface{}` is problematic as well as `net/rpc` doesn't generally handle vague interfaces well.

A similar issue was tracked here: https://github.com/qri-io/qri/issues/1193 and it's respective PR https://github.com/qri-io/qri/pull/1226

**Comment by Arqu** [comment]
Similar issue here: https://github.com/qri-io/qri/blob/master/lib/update.go#L73

**Comment by dustmop** [comment]
Removing `qfs.File` is not an option, it's pretty ingrained in our code. Instead, we should see if there's a way to make this work by using `gob.Register`, like in the `init` function in `lib/lib.go`.

**Comment by Arqu** [comment]
Yes, and the other alternative being going to our `Pod (Plain Old Data)` objects.

**Comment by b5** [comment]
yet another alternative: use the JSON API in these cases, which has none of these problems.

**Comment by Arqu** [comment]
I generally tried to avoid having a converter from RPC to API calls, or at least do it separately. 
But yeah that would solve this.

**Comment by Arqu** [comment]
Turns out, qfs.File is fine, it was the `json.RawMessage` from the `p.ReturnBody` as that actually abstracts the response from the raw `DatasetRef` and we don't have to deal with qfs at all.
