### ISSUE TITLE
improvements needed for further FSI integration

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#837]
- [x] `qri save` needs an api endpoint for the desktop app
- [x] `qri status` doesn't work correctly over api. it always uses the most recent version, apparently dropping the reference's path
- [x] running `qri save` while connected does not work the same as not connected. the meta.json file adds a field "keywords: []", which causes `qri status` to report a difference
- [ ] in fsi.ReadDir, we should use fill.Struct instead of Decode'ing the component files. If fill.Struct detects an error, this should be tagged as a new "name_error" instead of "parse_error".
- [ ] need some sort of command for reverting a working directory back to the head. maybe `qri revert` or `qri reset` or `qri undo`.

**Comment by ramfox** [comment]
also requesting:

* on init, be able to pass in an existing data file to use as the body, even if it's just on the api right now. This is to prepare for the case where a user wants to drop in a file onto the desktop app and expects qri to create a new dataset for them

**Comment by dustmop** [comment]
> on init, be able to pass in an existing data file to use as the body

We should discuss this further, but I feel like the solution for drag-and-dropping a file should not be `init`, but instead `save` followed by an optional `checkout`.

**Comment by b5** [comment]
the 5th point in the list is already being discussed at length in #861, so I'll consider that addressed here. I've created #874 to track point #4 so we can close this.
