### ISSUE TITLE
User can send a a filepath to init, init will copy the file to the working directory

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#839]
Prerequisite for https://github.com/qri-io/desktop/issues/29

`qri init` should take a flag so the user can specify a file path to a csv that they would like to turn into a qri dataset.

Qri should:
- copy the file to the working directory
- rename it to `body.[extension]`
- validate it (try to read the csv/json, if it's not in a good enough state to be committed as-is, throw an error)

**Comment by b5** [comment]
closed by #910
