### ISSUE TITLE
bug: POSTs to `/profile` don't save once you've closed `qri connect`

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#849]
- `qri connect` is running
- POSTing to the `/profile` endpoint to try to change the peername:
<img width="1023" alt="Screen Shot 2019-07-29 at 2 43 02 PM" src="https://user-images.githubusercontent.com/17440142/62073764-5c0b2a80-b20f-11e9-8269-83049791d94a.png">

- curling that endpoint again show that the peername has changed:
<img width="1028" alt="Screen Shot 2019-07-29 at 2 45 29 PM" src="https://user-images.githubusercontent.com/17440142/62073917-ab515b00-b20f-11e9-9a98-1aed9366d86f.png">

- however, once `qri connect` has ended, and you try to look at the config to see if the peername is still different:
<img width="379" alt="Screen Shot 2019-07-29 at 2 43 10 PM" src="https://user-images.githubusercontent.com/17440142/62073957-c328df00-b20f-11e9-999e-30090bff1610.png">

It hasn't actually changed.

**Comment by dustmop** [comment]
Some additional context around problems with peernames changing: https://github.com/qri-io/desktop/issues/64#issuecomment-516068757. Not sure if that's related to this specific issue, but it's possible.

**Comment by ramfox** [comment]
Peername and the profile are super sticky, huh?

I'm pretty sure this specific issue is surrounding the config and how we handle saving the config when we are in daemon mode. 

Either: the `/profile` endpoint is changing the ephemeral config object that gets created when we serve the daemon, rather than both changing the ephemeral config object and also writing to the repo. Then, the ephemeral config object does not get saved so the changes are lost.

OR: the `/profile` endpoint is changing the config in the repo, and when we request the profile, we are reading from the repo. Then, when we disconnect the daemon, we save over the repo with the ephemeral config, so the changes are lost.

My money is on the former.
