### ISSUE TITLE
Refactor qri checkout for single components to "qri restore", add API endpoint to checkout a single file

### ISSUE THREAD

**Issue by b5** [qri-io/qri#880]
#867 makes nice inroads on being able to resurrect individual components of a dataset from history. We've talked internally and have agreed to go with @dustmop's _other_ original proposal of using _restore_ as the word for "resetting a single component".

We need this feature so the frontend can "reset" a component to it's prior commit state.

**Comment by dustmop** [comment]
Fixed by #867
