### ISSUE TITLE
invalid character 'd' looking for beginning of value

### ISSUE THREAD

**Issue by benmazzotta** [qri-io/qri#908]
Hi, I tried running the CLI quickstart on Linux Ubuntu 18.04. Every search command returns the same error code. 

`invalid character 'd' looking for beginning of value`

Any thoughts? Thanks in advance.

**Comment by b5** [comment]
Hi @benmazzotta! 

Apologies, we're currently in the process of transitioning our "registry" code, which powers search. It's going to be a minute before search is properly restored (we're aiming for Monday of next week)

**Comment by b5** [comment]
Hey Ben, We've shipped a bunch of fixes around search, and this should be much smoother if you run the following command:

```
qri config set registry.location https://registry.qri.cloud
```

after running that configuration update, search should work! You'll need to be sure `qri version` reports at least `v0.9.0`

Thanks!
