### ISSUE TITLE
Body response includes object instead of array for data key

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#944]
Requests to body are returning an object under the `data` key instead of the expected array.  This is causing pagination to break in desktop (https://github.com/qri-io/desktop/issues/282).

![Qri_Desktop](https://user-images.githubusercontent.com/1833820/65689795-c1c33980-e03b-11e9-825a-423ec516cacd.png)

**Comment by b5** [comment]
We decided this isn't a bug. Pagnation should be able to leverage the path of the response, which part of the raw lib.Get response data. Instead we shipped a fix on desktop
