### ISSUE TITLE
bug: when we init a dataset, we need a basic structure

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#953]
When we init a dataset, we should create a `structure.json` file with `formatConfig` options.

After looking through dataset, here are the possible options for formatConfig. We should create a structure using the specific options found in `dataset`:

csv: 
  HeaderRow
  VariadicFields
  LazyQuotes
  Separator

json:
  Pretty (this is not explicit in the implementation check out https://github.com/qri-io/dataset/blob/af14d7dff51ae79f78771b74efa5b494eafa4b5d/data_format_config.go#L128-L130) 

xlsx:
  SheetName

**Comment by dustmop** [comment]
Implemented over multiple steps, such as: https://github.com/qri-io/qri/pull/954, https://github.com/qri-io/qri/pull/960, https://github.com/qri-io/qri/pull/986.
