### ISSUE TITLE
refactor: Convert `Viz` to `Readme` (Qri Backend)

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#972]
`Viz` was always intended to be the place where users could summarize their findings, show charts, and detail their methodology. Because `Viz` is not surfaced to the desktop, and perhaps because of the phrase `Viz` itself, it is currently being usurped by `Meta.Description`. We want `Meta.Description` to be a summary of the dataset, not the place for users to add copious detail. 

To facilitate the `Viz` component as a place for `Readme`'s, let's allow and cater to markdown files when we save and render a `Viz`. Let's surface `Viz` in the fsi, but let's call it `readme.md`. Let's have the `/render/` endpoint (and `render` when we save) return an index.html that shows our formatted markdown.

Internally, let's keep the name `Viz` for now. Let's not remove html as an option (so readme.html will still function as viz.html), but let's suppliment `Viz` with format `md`. However, at the fsi layer we will spit out `readme.md` or `readme.html`, rather then `viz.md` or `viz.html`. Any advanced use case (eg, using `dataset.yaml`), we will assume you understand that `viz` and `readme` are the same for this refactoring.

That should probably be, for now, where we stop the conversion. If you are working using the qri command line, you will use `viz` in place of `readme`, for this refactor.

* [ ] add Viz to the fsi
* [ ] rename all output to fsi and recognize input to fsi to use `readme` rather then `viz`
* [ ] add format `md` to viz
* [ ] add rendering from md to html to render (no charting for now, just pure md)
* [ ] add tests to render, dataset, fsi to show markdown conversion is working and html functionality is the same

One main goal of this pr is to not introduce any breaking changes. However, this change needs to be documented in our release notes.

**Comment by chriswhong** [comment]
More notes from sprint planning:

Add Readme component

Ensure `qri render` command can be called on a readme and returns the expected compiled html

Ensure that potential malicious code is handled properly (script tags, etc)

Add readme to FSI
Should qri init create a template readme with # {datasetname} ?

Qri local API should handle requests for both raw and rendered readme
If structured similarly to body request, the call would look like: http://localhost:2503/readme/:username/:name?fsi=true

Should there be a query param for rendered=true ?

If the readme is larger than some threshold, render should return a warning message

Qri API should handle requests for updating readme (live editing) which should update the FSI linked file, similar to the way meta editing works  


Feature doc: https://docs.google.com/document/d/1LHvjRgSN9q_pFWZ_lBOUtjIhSO0-4M-Mxj8AeX9IcxU/edit#

**Comment by dustmop** [comment]
Mostly implemented by https://github.com/qri-io/qri/pull/974. Need to test the integration, and probably add more tests.
