### ISSUE TITLE
`qri diff` appears to be sorting CSV rows alphabetically instead of numerically

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/qri#975]
I have a pretty big CSV change (thousands of rows) and, while scrolling through the output of `qri diff`, I noticed some funky looking ordering:

```
# Snippet from the middle of `qri diff`
  5479:
    ~ 1: "98"
  548:
    ~ 1: "699"
  5480:
    ~ 1: "98"
  5481:
    ~ 1: "98"
```

I think (?) the first line of each is the row number, but they are clearly getting sorted alphabetically instead of numerically.

**Comment by b5** [comment]
Nice catch. This was fixed in https://github.com/qri-io/qri/commit/6d6abb279745810668bf40edfe3b4fc622c0d545 when we upgraded our deepdiff dependency.
