### ISSUE TITLE
The fsi command is not listed in the command-line help

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#982]
Running `qri` shows help about available commands, but does not list qri fsi. Relatedly, it might be worth breaking FSI commands out into their own section. This would move status, restore, checkout and init.

**Comment by b5** [comment]
From our [CLI Manual working document](https://docs.google.com/document/d/1-1FzdfEOJZueHYBmf07ImDpkn12JYBVu_3o0Vp4g-5E/edit?usp=sharing) we've thought about introducing a section in `qri --help` that lists working directory commands:

```
Working Directory Commands:
  init        	Initialize a dataset directory
  status      	Show status of working directory
  checkout   	Create a linked directory and write dataset files to that directory
  restore     	Return part or all of a dataset to a previous state
```

To address this we should adjust the default usage template to list out `group`: `fsi` from the cmd.Annotations field: https://github.com/qri-io/qri/blob/4de6dd8af715677e89ea04270d8d0b0ac11b765c/cmd/templates.go#L26
