### ISSUE TITLE
bug: `qri unpublish@NOT_MOST_RECENT_HASH` has bugs 

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#984]
From @Mr0grog via discord:

> So what I was seeing was basically that, if I ran qri status there were no changes in my working directory, and if I ran qri log, I had three versions. Then I unpublished the earliest version, and was left with qri status showing that I suddenly had local changes and qri log showing I only had one version (the earliest version). So what I meant by "changed my dataset in my repo" was that qri appeared to have lost the latest two versions of my dataset (although it thankfully didn't change my working directory).

Adding my own experience to this. If you publish or unpublish at a specific commit, Qri then assumes that that commit is head (has that version be head in the repo). I have logbook in my version of qri, so `qri log` works fine. However, if you `qri get me/dataset_name` (so basically asking for head in the repo) it will give you back the last specific version you published or unpublished with.

**Comment by b5** [comment]
OK, we've nailed down the source of the issue:
https://github.com/qri-io/qri/blob/13485065598b924a144825e97a9a48cb6492a360/base/ref.go#L24-L31

The final call in [lib.RemoteMethods.Unpublish](https://github.com/qri-io/qri/blob/13485065598b924a144825e97a9a48cb6492a360/lib/remote.go#L151) sets the publication status, which is calling `PutRef` and clobbering our HEAD reference.

For the purposes of triage, I'm going to split this issue in two:

### Publish & Unpublish only applies to whole datasets
Make it an error to run `qri publish` or `qri publish --unpublish` on anything other than a dataset alias (`name/peername` combo, with nothing after the `@` symbol. This also applies equivalent API commands. Given that Qri currently lacks the tools to do the right thing, we shouldn't let users do things that'll mess up their repo. We'll use this issue to track this first step, and close it once these checks are in place.

### Add a feature for unpublishing specific commits
We very much _do_ want this version-specific publication control to happen, and have lots of infrastructure in place to support such a feature. I've filed #998 to track the feature

**Comment by dustmop** [comment]
Made a change to disallow publishing or unpublishing specific versions: https://github.com/qri-io/qri/pull/999.

**Comment by b5** [comment]
Cool, I'm marking this as closed. Onward to #998!
