### ISSUE TITLE
renaming a dataset must write log operations 

### ISSUE THREAD

**Issue by b5** [qri-io/qri#997]
currently we aren't properly tracking renaming properly in logbook, which means we won't be able to use logbook as a canonical source of naming events. We're also _very_ short on rename tests in general.

* Write a test that proves rename presently doesn't work on the CLI.
* Write a test that proves logbook operations aren't being written on renaming
* Add calls to logbook to write an operation to the dataset namespace on rename
* make tests pass
* party

**Comment by dustmop** [comment]
Related: https://github.com/qri-io/qri/issues/993.
